### ISSUE TITLE
[Feature Request] Draft 2020-12 support for schema definitions

### ISSUE THREAD

**Issue by AE1NS** [microsoft/monaco-editor#3160] opened 2022-06-23 09:16 UTC
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Are you going to support the the Draft 2020-12 version for schema definitions in the future? When I set `$schema: 'https://json-schema.org/draft/2020-12/schema',` inside my schema objects, I get this output in my monaco editor: `Draft 2020-12 schemas are not yet fully supported.(768)`.

With the new draft https://json-schema.org/draft/2020-12/release-notes.html we could i.e. use the `unevaluatedProperties` feature.

In my case, I could solve the issue described here: https://stackoverflow.com/questions/64143406/allow-additional-properties-in-reference-schemas-but-none-else

**Comment by mjperrone** [comment] 2023-09-29 23:03
I would be interested in this support

**Comment by elitemike** [comment] 2023-10-24 16:01
I could use this as well

**Comment by elitemike** [comment] 2024-03-06 18:54
Has there been any movement on this?  I'm trying to put in a work around for my users and it's not very clean.

**Comment by aeschli** [comment] 2024-12-20 17:32
duplicate of https://github.com/microsoft/vscode/issues/165219

**Closed by aeschli** 2024-12-20 17:32 UTC
Labels: feature-request

**Comment by StefanR23** [comment] 2025-01-06 10:58
:(  Monaco is great. I'm using it in our react app to edit JSON files without VSCode

I download the 2020 spec and registered it - it seems almost to work by setting `monaco.languages.json.DiagnosticsOptions`

```
import { applicator } from "./2012-12/applicator";
import { content } from "./2012-12/content";
import { core } from "./2012-12/core";
import { formatAnnotation } from "./2012-12/format-annotation";
import { formatAssertion } from "./2012-12/format-assertion";
import { meta } from "./2012-12/meta";
import { metaData } from "./2012-12/meta-data";
import { unevaluated } from "./2012-12/unevaluated";
import { validation } from "./2012-12/validation";

export const vsCodeJsonSchema = [
    {
        uri: "https://json-schema.org/draft/2020-12/schema",
        fileMatch: ["*.schema.json"],
        schema: meta
    },
    {
        uri: "https://json-schema.org/draft/2020-12/meta/content",
        schema: content
    },
    {
        uri: "https://json-schema.org/draft/2020-12/meta/validation",
        schema: validation
    },
    {
        uri: "https://json-schema.org/draft/2020-12/meta/format-annotation",
        schema: formatAnnotation
    },
    {
        uri: "https://json-schema.org/draft/2020-12/meta/applicator",
        schema: applicator
    },
    {
        uri: "https://json-schema.org/draft/2020-12/meta/unevaluated",
        schema: unevaluated
    },
    {
        uri: "https://json-schema.org/draft/2020-12/meta/format-assertion",
        schema: formatAssertion
    },
    {
        uri: "https://json-schema.org/draft/2020-12/meta/meta-data",
        schema: metaData
    },
    {
        uri: "https://json-schema.org/draft/2020-12/meta/core",
        schema: core
    },
];```

but the language specific keywords are not working `$dynamicAnchor`, `$dynamicRef` etc.
![Image](https://github.com/user-attachments/assets/2049fa49-c81c-4c88-b9c3-cfa348a6be82)

IMHO therefore the json specification needs to be implemented in the monaco first/as well.
