### ISSUE TITLE
Editor in an Electron app, autocomplete not working

### ISSUE THREAD

**Issue by MirageDT** [microsoft/monaco-editor#2282] opened 2020-12-22 21:24 UTC
**monaco-editor version:** 0.20.0
**Browser:** Electron through Capacitor
**OS:** Windows 10
**Playground code that reproduces the issue:** Unable to reproduce the issue

I am deeply sorry for bothering you with an issue that only happens to me. I have searched far & wide on the web and I did'nt find a SINGLE issue that was addressing my problem. My last hope is for you guys to help me out ...

# Context

I am trying to use the Monaco editor in an Electron application. The editor itself works, but the autocomplete shows "Loading ..." continuously : 

![image](https://user-images.githubusercontent.com/70582541/102934139-e8bd2500-44a3-11eb-8327-2db0af3d147f.png)

I am using Angular and the following library : https://www.npmjs.com/package/@materia-ui/ngx-monaco-editor

In their documentation they explain that you can load the editor from a remote URL, which I do : 

```
  providers: [
    {
      provide: MONACO_PATH,
      useValue: 'https://unpkg.com/monaco-editor@0.20.0/min/vs',
    },
  ],
```

Everything works well, except for a single network operation that fails : 

![image](https://user-images.githubusercontent.com/70582541/102934307-28840c80-44a4-11eb-9116-912c94ec596d.png)

I have absolutely NO IDEA why is this not working, and I can't reproduce it in any other project. 

I checked some online examples such as this one : https://stackblitz.com/edit/materia-ngx-monaco-editor-example

And copied the code verbatim, but I am still having the issue. 

I tried cleaning the cache, recreating the application, nothing works ... 

Would you have any idea about it ? 

Thank you in advance and again, sorry for the inconvenience !

PS : here are all of my networks call if it might help : 

![image](https://user-images.githubusercontent.com/70582541/102934734-03dc6480-44a5-11eb-8fc8-08671e893a9c.png)

**Comment by alexdima** [comment] 2020-12-29 15:35
This is very weird. The bundle `vs/base/worker/workerMain.js` at `https://unpkg.com/monaco-editor@0.20.0/min/vs/base/worker/workerMain.js` already contains the loader and the `vs/base/common/worker/simpleWorker` module, so it is very weird that those network requests (for `loader.js` and `simpleWorker.js`) appear. I have seen a lot of weirdness with how Chromium and subsequently Electron implements caching for web workers. Can you try running Electron with a new user data dir to rule out any caching problems? What is the content of `https://unpkg.com/monaco-editor@0.20.0/min/vs/base/worker/workerMain.js` if you click on it on the network tab. What is the full `data:` URL that the web worker is started off (the one above `workerMain.js`)?

**Comment by Maryannah** [comment] 2020-12-29 15:56
Hi @alexdima, thank you for your interest !

I decided to go back from scratch and implement step by step the editor. I finally managed to find the root cause of the issue : electron offers a node integration, as well as a node integration **in the workers**. The latter was found at fault : disabling it resulted in the issue resolving itself !

I don't know if you want to close this issue or not, maybe this is something to investigate, but as far as I am concerned, I have no more issue regarding the auto complete !

**Comment by Maryannah** [comment] 2020-12-29 16:06
Hi @alexdima, thank you for your interest !

I decided to go back from scratch and implement step by step the editor. I finally managed to find the root cause of the issue : electron offers a node integration, as well as a node integration **in the workers**. The latter was found at fault : disabling it resulted in the issue resolving itself !

I don't know if you want to close this issue or not, maybe this is something to investigate, but as far as I am concerned, I have no more issue regarding the auto complete !

PS : I'm using another account because I'm not on my own computer right now and don't have Google sync for the passwords

**Closed** 2020-12-29 16:23 UTC
Labels: needs-more-info
