### ISSUE TITLE
[Bug] Hover shown outside of visible area below editor

### ISSUE THREAD

**Issue by letmaik** [microsoft/monaco-editor#2819] opened 2021-12-12 00:06 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// Configures two JSON schemas, with references.

var jsonCode = "{\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n}";
var modelUri = monaco.Uri.parse('a://b/foo.json'); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, 'json', modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	validate: true,
	schemas: [
		{
			uri: 'http://myserver/foo-schema.json', // id of the first schema
			fileMatch: [modelUri.toString()], // associate with our model
			schema: {
                title: "Record of employee",
				type: 'object',
				properties: {
					p1: {
						type: "string"
					}
				},
                required: ["p1"]
			}
		},
		{
			uri: 'http://myserver/bar-schema.json', // id of the second schema
			schema: {
				type: 'object',
				properties: {
					q1: {
						enum: ['x1', 'x2']
					}
				}
			}
		}
	]
});

monaco.editor.create(document.getElementById('container'), {
	model: model
});
```

### Actual Behavior

The hover is not visible because it is shown after the closing `}` at the end of the document which is not in view.

### Expected Behavior

The hover should display where the squiggly line is.

**Comment by ValeraS** [comment] 2021-12-12 01:27
To correctly show widgets in this layout, set `fixedOverflowWidgets: true` in editor options.

**Comment by letmaik** [comment] 2021-12-12 11:42
> To correctly show widgets in this layout, set `fixedOverflowWidgets: true` in editor options.

This fixes it in the playground but not in a standalone example that doesn't use iframes (if that's related anyway). Copy the following into a file and open it straight in a browser (no need for a server). Note that the hover displays at the expected location if there is not enough space below the editor (resize your browser height to play with it).

```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Monaco editor</title>
    <link rel="stylesheet" data-name="vs/editor/editor.main"
        href="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.31.0/min/vs/editor/editor.main.min.css">
</head>

<body>
    <div id="container" style="width: 500px; height:300px;border:1px solid black;"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.31.0/min/vs/loader.min.js"></script>
    <script>
        // require is provided by loader.min.js.
        require.config({ paths: { 'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.31.0/min/vs' } });
        require(["vs/editor/editor.main"], () => {

            // a made up unique URI for our model
            const modelUri = monaco.Uri.parse('a://b/foo.json')
            const jsonCode = "{\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n}";
            const model = monaco.editor.createModel(jsonCode, 'json', modelUri)

            monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
                validate: true,
                schemaValidation: 'error',
                schemas: [
                    {
                        uri: 'http://myserver/foo-schema.json',
                        fileMatch: [modelUri.toString()],
                        schema: {
                            title: "Record of employee",
                            type: 'object',
                            properties: {
                                p1: {
                                    type: "string"
                                }
                            },
                            required: ["p1"]
                        }
                    },
                ]
            });

            monaco.editor.create(document.getElementById('container'), {
                model: model,
                fixedOverflowWidgets: true
            });
        });
    </script>
</body>

</html>
```

![image](https://user-images.githubusercontent.com/530988/145710704-2dac490f-c0bd-4dd0-83b5-f32ef59004ca.png)

**Comment by hediet** [comment] 2023-03-09 15:20
Duplicate of https://github.com/microsoft/monaco-editor/issues/2793

**Closed by hediet** 2023-03-09 15:20 UTC
Labels: bug, editor-hover
