### ISSUE TITLE
JSON validation dose not work for certain JSON schema

### ISSUE THREAD

**Issue by young-do** [microsoft/monaco-editor#1919] opened 2020-04-13 06:26 UTC
**monaco-editor version:** 0.20.0
**Browser:** chrome 80.0.3987.163
**OS:** macOS 10.15.4
**Playground code that reproduces the issue:**

I found that the editor is not validating JSON data for certain JSON schema. 
Below is an example for that case.
The situation is the same in the link below and locally.
I think this is **a bug**.

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

```js
var mySchema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Is this a Bug?",
    "type": "object",
    "properties": {
        "fruits": {
            "description": "Start with apple",
            "type": "array",
            "items": [
                { "$ref": "#/definitions/apple" }
            ],
            "additionalItems": {
                "$ref": "#/definitions/others"
            },
            "minItems": 1
        }
    },
    "required": [ "fruits" ],


    "definitions": {
        "apple": {
            "type": "object",
            "properties": {
                "name": { "enum": [ "apple" ] },
                "price": { "type": "string" },
            },
        },
        "others": {
            "type": "object",
            "oneOf": [
                { "$ref": "#/definitions/banana" },
                { "$ref": "#/definitions/orange" },
            ]
        },

        "banana": {
            "type": "object",
            "properties": {
                "name": { "enum": [ "banana" ] },
                "price": { "type": "string" },
            },
        },
        "orange": {
            "type": "object",
            "properties": {
                "name": { "enum": [ "orange" ] },
                "price": { "type": "string" },
            },
        }
    }
};

var model = monaco.editor.createModel('', "json");

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    schemas: [{
        uri: "test", // id of the first schema
        fileMatch: ['*'], // associate with our model
        schema: mySchema
    }],
    enableSchemaRequest: false,
    allowComments: false
});

monaco.editor.create(document.getElementById("container"), { model: model });
```

* sample JSON data
```
{
    "fruits": [
        {
            "name": "apple"
        },
        {
            "name": "banana"
        },
        {
            "name": "apple" // This line is not valid
        }
    ]
}
```

* JSON validation results are not being displayed
![](https://i.imgur.com/sxYotYm.png)
![](https://i.imgur.com/mpBC07k.png)

**Comment by young-do** [comment] 2020-05-11 07:52
Additionally, from what I have checked so far, I think the keyword 'oneOf' is directly related to this issue.

(You may think that there is a problem with the schema, but in the links below, the schema and examples work as desired.)

https://www.jsonschemavalidator.net/
https://ajv.js.org/

**Comment by brandonam** [comment] 2020-05-28 16:24
I can confirm this issue as well

**Comment by brandonam** [comment] 2020-06-10 11:58
@young-do - Have you found a work around for this?

**Comment by aeschli** [comment] 2020-09-09 07:59
duplicate of https://github.com/microsoft/vscode/issues/75394

**Closed by aeschli** 2020-09-09 07:59 UTC
Labels: monaco-json
