### ISSUE TITLE
Firefox does not respond to mouse wheel events, the scroll bar does not move

### ISSUE THREAD

**Issue by netnr** [microsoft/monaco-editor#1556] opened 2019-08-15 23:48 UTC
**monaco-editor version:** 0.17.0
**Browser:** Firefox 68.0.2 (64 bit)
**OS:** Windows Server 2019

![me](https://user-images.githubusercontent.com/10579621/63133979-19609500-bffa-11e9-8df2-5209968b2397.gif)

**Comment by spahnke** [comment] 2019-08-16 10:19
Duplicate of #1353 which will apparently be fixed in the next version

**Comment by siddhant1** [comment] 2019-08-18 09:05
https://github.com/microsoft/monaco-editor/issues/1353#issuecomment-515222615

**Comment by DenysVuika** [comment] 2019-09-02 20:12
As of 0.17.1, the problem is still there and not fix despite the #1353 being closed

**Comment by rebornix** [comment] 2019-09-04 18:38
0.18.0 fixed this issue.

**Closed by rebornix** 2019-09-04 18:38 UTC

**Comment by netnr** [comment] 2019-09-04 22:05
![GIF](https://user-images.githubusercontent.com/10579621/64295088-07439800-cfa3-11e9-9adc-547685ddb469.gif)

Rolling height is too short v0.18.0

@rebornix

**Comment by ransagy** [comment] 2019-09-23 13:41
Scrolling (and speed) seems fixed in 0.18.1.
