### ISSUE TITLE
errors.ts:33 Uncaught Error: Cannot read property 'startLineNumber' of undefined

### ISSUE THREAD

**Issue by gujiman** [Microsoft/monaco-editor#238] opened 2016-10-15 16:03 UTC
`monaco-editor` npm version: 0.7.0
Browser: Chrome
OS: Windows 7

Hi Team,

Steps to create the error:
1) goto https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-tokens-and-colors
2) right-click in the preview window and select "Format Code"
3) look at the console for the following error:

errors.ts:33 Uncaught Error: Cannot read property 'startLineNumber' of undefined(…)(anonymous function) @ errors.ts:33

**Comment by alexandrudima** [comment] 2016-10-18 12:52
yeah, looks like html format is broken

**Comment by JKillian** [comment] 2016-10-18 17:11
dupe of #227 for reference

**Comment by aeschli** [comment] 2016-10-19 08:46
I updated the version of monaco-html that contains the fix (and more). @alexandrudima Want to publish an update monaco-editor?

**Comment by alexandrudima** [comment] 2016-10-19 08:50
@aeschli Release notes text?

**Comment by aeschli** [comment] 2016-10-19 08:57
Just bug fixes

**Comment by alexandrudima** [comment] 2017-01-18 10:21
This is already fixed in `monaco-html` and the fix will come out with the v0.8.x release

**Closed by alexandrudima** 2017-01-18 10:21 UTC
