### ISSUE TITLE
Clicking on an empty line with Shadow Dom doesn't work.

### ISSUE THREAD

**Issue by kolobok001** [microsoft/monaco-editor#2290] opened 2020-12-30 05:10 UTC
I am using an example from [shadow-dom sample](https://github.com/microsoft/monaco-editor-samples/tree/master/browser-amd-shadow-dom). When I make a new line using enter, and try to click on it with the mouse and insert a text, I cannot do it . I can get to this line using the arrows on the keyboard. When I try to use the example from  [browser-amd-editor](https://github.com/microsoft/monaco-editor-samples/tree/master/browser-amd-editor) it everything works fine.(See gif)

**monaco-editor version:** 0.21.2
**Browser:** Chrome 87.0.4280.88(everything is ok in fierfox)
**OS:** Windows 10
![bug shadow dom](https://user-images.githubusercontent.com/44198169/103331283-bf9a2700-4a97-11eb-8146-cf2dbcb6e1b3.gif)

**Comment by alexdima** [comment] 2020-12-30 08:27
Duplicate of #2192

**Closed by alexdima** 2020-12-30 08:27 UTC
