### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#3080] opened 2022-04-22 03:14 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById('container'), {
	value: jsCode,
	language: 'javascript'
});
var editor1 = monaco.editor.create(document.getElementById('container1'), {
	value: jsCode,
	language: 'javascript'
});
var myCondition1 = editor.createContextKey(/*key name*/ 'myCondition1', /*default value*/ false);
var myCondition2 = editor.createContextKey(/*key name*/ 'myCondition2', /*default value*/ false);

editor.addCommand(
	monaco.KeyCode.Tab,
	function (e) {
		// services available in `ctx`
 console.log(111,e)
	},
	'myCondition1 && myCondition2'
);
editor1.addCommand(
	monaco.KeyCode.Tab,
	function (e) {
		// services available in `ctx`
 console.log(222,e)
	},
	'myCondition1 && myCondition2'
);
myCondition1.set(true);

setTimeout(function () {
	alert('now enabling also myCondition2, try pressing Tab!');
	myCondition2.set(true);
	// you can use myCondition2.reset() to go back to the default
}, 2000);
```

### Actual Behavior

Only editor1 has addCommand  (only console 222)

### Expected Behavior

all has that command  (can console  111 and can console 222 in different editor)

### Additional Context

These two commands should not correspond to each other, but the latter will replace the former, resulting in no addCommand in the editor
I want Perform different operations in different editors （console 111 console 222）

**Comment by Prinzhorn** [comment] 2022-04-25 10:09
I think this is a duplicate of https://github.com/microsoft/monaco-editor/issues/2947

**Comment by y912765390** [comment] 2022-04-26 00:40
> I think this is a duplicate of #2947

Yes  thank you very much

**Comment by hediet** [comment] 2023-02-07 12:41
Closing as duplicate of #2947

**Closed by hediet** 2023-02-07 12:41 UTC
