### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by kia** [microsoft/monaco-editor#3517] opened 2023-01-30 15:37 UTC
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

How can I disable the context menu appearing by mouse right click on the scroll bar ?
![image](https://user-images.githubusercontent.com/123203/215522077-d31b8138-fdb6-4b47-a417-0d850f542cfe.png)

**Comment by hediet** [comment] 2023-02-16 16:13
Closing as duplicate of #3559

**Closed by hediet** 2023-02-16 16:13 UTC
Labels: *question
