### ISSUE TITLE
Model Markers when called onDidChangeModelContent is not synchronous

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2323] opened 2021-01-28 14:37 UTC
**monaco-editor version:** 0.21.2
**Browser:** Chrome 
**OS:** Mac OS
**Playground code that reproduces the issue:**

I have a use case like, I have to list down all the markings in the editor (due to syntax errors) 
For that, I tried `monaco.editor.getModelMarkers(modelId)` inside `onDidChangeModelContent` callback but the markings array returned is having certain delay (which i guess will be different on different applications scenarios). I tried this inside a `setTimeout` function having delay value 0, still results the same

```js
var editor = monaco.editor.create(document.getElementById("container"), {
    value: '',
    language: "json"
});

editor.onDidChangeModelContent(function () {
    const model = editor.getModel();
    console.log(monaco.editor.getModelMarkers(model.id));
    setTimeout(function () {
        console.log('INSIDE TIMEOUT',monaco.editor.getModelMarkers(model.id));
    }, 0)
})
```
**Expected** : A Callback which gets called after all the markings in the model are drawn for each model content change

**Current Behaviour**

https://user-images.githubusercontent.com/29809906/106152749-d077ae80-61a3-11eb-8cb3-4583fcdd1160.mov

**Output with Timeout**

<img width="1621" alt="Screen Shot 2021-01-28 at 7 52 28 PM" src="https://user-images.githubusercontent.com/29809906/106152990-146ab380-61a4-11eb-9b97-06a001995854.png">

Please update me, is there any configuration (or) callback which exists to handle this case
I also tried, `onDidChangeModelDecorations` , it is getting called multiple times for every change in the model content

**Comment by alexdima** [comment] 2021-01-28 20:56
Duplicate of #313

**Closed by alexdima** 2021-01-28 20:56 UTC

**Comment by Pranomvignesh** [comment] 2021-01-29 05:43
Thanks @alexdima , For adding `onDidChangeMarker` in monaco-editor@0.22.0
