### ISSUE TITLE
There is an error

### ISSUE THREAD

**Issue by cyulin** [microsoft/monaco-editor#2029] opened 2020-07-07 12:14 UTC
![image](https://user-images.githubusercontent.com/10137410/86779635-60320000-c08e-11ea-9a22-7bec0be0c572.png)

**Comment by alexdima** [comment] 2020-09-09 14:05
The language is `javascript`.
The content is `return 111xxx`
The error is:
```
Uncaught Error: Cannot read property 'getStart' of undefined

TypeError: Cannot read property 'getStart' of undefined
    at a (tsWorker.js:21)
    at tsWorker.js:21
    at Function.n.with (tsWorker.js:21)
    at Object.getCodeActions (tsWorker.js:21)
    at tsWorker.js:21
    at Object.e.flatMap (tsWorker.js:21)
    at Object.n.getFixes (tsWorker.js:21)
    at tsWorker.js:21
    at Object.e.flatMap (tsWorker.js:21)
    at Object.getCodeFixesAtPosition (tsWorker.js:21)
    at editor.main.js:53
```

**Comment by alexdima** [comment] 2020-09-09 14:06
fyi @orta

**Comment by alexdima** [comment] 2020-09-18 18:26
Duplicate of #1638, because this is also fixed by https://github.com/microsoft/monaco-typescript/commit/0ac03ae5cd15be689e7806c038269eb162bc5bf0

**Closed by alexdima** 2020-09-18 18:26 UTC
Labels: bug, monaco-typescript, upstream
