### ISSUE TITLE
Window scroll jumps when placed in a scrolling element and typing

### ISSUE THREAD

**Issue by mkhatib** [Microsoft/monaco-editor#476] opened 2017-06-23 07:45 UTC
monaco-editor version: 0.X.Y
Browser: Chrome
OS: Mac OS X
Steps or JS usage snippet reproducing the issue:

* Include a long sized Monaco editor in a scrollable container.
* Scroll the container down where you keep the top of the monaco editor's TOP just above the viewport
* While the cursor in the viewport and inside monacho editor type anything
* Notice the page just jumps the scroll to bring Monaco editor's TOP to the middle of the screen.

## Debugging notes
I traced this back to the `textarea` used as the back-end of the editor selection. The text area position seems to be `top:0` and its height seem to be only 10 or so lines. The browser by default will scroll to the out-viewport focused input when typing happens.

I was able to "lower" the effect of the scroll jump by forcing textarea `height: 100%` and set its `line-height: 1000%` to a large value. This way the text area cursor is always in the viewport along when the monacho editor is. This is obviously a hack - but might gives pointers to how to fix this. Not sure if which one of these the best performance wise:

* Keep the textarea position in sync with the actual cursor of the monacho editor.
* Use a 100% text area with same count of rows that are visible in monacho editor
* Maybe use the line-height hack but dynamically calculate it based on the height of the monacho editor or the line ratio to the line numbers that is displayed in the textarea.

I've tried the following code in the playground.

```javascript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

monaco.editor.create(document.getElementById("container"), {
	value: [
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
        "function hello() {\n\talert('Hello world!');\n}\n\n\n\n\n\n",
    ].join('\n'),
	language: "javascript",
});
```

```html
<div id="outer" style="height: 300vh">
    <h1>Hello</h1>
    <h1>Hello</h1>
    <h1>Hello</h1>
    <h1>Hello</h1>
    <h1>Hello</h1>
    <h1>Hello</h1>
    <h1>Hello</h1>
    <div id="container" style="height:100%;"></div>
    <h1>Hello</h1>
    <h1>Hello</h1>
    <h1>Hello</h1>
    <h1>Hello</h1>
    <h1>Hello</h1>
</div>
```

And then if you scroll the `outer`

**Comment by alexandrudima** [comment] 2017-06-23 07:54
Duplicate of #113

Indeed, browsers will try as much as possible to reveal the focused element. On master, we position the textarea always with the cursor. I still need to test it, but I think this should reduce the jumpiness substantially

**Comment by mkhatib** [comment] 2017-06-23 21:35
Thanks @alexandrudima for the update! Looking forward to try `0.9.x`.

**Closed** 2017-06-28 10:39 UTC
