### ISSUE TITLE
Allow merging of custom and default completion items

### ISSUE THREAD

**Issue by jhndnnqsc** [microsoft/monaco-editor#2555] opened 2021-06-29 21:10 UTC
My unsuccessful searching to solve this makes me think this needs to be a feature request - I would like the ability to merge the automatically generated completion items with my suggested completion items. I have a sample here - https://github.com/jhndnnqsc/monaco-test/blob/main/src/App.js. In this example, if the user hits ctrl+space provideCompletionItems returns an empty array and the automatic list is shown.

![image](https://user-images.githubusercontent.com/17261553/123867650-d8bb4d80-d8eb-11eb-86f3-e17a4a315fb5.png)
 
If the user hits the '.' character a suggestion list is returned - in this case only the suggested items are included

![image](https://user-images.githubusercontent.com/17261553/123867784-0a341900-d8ec-11eb-885c-c29876d69cd1.png)

It seems like it would be useful to be able to automatically combine the two lists - if there is a method for that already please let me know.

**Comment by rcjsuen** [comment] 2021-07-01 11:16
@alexdima This looks like a duplicate of #1850 to me.

**Closed** 2021-07-01 11:22 UTC
Labels: help wanted, suggest
