### ISSUE TITLE
Scrolling does not work in IE 11

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#1573] opened 2019-09-05 06:21 UTC
**monaco-editor version:** 0.18.0
**Browser:** IE 11
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**
Reproducible on the [Monaco Website](https://microsoft.github.io/monaco-editor/) and in the playground.

It works with the keyboard (Ctrl+Up/Down), but not with the scroll wheel.

**Comment by ulrichb** [comment] 2019-09-05 17:59
Related: In Firefox it works now, but scrolling is very "slow" (in comparison to Chrome).

**Comment by brijeshb42** [comment] 2019-09-06 06:06
For the same amount of scroll (or wheel), firefox is firing the event very infrequently and with very low `deltaY` compared to chrome.

**Comment by ulrichb** [comment] 2019-09-06 13:28
=> #1575

**Comment by alexandrudima** [comment] 2019-09-18 16:26
Duplicate of #1575

**Closed by alexandrudima** 2019-09-18 16:26 UTC
