### ISSUE TITLE
Invisible selection for blank lines

### ISSUE THREAD

**Issue by ragnard** [Microsoft/monaco-editor#427] opened 2017-04-23 19:44 UTC
monaco-editor version: 0.8.3
Browser: Safari Version 10.1 (12603.1.30.0.34)
OS: macOS Sierra 10.12.4 (16E195)

Selecting one or more blank lines in Safari shows no selection (but it does in Chrome) and instead looks very confusing. Screenshots from [playground](https://microsoft.github.io/monaco-editor/playground.html)

![monaco-invisible-select](https://cloud.githubusercontent.com/assets/882/25316851/da014650-286d-11e7-9254-1759743c4598.gif)

A consequence is that clicking on line numbers for empty lines puts the cursor on the next line without any visible selection:

![monaco-line-click-off-by-one](https://cloud.githubusercontent.com/assets/882/25316854/f3eb858a-286d-11e7-8c6b-3090a46503b9.gif)

**Comment by ragnard** [comment] 2017-04-23 20:15
Running the editor from source as described [here](https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md#running-the-editor-from-source) on HEAD I can't reproduce the error so possible this has already been fixed.

**Comment by alexandrudima** [comment] 2017-06-09 14:21
:+1: I also cannot reproduce on master so I think this got fixed in the meantime:

![editor-427](https://user-images.githubusercontent.com/5047891/26979584-9baa59be-4d2f-11e7-9275-3e142736ba4b.gif)

**Closed by alexandrudima** 2017-06-09 14:21 UTC
Labels: bug, safari
