### ISSUE TITLE
[Web][Accessibility][A11yMAS][Visual Requirement][MAS1.4.3][Luminosity ratio is less than 4.5:1 for the commands in the command palate.]

### ISSUE THREAD

**Issue by DasaradhaKamjula** [Microsoft/monaco-editor#636] opened 2017-11-20 10:23 UTC
**User Experience:**
User with partial vision disability will not be able to view the controls properly as the luminosity ratio is less than 4.5:1

**Test Environment:**
OS Build: 16299.19
Excel version:1712(8808.1000)

**Attachments:**
![mas1 4 3 commands](https://user-images.githubusercontent.com/33054846/33013660-d7eb4288-ce0a-11e7-8968-24a9a3f6e5e7.png)

**Repro Steps:**
1.Open https://microsoft.github.io/monaco-editor/playground.html.
2.Navigate to editor and press F1.
3.Verify the luminosity ratio for the Commands in the command palate.

**Current Behavior:**
Luminosity ratio is 2.16:1. Luminosity ratio is less than 4.5:1 for both selected and non-selected controls.

**Expected Behavior:**
Luminosity ratio should be more than or equal to 4.5:1 for all the controls.

**Note:**
Bug was found while doing Script Lab Testing.

**MAS Reference:**
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a73546c7-765f-489c-b18f-afb659fe99e6}

**Suggested Fix:**
https://microsoft.sharepoint.com/teams/msenable/mas/pages/mas-details.aspx?masid=1.4.3

**Comment by alexandrudima** [comment] 2018-02-28 13:37
Duplicate of #656

**Closed by alexandrudima** 2018-02-28 13:37 UTC
