### ISSUE TITLE
[Bug] Bad regex for Safari 16.x

### ISSUE THREAD

**Issue by mattgodbolt** [microsoft/monaco-editor#4223] opened 2023-10-25 18:28 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

Since https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0-dev-20230919#example-creating-the-editor-hello-world Safari v16 errors with "invalid group specifier name"

I don't have direct access to Safari 16 to test, but my users are reporting this and can reproduce using the above link on the Monaco playground.

### Monaco Editor Playground Code

```typescript
na/
```

### Reproduction Steps

Visit the playground using safari 16 and it happens immediately

### Actual (Problematic) Behavior

Page fails to load with invalid regex errors at editor.main.js line 63 and 16593

### Expected Behavior

No errors

### Additional Context

Reported on my site as: https://github.com/compiler-explorer/compiler-explorer/issues/5650

**Comment by QuentinUK** [comment] 2023-10-29 17:18
Repoducible in the Monaco editor playground from version 19 

source=v0.44.0-dev-20230919#example-creating-the-editor-hello-world

**Comment by dweitzman-codaio** [comment] 2023-11-09 19:13
cc @rzhao271 , since the negative lookbehind regex https://github.com/microsoft/vscode/pull/193048 seems like the likely cause

**Comment by mjbvz** [comment] 2023-11-09 19:42
Looks like this would only affect users on safari < 16.3: https://caniuse.com/js-regexp-lookbehind. Other browsers have supported it for a while before that

**Comment by dweitzman-codaio** [comment] 2023-11-09 20:11
Yeah, Safari unfortunately isn't evergreen so it's not uncommon for people to be on versions older than 16.3, which is probably why there was a lint error trying to discourage lookbehinds (the PR linked above disabled that lint error)

We've had reports from multiple users, and I was easily able to reproduce on an M1 macbook that's less than 2 years old

**Comment by rzhao271** [comment] 2023-12-08 22:26
I don't have a version of Safari that old, but I'm wondering whether the issue is fixed now?
I changed the regex in the microsoft/vscode repo.

**Closed** 2023-12-16 12:32 UTC
Labels: bug, info-needed
