### ISSUE TITLE
[Bug] The editor adds a lot of blank horizontal space when direction is RTL

### ISSUE THREAD

**Issue by avimaymon** [microsoft/monaco-editor#4141] opened 2023-08-27 15:09 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

set the html direction as RTL and use the monaco editor

### Actual (Problematic) Behavior

![monaco1](https://github.com/microsoft/monaco-editor/assets/29678658/47513d5a-d55a-417d-861a-74c167bdceb8)

### Expected Behavior

to not add these scrollbars and blank spaces

### Additional Context

The css file that is responsible for this is this one
/node_modules/monaco-editor/min/vs/editor/editor.main.css

version in use: 0.34.1

to overcome this bug I had to do this
![image](https://github.com/microsoft/monaco-editor/assets/29678658/c5031174-4739-49fe-b465-0fb02d145f52)

But it's a hack, awaiting your fix, thanks!

**Comment by hediet** [comment] 2023-08-28 14:21
Please provide a reproducible monaco editor playground sample. Thanks!

**Comment by hediet** [comment] 2023-12-13 16:26
Closing because of missing information.

**Closed by hediet** 2023-12-13 16:26 UTC
