### ISSUE TITLE
[Bug]  "Press Alt+F1 for Accessibility Options." is announced, but monico does not respond to alt+f1

### ISSUE THREAD

**Issue by derekriemer** [microsoft/monaco-editor#4394] opened 2024-02-21 20:34 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

Not applicable

### Monaco Editor Playground Code

```typescript
code is not relevant for the str
```

### Reproduction Steps

when using a screen reader, the editor's label says "Editor content;Press Alt+F1 for Accessibility Options. " However, pressing alt+f1 in the playground, and other monico instances I know of, does not actually open any sort of dialog.

str:

1. Turn on any suitable screen reader.
2. Open a monico, then listen to the verbalization on the edit field.
3. Press alt+f1 to get accessibility options.

### Actual (Problematic) Behavior

When not in a vscode environment, monico simply does nothing with this shortcut.

### Expected Behavior

Monico opens the accessibility help, or the verbalization is left out when the core is not inside of vscode.

**Comment by vick08** [comment] 2024-02-21 21:22
Yep, here too. Colab is another place where this bug can be found.
Etc...

**Comment by ben519** [comment] 2024-02-22 03:57
What operating system are you using?

**Comment by vick08** [comment] 2024-02-22 04:23
I am on Mac OS, but I don't believe it matters since the tech is web-based?

**Comment by ben519** [comment] 2024-02-22 04:25
@vick08 that smells like issue #4378. Maybe you can try downgrading to 0.45.0. That worked for me.

**Comment by vick08** [comment] 2024-02-22 05:08
Unfortunately, the places where I am encountering this are not under my control, so I am not able to downgrade. :)
What I wonder about is whether the message is wrong or the context menu is missing. Do you happen to know?
Thanks!

**Comment by derekriemer** [comment] 2024-03-04 11:50
this happens both on windows an mac, idk about linux, I only use linux in terminals, not with browsers.

**Comment by vick08** [comment] 2024-03-12 03:17
I was curious as to whether this is the right place for this issue since no one responded here so far?

**Comment by irinatarn** [comment] 2024-07-09 20:40
We have the same issue and it was flagged by our accessibility team as well. Is there any traction on this bug?

**Comment by vick08** [comment] 2024-10-27 21:39
Apparently not. I am not sure who to mention on this particular issue as i am not aware of who the owner of this repository is.
Anyone watching this bug happens to know?

**Comment by rzhao271** [comment] 2024-12-18 19:57
Duplicate of https://github.com/microsoft/monaco-editor/issues/4674

**Closed by rzhao271** 2024-12-18 19:57 UTC
