### ISSUE TITLE
How do I recreate the vscode's snippet functionality?

### ISSUE THREAD

**Issue by jackrobertscott** [microsoft/monaco-editor#1112] opened 2018-10-13 07:30 UTC
Hello 👋

I would like to have the exact same functionality as vscode does for snippets when they are inserted into the editor.

To clarify; I would like to insert a piece of snippet text into the editor e.g.

```js
const snippetTextToInsert = [
  "for (const ${2:defaultElement} of ${1:defaultArray}) {",
  "\tconsole.log(${2});",
  "}",
];
```

Then have that render in the editor as it does in vscode e.g.

```js
for (const defaultElement of defaultArray) {
  console.log(defaultElement);
}
```

Once the code is inserted in the editor, I would like to be able to press the `TAB` key and have it focus on the variable elements in the order provided i.e. `${1:defaultArray}` then `${2:defaultElement}` and so on.

Thank you!

**Comment by rcjsuen** [comment] 2018-10-13 07:59
Duplicate of #734.

```JavaScript
function createDependencyProposals() {
    return [
        {
            label: 'forloop',
            insertText: {
                value: 'for (const ${2:defaultElement} of ${1:defaultArray}) {\n\tconsole.log(${2});\n}'
            }
        }
    ];
}


monaco.languages.registerCompletionItemProvider('javascript', {
    provideCompletionItems: function(model, position) {
        return createDependencyProposals();
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "for",
    language: "javascript"
});
```

**Comment by rcjsuen** [comment] 2018-10-13 08:56
@jackrobertscott I don't understand fully understand your requirement(s).

Please provide a detailed description of what you imagine the workflow to be and/or describe your use case as it is achieved in VS Code.

**Comment by rcjsuen** [comment] 2018-10-13 22:30
@jackrobertscott There is no good way to do this. See #342.

```JavaScript
let editor = monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "javascript"
});

let contribution = editor.getContribution("snippetController2");
contribution.insert('for (const ${2:defaultElement} of ${1:defaultArray}) {\n\tconsole.log(${2});\n}');
```

**Comment by alexdima** [comment] 2019-12-11 08:35
The TM snippet parser functionality does not ship with the Monaco Editor. But the code is open source. You can extract it from https://github.com/microsoft/vscode/tree/master/src/vs/workbench/contrib/snippets/browser . There you will find a parser which transforms the TM snippet to a snippet the Monaco Editor can understand.

**Closed by alexdima** 2019-12-11 08:35 UTC
Labels: question, suggest
