### ISSUE TITLE
Error positioning cursor inside comment on top

### ISSUE THREAD

**Issue by brune83** [Microsoft/monaco-editor#700] opened 2018-01-22 10:25 UTC
monaco-editor version: 0.10.1
Browser: any
OS: Windows 10
Steps or JS usage snippet reproducing the issue:

The issue happens if your code has a comment on top.
If you position the cursor inside the uncommented code and then you press the KEYUP key until the cursor reaches the comment, you obtain a script error:

TypeError: Cannot read property 'kind' of undefined
    at Object._t [as isJsxOpeningElement] (typescriptServices.js:33)
    at Object.r [as getDocumentHighlights] (typescriptServices.js:59)
    at C (typescriptServices.js:65)
    at D (typescriptServices.js:65)
    at Object.x [as getOccurrencesAtPosition] (typescriptServices.js:65)
    at e.getOccurrencesAtPosition (worker.js:9)
    at t.e.fmr (workerMain.js:7)
    at t._handleMessage (workerMain.js:7)
    at Object.handleMessage (workerMain.js:7)
    at e._handleMessage (workerMain.js:7)
    at Object._t [as isJsxOpeningElement] (typescriptServices.js:33)
    at Object.r [as getDocumentHighlights] (typescriptServices.js:59)
    at C (typescriptServices.js:65)
    at D (typescriptServices.js:65)
    at Object.x [as getOccurrencesAtPosition] (typescriptServices.js:65)
    at e.getOccurrencesAtPosition (worker.js:9)
    at t.e.fmr (workerMain.js:7)
    at t._handleMessage (workerMain.js:7)
    at Object.handleMessage (workerMain.js:7)
    at e._handleMessage (workerMain.js:7)
    at errors.ts:84

You can reproduce this issue also in the Playground page of the project:
https://microsoft.github.io/monaco-editor/playground.html

**Comment by alexandrudima** [comment] 2018-02-28 15:20
Duplicate of #621

**Closed by alexandrudima** 2018-02-28 15:20 UTC
