### ISSUE TITLE
Diff Editor's drag hander in the middle is broken

### ISSUE THREAD

**Issue by lihuishe** [microsoft/monaco-editor#2245] opened 2020-12-04 20:43 UTC
**monaco-editor version:** 0.21.2
**Browser:** Version 87.0.4280.67 (Official Build) (x86_64)
**OS: ** Mac OS 11.0.1 (20B29)(Big Sur)
**Playground code that reproduces the issue:**
1. go to  https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-hello-diff-world
2. try to drag the handle in middle

expected: can shrink and expand width for left and right editor.
actual: not draggable anymore.

this feature used to work on 0.20.0

**Comment by Prinzhorn** [comment] 2020-12-06 11:12
Duplicate of #2203 I think

**Closed** 2020-12-17 08:03 UTC
