### ISSUE TITLE
[Bug] lazily adding extra libs did not trigger re-validation of semantic

### ISSUE THREAD

**Issue by weareoutman** [microsoft/monaco-editor#2866] opened 2021-12-31 07:29 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
    // I don't want to disable semantic validation.
	noSemanticValidation: false,
	noSyntaxValidation: false
});

function addLib() {
    console.log('adding lib...');
    // extra libraries
    var libSource = [
        'declare class Facts {',
        '    /**',
        '     * Returns the next fact',
        '     */',
        '    static next():string',
        '}'
    ].join('\n');
    var libUri = 'ts:filename/facts.d.ts';
    monaco.languages.typescript.typescriptDefaults.addExtraLib(libSource, libUri);
    monaco.editor.createModel(libSource, 'typescript', monaco.Uri.parse(libUri));
}

var jsCode = [
	'"use strict";',
	'',
	'class Chuck {',
	'    greet() {',
	'        return Facts.next();',
	'    }',
	'}'
].join('\n');

monaco.editor.create(document.getElementById('container'), {
	value: jsCode,
	language: 'typescript'
});

// `setEagerModelSync` would not help here.
// monaco.languages.typescript.typescriptDefaults.setEagerModelSync(true);

// Simulate adding libs lazily.
setTimeout(addLib, 2000);
// Changing timeout to `0` will make it work.
```

### Actual Behavior

It shows `Cannot find name 'Facts'` while it shows `class Facts` above which indicates the lib has been loaded.

And when I make any edits, the error disappears.

![image](https://user-images.githubusercontent.com/2338946/147809306-a527a24e-124e-4802-9bfd-0bf983f65e3c.png)

I tried add `monaco.languages.typescript.typescriptDefaults.setEagerModelSync(true)` but it didn't help.

I think a re-validation of semantic should be done automatically after adding libs. Or Monaco should expose an API to do this.

### Expected Behavior

Expect the error message disappears after libs loaded.

**Comment by spahnke** [comment] 2021-12-31 09:52
Is this 0.31.1? If yes, this could have a similar cause as #2841. In that bug the `_onDidChange` event emitter somehow "lost" it's subscribers. In `addExtraLib` another event emitter `_onDidExtraLibsChange` is used. So my first gut instinct says they may be related, especially since the `WorkerManager` is also a subscriber here.

**Comment by weareoutman** [comment] 2021-12-31 10:02
@spahnke Yes, it's 0.31.1.

**Comment by weareoutman** [comment] 2022-01-04 02:29
Code below doesn't work either, and making any edits in editor after loaded libs will not make it working again:

```ts
function addLib() {
    monaco.languages.typescript.typescriptDefaults.addExtraLib(
        'export declare function add(a: number, b: number): number',
        'file:///node_modules/@types/math/index.d.ts'
    );
}

const model = monaco.editor.createModel(
    `import {add} from 'math';\nconst x = add(3, 5);\n`,
    'typescript',
    monaco.Uri.parse('file:///main.ts')
);

monaco.editor.create(document.getElementById('container'), {model});

// Simulate adding libs lazily.
setTimeout(addLib, 2000);
// Changing timeout to `0` will make it work.
```

It seems that not only re-validation is missing, but also the lib has never been loaded.

![image](https://user-images.githubusercontent.com/2338946/148001495-b8d8b5c1-25c5-4ebb-9e0e-274ba1ac7433.png)

**Comment by AlanSorrill** [comment] 2022-01-10 23:23
Ran into the same issue. Here is a good way to reproduce it in playground. badVariable should always be marked as missing, but clicking the button should fix yourVariable. But it doesn't...
monaco.languages.typescript.typescriptDefaults.addExtraLib('var myVariable: string = "cheese"')


let editor = monaco.editor.create(document.getElementById('container'), {
	value: "let ddd: string = 'tst';\nconsole.log(myVariable)\nconsole.log(badVariable)\nconsole.log(yourVariable)",
	language: 'typescript'
});

let btn = document.createElement('button')
btn.innerText = 'Click to Fix'
document.getElementById('container').parentElement.prepend(btn);
btn.onclick = ()=>{
    alert('Should fix yourVariable but doesnt')
    monaco.languages.typescript.typescriptDefaults.addExtraLib('var yourVariable: string = "cheese"')
}

**Comment by mifopen** [comment] 2022-01-27 14:21
@alexdima Could you provide your estimates on this? Or maybe any workarounds? We're heavily relying on this and can't downgrade as several other bugs were resolved in the new version.

**Comment by mifopen** [comment] 2022-01-27 14:25
@hediet cc

**Comment by mifopen** [comment] 2022-02-01 09:25
@hediet Do you need any help with this? Or maybe you could share your estimation, please?

**Closed** 2022-02-02 19:22 UTC
Labels: bug

**Comment by mifopen** [comment] 2022-02-03 11:23
@alexdima Wow, thank you!
Could you please fix npm publish job so that we could test the change asap?
https://github.com/microsoft/monaco-editor/actions/runs/1788088945/workflow

Also, what users have you meant here?
https://github.com/microsoft/monaco-editor/blob/main/.github/workflows/publish.yml#L6
Repo owners?
