### ISSUE TITLE
Broken fold buttons when lineNumbersMinChars is too small

### ISSUE THREAD

**Issue by 2JJ1** [microsoft/monaco-editor#1438] opened 2019-05-07 21:45 UTC
**monaco-editor version:** 0.17.0
**Browser:** Electron.js
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**

```
        editor.create(document.getElementById('codecontainer'), {
            value: [
                'for i,v in pairs(kek) do',
                    '\tprint""',
                    '\tprint""',
                    '\twhile true do',
                        '\t\tdoThing()',
                    '\tend',
                'end',
            ].join('\n'),
            language: 'lua',
            minimap: {
                enabled: false
            },
            scrollbar: {
                horizontal: "hidden",
                verticalScrollbarSize: 5
            },
            lineNumbersMinChars: 1,
            glyphMargin: false,
            showFoldingControls: "always",
        });
```

Clicking on the fold buttons does nothing when I set the lineNumberMinChars to 1. If I set it to 5 or higher, it works fine.

**Comment by alexdima** [comment] 2019-12-11 10:19
I cannot reproduce. I have tweaked the code to make it run at https://microsoft.github.io/monaco-editor/playground.html

```js
monaco.editor.create(document.getElementById('container'), {
    value: [
        'for i,v in pairs(kek) do',
        '\tprint""',
        '\tprint""',
        '\twhile true do',
        '\t\tdoThing()',
        '\tend',
        'end',
    ].join('\n'),
    language: 'lua',
    minimap: {
        enabled: false
    },
    scrollbar: {
        horizontal: "hidden",
        verticalScrollbarSize: 5
    },
    lineNumbersMinChars: 1,
    glyphMargin: false,
    showFoldingControls: "always",
});
```

I believe this has been fixed in the meantime.

**Closed by alexdima** 2019-12-11 10:19 UTC
