### ISSUE TITLE
Accessibility: NVDA reads the suggestion in the Monaco editor will read the whole line

### ISSUE THREAD

**Issue by cary-rowen** [microsoft/monaco-editor#2615] opened 2021-08-16 16:32 UTC
**monaco-editor version:** None
**Browser:** Google Chrome
**OS:** Windows 10 21H1 (x64) build 19043.1165
**Playground code that reproduces the issue:** 

Sorry, this issue may be related to the NVDA screen reader. I hope to investigate this issue together with NVDA. Please check the link below for the relevant steps.

[**Here**](https://github.com/nvaccess/nvda/issues/12721)

I am sorry that I did not fill in the template, but this question is very special. There are detailed steps in the Issue of NVDA Repo.

**Comment by hediet** [comment] 2021-08-17 07:39
Thanks for reporting this issue! Does this also happen when using VS Code?

**Comment by cary-rowen** [comment] 2021-08-17 11:57
Hello,

 this problem does not occur in VS Code, I think NVDA may have made improvements.

Thanks

**Comment by isidorn** [comment] 2021-08-18 12:18
I tried reproducing this using your exact steps on Windows with monaco editor and NVDA and I can not reproduce. This seems to be very specific for NVDA. Why would NVDA append the word `suggestion` in browse mode?

@cary-rowen is this something new, or did this started happening all of a sudden? I believe @hediet did a recent release of Monaco Editor. Can you reproduce with VS Code insiders (I can not)? Also can you maybe take a screenshot when that happens (if possible)?

@hediet do we have inline suggestions enabled in the latest editor?

Code pointer where we compute the aria label for the suggest widget
https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/suggestWidget.ts#L230

**Comment by hediet** [comment] 2021-08-18 13:21
> do we have inline suggestions enabled in the latest editor?

I don't think so, afaik I made it on by default just this release. But it shouldn't change anything.

**Comment by isidorn** [comment] 2021-08-19 09:25
Since the issue is not reproducible with latest monaco-editor I will close this.
This is just an outdated version of the editor. Those websites should update.

**Closed by isidorn** 2021-08-19 09:25 UTC
Labels: accessibility

**Comment by cary-rowen** [comment] 2021-08-19 14:36
OK, thanks for your investigation.
@isidorn
