### ISSUE TITLE
24x7 intellisense not firing

### ISSUE THREAD

**Issue by JKillian** [Microsoft/monaco-editor#623] opened 2017-11-02 18:03 UTC
monaco-editor version: 0.10.1
Browser: Chrome 61
OS: macOS

In previous versions of monaco, 24x7 intellisense, (aka `quickSuggestions` I believe) was on by default. We noticed in our app that it was no longer ever firing. We set `quickSuggestions: true` manually in our editor, but this still doesn't get 24x7 intellisense to fire.

I noticed a similar issue in the playground, but in the case of the playground, it's fixed by setting `quickSuggestions: true`.

Have there been any changes that would cause 24x7 intellisense to stop firing?

![image](https://user-images.githubusercontent.com/1400151/32342285-520dd938-bfd6-11e7-880d-a933488d1a44.png)

**Comment by alexandrudima** [comment] 2017-11-07 16:04
There might be something wrong, I'm not sure. Have you tried the other form:

```
quickSuggestions?: boolean | { other: boolean, comments: boolean, strings: boolean }
```

i.e. `quickSuggestions: { other: true, comments: true, strings: true }`.

This would mean you'd want to see quick suggestions popping up in comments, strings and anywhere else (other)

**Comment by JKillian** [comment] 2017-11-14 22:24
I did try `quickSuggestions: { other: true, comments: true, strings: true }`, but it didn't change the behavior. 

I believe I figured out partly what's happening though! It seems we have two (different) `CompletionItemProvider`s registered for a language. When I trigger auto-complete manually, (i.e. CMD+space), it triggers both providers, and I see the results I expect. When I hit a trigger character of either provider, it triggers the respective provider.

However, 24x7 intellisense only every triggers the second of the two providers. In my case, this second provider is written such that it rarely returns any results.

Do you know if this is intended behavior? Is there a way to designate which provider gets called or have them both get called?

**Comment by alexandrudima** [comment] 2017-11-15 09:50
@jrieken might now more about how multiple providers interact.

**Comment by jrieken** [comment] 2017-11-15 09:57
24x7 IntelliSense only works at the end of words. In JSON a word contains the quotes surrounding it

**Comment by aeschli** [comment] 2017-11-15 14:33
Duplicate of https://github.com/Microsoft/vscode/issues/32480

**Closed by aeschli** 2017-11-15 14:33 UTC
Labels: needs-more-info

**Comment by JKillian** [comment] 2017-11-15 16:13
Thanks for the help all. Although my initial post was slightly misguided, I think the issue in my case wasn't about JSON strings, but about how 24x7 intellisense seems to only trigger one of my completion providers where as manually firing intellisense seems to hit both providers.

If you have any insight on that let me know! I noticed there's some system about scores of providers but haven't figured it out fully yet
