### ISSUE TITLE
[Feature Request] Completition for known Function Parameters if I edit only Function content

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/monaco-editor#3614] opened 2023-02-28 14:53 UTC
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I've a fuction like this:

function aa(td: HTMLTableCellElement, row: number)

but with monaco I only want to endit the inside of the function.
Is there a way, so I can Tell Monaco that "td" and "row" are available as Variables, with their type?

**Comment by hediet** [comment] 2023-02-28 15:43
Duplicate of https://github.com/microsoft/monaco-editor/issues/1661

**Closed by hediet** 2023-02-28 15:43 UTC
Labels: feature-request
