### ISSUE TITLE
Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test

### ISSUE THREAD

**Issue by Wiiseguy** [microsoft/monaco-editor#2069] opened 2020-08-05 11:10 UTC
**monaco-editor version:** 0.20.0
**Browser:** Chrome 84
**OS:** Windows
**Playground code that reproduces the issue:**

Make sure you have your Dev console open when trying to reproduce this.

```js
{
	works: false
}
```

If you place an object literal like the code above in the playground and try CTRL+A or try to selecting from the first accolade  up until part of "works", it will produce this error in the console:
```
Uncaught Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test ''.

Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test ''.
    at Object.e.cast (tsWorker.js:21)
    at a (tsWorker.js:21)
    at tsWorker.js:21
    at Function.n.with (tsWorker.js:21)
    at Object.getCodeActions (tsWorker.js:21)
    at tsWorker.js:21
    at Object.e.flatMap (tsWorker.js:21)
    at Object.n.getFixes (tsWorker.js:21)
    at tsWorker.js:21
    at Object.e.flatMap (tsWorker.js:21)
    at errors.ts:22
```

I get the same error in my local project using monaco-editor 0.20.0, but in addition, it also triggers a breakpoint caused by a `debugger;` statement in the `fail()` method in typescriptServices.js.

**Comment by rcjsuen** [comment] 2020-08-05 11:53
> I get the same error in my local project using monaco-editor 0.20.0, but in addition, it also triggers a breakpoint caused by a `debugger;` statement in the `fail()` method in typescriptServices.js.

This particular issue has been brought up in the past by https://github.com/microsoft/monaco-editor/issues/1937#issuecomment-624006101.

**Comment by jquintozamora** [comment] 2020-08-18 14:49
Hi, I'm also having that issue, which is causing Error log in console and also my error wrapper to trigger.

Is there any plans in place to solve it ?

Thanks

**Comment by alexdima** [comment] 2020-09-18 18:27
Duplicate of #1638, because this is also fixed by https://github.com/microsoft/monaco-typescript/commit/0ac03ae5cd15be689e7806c038269eb162bc5bf0

**Closed by alexdima** 2020-09-18 18:27 UTC
Labels: bug, monaco-typescript, upstream
