### ISSUE TITLE
Cannot redefine property: Position error - Css language

### ISSUE THREAD

**Issue by YauhenPylAurea** [microsoft/monaco-editor#1722] opened 2019-10-24 15:43 UTC
Tried to use `https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-parcel` and got the next error when I tried to use `css` language:

```
main.js:1446 Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:494)
    at webWorker.js:54
(anonymous) @ main.js:1446
css.worker.js:1 Uncaught TypeError: Cannot redefine property: Position
    at Function.defineProperty (<anonymous>)
    at css.worker.js:148
    at Array.forEach (<anonymous>)
    at Object.parcelRequire.ocgq../parser/cssParser.js (css.worker.js:148)
    at f (css.worker.js:1)
    at p (css.worker.js:1)
    at Object.parcelRequire.kA9K../_deps/vscode-css-languageservice/cssLanguageService.js (css.worker.js:150)
    at f (css.worker.js:1)
    at p (css.worker.js:1)
    at Object.parcelRequire.pWYv.../../editor/editor.worker.js (css.worker.js:152)
```

Could you please help with it? thanks

**Comment by alexdima** [comment] 2019-12-20 14:28
Duplicate of #1327

**Closed by alexdima** 2019-12-20 14:28 UTC
