### ISSUE TITLE
[Bug] Different key actions in two editors

### ISSUE THREAD

**Issue by guillegpra** [microsoft/monaco-editor#3084] opened 2022-04-26 09:22 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var editor = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

var editor2 = monaco.editor.create(document.getElementById('container2'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

editor.addCommand(monaco.KeyCode.F9, function () {
	alert('F9 pressed in editor!');
});

editor2.addCommand(monaco.KeyCode.F9, function () {
	alert('F9 pressed in editor2!');
});

editor2.addCommand(monaco.KeyCode.F8, function () {
	editor2.getModel().setValue('console.log("Hello world");');
});
```

### Actual Behavior

When having two editors in the same page, if one includes an action for the e.g.`F9` key event and the other one needs a different behavior for the same key, it currently overrides the previous one for the both editors. Besides, if one requires a key event that the other doesn't, it is now not possible: both editors need to have the same key commands.

For instance, in the example below, `editor2` adds a key binding for `F8` that is not supposed to work in `editor`, but it does. The `F9` event also displays a dialog with "F9 pressed in editor2!" regardless of where it was pressed.

**Playground code that reproduces the issue:**
```javascript
var editor = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

var editor2 = monaco.editor.create(document.getElementById('container2'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

editor.addCommand(monaco.KeyCode.F9, function () {
	alert('F9 pressed in editor!');
});

editor2.addCommand(monaco.KeyCode.F9, function () {
	alert('F9 pressed in editor2!');
});

editor2.addCommand(monaco.KeyCode.F8, function () {
	editor2.getModel().setValue('console.log("Hello world");');
});
```

```html
<div id="container" style="height: 50%"></div>
<hr>
<div id="container2" style="height: 50%"></div>
```

### Expected Behavior

Two or more editors should be able to have different key bindings.

### Additional Context

Since version 0.32.0, it is not possible to have two editors in the same page with different key actions. It worked fine in previous versions. Has this feature been removed or is it a bug?

**Comment by stoanarrr** [comment] 2022-04-26 14:11
duplicate of #2947

**Comment by hediet** [comment] 2023-03-13 15:13
Closing, because this seems to be a duplicate

**Closed by hediet** 2023-03-13 15:13 UTC
Labels: bug, editor-core
