### ISSUE TITLE
"Duplicate function implementation" eror when loading two models with same function name

### ISSUE THREAD

**Issue by shreedhart** [microsoft/monaco-editor#1883] opened 2020-03-24 00:38 UTC
**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Windows 10
**Playground code that reproduces the issue:** 

```js
var editor = monaco.editor.create(document.getElementById("container"), {
	value: "",
	language: "typescript"
});

var model1 = monaco.editor.createModel("function hello() {}", "typescript", monaco.Uri.file("foo"));
editor.setModel(model1);

var model2 = monaco.editor.createModel("function hello() {}", "typescript", monaco.Uri.file("bar"));
editor.setModel(model2);
```

When two models have same function implementation and connected to same editor, there is an "Duplication function implementation" error.

![image](https://user-images.githubusercontent.com/9101715/77376141-ca67a480-6d2c-11ea-8ea6-069a8c8fd0ac.png)

Looks like all models connected to an editor are treated as if they are part of the same project. Is there a way to treat each model as a separate project?

**Comment by alexdima** [comment] 2020-04-02 13:49
Duplicate of https://github.com/microsoft/monaco-editor/issues/1105

**Closed by alexdima** 2020-04-02 13:49 UTC
