### ISSUE TITLE
[Bug] XXX depends on UNKNOWN service YYY again

### ISSUE THREAD

**Issue by BeishaoCao-db** [microsoft/monaco-editor#4229] opened 2023-10-27 21:50 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Additional Context

This bug looks exactly the same as the https://github.com/microsoft/monaco-editor/issues/2941, but with different services not found.

After update to the latest version from 0.39.0 to 0.43.0 (from 3 days ago) we get the following errors:
`Error: [createInstance] ut depends on UNKNOWN service ISuggestMemories.`
`Error: [createInstance] Z depends on UNKNOWN service actionWidgetService.`
`Error: [createInstance] ee depends on UNKNOWN service snippetService.`
`Error: [createInstance] dt depends on UNKNOWN service IMarkerNavigationService.`

One of the stack trace looks like:
```
Error: [createInstance] ee depends on UNKNOWN service snippetService.
  at None (webpack://../node_modules/monaco-editor/esm/vs/platform/instantiation/common/instantiationService.js:280:18)
  at _throwIfStrict (webpack://../node_modules/monaco-editor/esm/vs/platform/instantiation/common/instantiationService.js:79:21)
  at _createInstance (webpack://../node_modules/monaco-editor/esm/vs/platform/instantiation/common/instantiationService.js:67:26)
  at createInstance (webpack://../node_modules/monaco-editor/esm/vs/editor/browser/widget/codeEditorContributions.js:125:56)
  at _instantiateById (webpack://../node_modules/monaco-editor/esm/vs/editor/browser/widget/codeEditorContributions.js:103:17)
  at _instantiateSome (webpack://../node_modules/monaco-editor/esm/vs/editor/browser/widget/codeEditorContributions.js:40:13)
  at initialize (webpack://../node_modules/monaco-editor/esm/vs/editor/browser/widget/codeEditorWidget.js:213:28)
  at super (webpack://../node_modules/monaco-editor/esm/vs/editor/standalone/browser/standaloneCodeEditor.js:66:8)
  at super (webpack://../node_modules/monaco-editor/esm/vs/editor/standalone/browser/standaloneCodeEditor.js:182:8)
  at super (webpack://../node_modules/vscode/tools/injection.js:10:12)
  at None (webpack://../node_modules/monaco-editor/esm/vs/base/common/errors.js:14:26)
```

**Comment by sagivf** [comment] 2023-10-29 10:44
Same here

**Comment by mofux** [comment] 2023-10-30 13:37
Same here as well :(

**Comment by romainr** [comment] 2023-10-30 23:43
All of you on 0.43.0?

**Comment by romainr** [comment] 2023-10-31 13:13
Bit similar https://github.com/microsoft/monaco-editor/issues/2941

**Comment by hediet** [comment] 2023-10-31 14:37
Thanks for reporting, but I cannot reproduce this error in the monaco editor playground.

Could this be a bundling issue?

**Comment by BeishaoCao-db** [comment] 2023-11-01 16:37
We can reproduce it with a extension called Codeium, but not sure if that's the root cause

**Comment by BeishaoCao-db** [comment] 2023-11-01 16:37
We can reproduce it with a extension called Codeium, but not sure if that's the root cause.
@hediet

**Comment by sagivf** [comment] 2023-11-05 07:36
I was able to bisect the commits and found that this commit is what brakes things for us -
https://github.com/microsoft/monaco-editor/commit/e7d7a5b072e74702a912a4c855a3bda21a7757e7

We are using Parcel as the bundler.

**Comment by hediet** [comment] 2023-11-06 11:59
If it does not reproduce in the monaco editor playground, it seems like a bundler issue, which we cannot investigate at the moment.

**Comment by sagivf** [comment] 2023-11-06 15:59
@BeishaoCao-db @mofux @romainr what bundlers are you using?

**Comment by BeishaoCao-db** [comment] 2023-11-06 21:31
We use rollup, we fix one of the error (IMarkerNavigationService) by manually import a service:

e.g.: 
`import 'monaco-editor/esm/vs/editor/contrib/gotoError/browser/markerNavigationService';`

Guess other service can somehow be manually import and fix the error

**Comment by hediet** [comment] 2023-12-13 17:02
> We use rollup, I don't think the bundler is the cause

In that case, please try to reproduce the issue in the monaco editor playground.

Closing for now, as we don't have the resources to investigate third party monaco editor integrations.

**Closed by hediet** 2023-12-13 17:02 UTC
