### ISSUE TITLE
Narrator focus is going to some hidden elements under "New SQL Query" pane.

### ISSUE THREAD

**Issue by naina12345678** [Microsoft/monaco-editor#622] opened 2017-11-02 11:28 UTC
**User Experience:**  
If screen reader focus moves to some hidden element in scan mode, then the users who completely depend on screen reader would not be able to know about the contents.

**Test Environment:**
OS: Windows 10, Version 1703 (OS build 15063.483)
Browser: Edge
Screen Reader: Narrator

**MAS Reference:
![mas4 2 10_focus is going on hidden elements in item mode](https://user-images.githubusercontent.com/33317761/32323721-031a49f6-bfef-11e7-98ad-5a4149cfb12c.jpg)

**
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7BBF8AF12E-731E-4129-A439-077991F93C2C%7D&file=MAS%2033J%20%E2%80%93%20Tracking%20of%20Focus%20and%20Selection%20Attributes.docx&action=default

 

**Repro Steps:**
1. Open https://portal.azure.com and login via valid credentials. 
2. Navigate to all resources.                                 
3. Search for Azure Cosmos DB ( Type -Azure Cosmos DB )
4. Navigate to in Azure Cosmos Azure Cosmos DB account.
5. Navigate to 'Data Explorer' in Azure Cosmos Azure Cosmos DB account and select it.
6. Navigate to Collections and open context menu.
7. Select "New SQL Query " on context menu and navigate to "New SQL query" Pane.
8. Launch Narrator in scan mode using Caps Lock + Space bar.
9. Verify, if narrator focus is going on to some hidden element.

**Actual result:**
Narrator focus is going on some hidden element under "New SQL Query" pane.

**Expected Result:**
Narrator focus should not move to hidden element under "New SQL Query" pane.

**Note:**
1. Issue doesn't exists with Firefox + NVDA.
2. Same issue exists with item mode and scan mode using Narrator.
3. Same issue exists throughout "Data Explorer" pane.

**Comment by naina12345678** [comment] 2017-11-02 11:30
Cosmos Db Linked Bug id:
Bug 72753

**Comment by StommePoes** [comment] 2018-09-14 10:58
I run into the disabled options (find, replace, etc) with NVDA and JAWS when browsing. I can hear they're disabled, but wouldn't realise these weren't sitting out in the open for other users. However this isn't keyboard focus, just virtual cursor. Not sure if this is the same issue?

Top: screenshot after devtools manipulates to make the disabled tools visible.
Bottom: NVDA with the plugin to show virtual focus, green outline is an object. They're correctly read as disabled controls, but I feel the intention is that the panel doesn't exist for any users at all unless expressly called (Ctrl-H makes this panel visible and enabled on Linux but apparently that no longer works on Macs?)
![image description above](https://user-images.githubusercontent.com/136210/45546448-9b11d680-b81d-11e8-915d-a279fca5f7de.png)

**Comment by alexandrudima** [comment] 2018-09-14 15:11
@StommePoes Are you using a super old version of the editor? That sounds like a duplicate of #450

**Comment by StommePoes** [comment] 2018-09-17 11:56
it could be! I am an auditor testing a client's page and when we discovered they were using Monaco, I went looking for any existing bugs that were open and found this bug which didn't seem entirely clear if it was what I was seeing or a Narrator-specific thing.
I can use the #450 in my report to encourage the client to upgrade, thanks!

**Comment by alexandrudima** [comment] 2018-11-12 14:22
This has been fixed since a long time.

**Closed by alexandrudima** 2018-11-12 14:22 UTC
Labels: accessibility
