### ISSUE TITLE
Narrator does not announce suggestions from the SuggestWidget

### ISSUE THREAD

**Issue by xirzec** [Microsoft/monaco-editor#471] opened 2017-06-19 21:11 UTC
monaco-editor version: 0.8.3
Browser: Edge
OS: Windows 10 1703
Steps or JS usage snippet reproducing the issue:

Type some code to trigger suggestions. Presence of suggestions not announced by narrator)

Arrow up/down. Suggestions are never announced by narrator until they are committed.

**Comment by alexandrudima** [comment] 2017-06-20 09:40
Duplicate of #425

**Closed by alexandrudima** 2017-06-20 09:40 UTC
Labels: duplicate

**Comment by xirzec** [comment] 2017-06-20 16:15
Nice! Sorry I forgot to check closed issues too. Thanks for the fix! 👍
