### ISSUE TITLE
Javascript does not honor wordBasedSuggestions = false

### ISSUE THREAD

**Issue by AndersMad** [microsoft/monaco-editor#1980] opened 2020-05-24 00:29 UTC
**monaco-editor version:** v0.20.0

**ISSUE:** Can we have suggest any word suggestions turned off? It confuses. Below repro in playground:
```js
function a() { let myVar; }
myV| // CTRL + SPACE here should not suggest myVar as type any-word
```

**NOTE:** This works in Typescript - only Javascript has the issue. It says its fixed here but its not: https://github.com/microsoft/monaco-editor/issues/907). I assume the `wordBasedSuggestions` is meant to turn this off. 

Thanks!

**Comment by alexdima** [comment] 2020-09-04 16:04
I think this is how TypeScript works. When the language is set to JavaScript, it offers word completions from its side. We just forward them through `monaco-typescript`.

**Comment by os-lmo** [comment] 2021-07-14 17:11
I am also facing this issue. Is there any to plan to fix it soon?

**Comment by hediet** [comment] 2021-07-23 11:50
@orta I think this due to the implementation of suggestions in TypeScript/JavaScript?

**Comment by hediet** [comment] 2021-07-24 11:47
Duplicate of #2136.

See https://github.com/microsoft/monaco-editor/issues/2136#issuecomment-886025174.

**Closed by hediet** 2021-07-24 11:47 UTC
Labels: feature-request, monaco-typescript

**Comment by AndersMad** [comment] 2021-11-04 19:46
TIP: this annoying bug can be fixed with option `suggest: { showFiles: false }` - yes, file 🙄
