### ISSUE TITLE
bug: Refused to evaluate a string as JavaScript because 'unsafe-eval'

### ISSUE THREAD

**Issue by kimbaz** [microsoft/monaco-editor#2488] opened 2021-05-19 12:43 UTC
**monaco-editor version:** 0.24.0
**Browser:** Chrome/Firefox
**OS:**
**Playground code that reproduces the issue:**
- Enable CSP policy without having `'unsafe-eval'` enabled.
- Load the editor

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not 
an allowed source of script in the following Content Security Policy directive...

at eval (<anonymous>)
    at workerMain.js:2
    at editor.main.js:2
```

If you need more details about it please let me know.

**Comment by hediet** [comment] 2021-06-09 13:09
Can you provide a minimal reproducable example?

What would we need to change to fix this?

**Comment by kimbaz** [comment] 2021-06-10 15:34
Hi @hediet,
to reproduce the issue you would need to enable CSP policies (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src) on your test server (i.e. on `express`) and then try to load the editor.
If you need any help setting up express to test it please let me know.

Full exception:
```
editor.main.js:formatted:1259 Uncaught Error: Refused to evaluate a string as JavaScript because
'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive:
"script-src 'self' 'unsafe-inline'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source 
of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

    at eval (<anonymous>)
    at workerMain.js:2
    at editor.main.js:formatted:1259
(anonymous)                           @ editor.main.js:formatted:1259
setTimeout (async)
unexpectedErrorHandler                @ editor.main.js:formatted:1258
onUnexpectedError                     @ editor.main.js:formatted:1271
t.onUnexpectedError                   @ editor.main.js:formatted:1281
Promise.then (async)
then                                  @ editor.main.js:formatted:5898
beginCompute                          @ editor.main.js:formatted:78049
onModelChanged                        @ editor.main.js:formatted:78038
(anonymous)                           @ editor.main.js:formatted:77992
fire                                  @ editor.main.js:formatted:5304
register                              @ editor.main.js:formatted:44643
z                                     @ editor.main.js:formatted:98798
d                                     @ jsonMode.js:2
t.setupMode                           @ jsonMode.js:2
(anonymous)                           @ editor.main.js:formatted:101253
Promise.then (async)
(anonymous)                           @ editor.main.js:formatted:101252
(anonymous)                           @ editor.main.js:formatted:98602
fire                                  @ editor.main.js:formatted:5304
_getOrCreateMode                      @ editor.main.js:formatted:61265
_createModeAndGetLanguageIdentifier   @ editor.main.js:formatted:61254
(anonymous)                           @ editor.main.js:formatted:61241
l                                     @ editor.main.js:formatted:61188
create                                @ editor.main.js:formatted:61239
O                                     @ editor.main.js:formatted:98246
z                                     @ editor.main.js:formatted:98413

```

Source code:

workerMain.js
```js
fetch(t).then((function (e) {
    if (200 !== e.status)
      throw new Error(e.statusText);
    return e.text()
  }
)).then((function (e) {
    e = e + "\n//# sourceURL=" + t,
      (r ? self.eval(r.createScript("", e)) : new Function(e)).call(self),
      n()
  }
)).then(void 0, i)
```
<img width="743" alt="image" src="https://user-images.githubusercontent.com/20518828/121553456-305f4b00-ca09-11eb-8fa7-e6d5e42a80ac.png">

editor.main.js
```js
setTimeout((() => {
    throw e.stack ? new Error(e.message + "\n\n" + e.stack) : e
}
```
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/20518828/121551085-3ce2a400-ca07-11eb-9e3c-e1206aeab0b9.png">

**Comment by mweiss-osi** [comment] 2021-08-09 19:36
Is this still on the table to be fixed?

**Comment by mjiang108** [comment] 2021-09-04 00:17
+1 I am encountering the same issue. Do you know if this will be fixed soon?

**Comment by tjsfdc** [comment] 2021-09-04 14:32
Loading editor in chrome extension is also replicating this issue as manifest v3 now does not allow unsafe-eval  
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#content-security-policy

Is there any known workaround?

**Comment by alexdima** [comment] 2021-09-10 13:58
I've pushed some changes to fall back to `importScripts` when `eval` throws (due to CSP).

**Closed by alexdima** 2021-09-10 13:58 UTC

**Comment by dstrenge** [comment] 2021-09-10 14:13
Why not always use importScripts?

**Comment by anhhnguyen206** [comment] 2021-09-29 20:18
@alexdima hi - thanks for the fix. Do you know when this fix will be release? I saw the commit but I don't see it's getting associated with the release 5 days ago.

**Comment by bhoomij** [comment] 2021-12-01 12:49
@alexdima is this fixed now ? I'm still getting it with monaco-editor@0.30.1

**Comment by alexdima** [comment] 2021-12-01 21:20
@bhoomij The initial issue is resolved. If you get some error, please create a new issue with complete repro steps. You can also test using the nightly builds e.g. `monaco-editor@0.31.0-dev.20211201`.
