### ISSUE TITLE
Searching using regex to highlight multiple lines within my JSON editor.

### ISSUE THREAD

**Issue by aaronpcz** [microsoft/monaco-editor#216] opened 2016-10-03 16:54 UTC
monaco-editor npm version: 0.6.1
Browser: Latest Chrome
OS: Mac OS X El Capitan

I've manage to integrate the Monaco editor into my current project.  I'm having an issue with a particular feature I'm trying to implement and found a possible bug.

I'm looking to search using an regex similar to this:

`/{[\s\S]{1,10}tags.*[\s\S]*?type[\s\S]*?}[\s\S]*?}/g`
- Allowing me to search through the JSON objects that contain keys tags and types at an index (at index will be implemented in code not regex).  IE highlight the 5th JSON object.  Within the project the index (5th in this case) is provided so I need to integrate a search and highlight for Monaco.

To avoid making this complicated to debug, I've found what seems to be the issue

`[\s\S\]` does not seem to either be implemented to actually be able to search over multiple lines of a JSON object.

Here is my search

`
var sceneMediaObjectRegex = /tags[\s\S]*?style/g;
var matches = monacoEditor.getModel().findMatches(sceneMediaObjectRegex, false, true, false, false);`

Results in zero matches found, the json within the editor looks similar to this:
- Anything after the [\s\S]*? causes all searches to return with 0 results. 
- Tested both in project and in the Monaco playground. 
- I can provide some code to be used in the Monaco playground if this will help the investigation.
- Tested the query in various other regex tools to ensure this is a valid and successful regex.

`
{
      "tags": "",
      "type": "text",
      "text": "df",
      "style": {
        "z-index": "1"
      },
      "_id": "57e1b7ad1b196a054287f76c"
    },
    {
      "tags": "",
      "type": "text",
      "text": "text",
      "style": {
        "z-index": "1"
      },
      "_id": "57e1b7ad1b196a054287f76d"
    }
`

Any ideas to point in the correct direction and/or is it possible?

Thanks,
Aaron

**Comment by aaronpcz** [comment] 2016-10-03 17:10
Quick Update:

I've done some more testing

`[\s\S\]*?` works if search is all on the same line.

Might be worth updating issue to resolve searching for multiple lines of a JSON object.

**Comment by alexandrudima** [comment] 2016-10-05 15:41
The issue is that we construct the regex and don't set the multiline flag.

**Comment by aaronpcz** [comment] 2016-10-05 22:42
I've managed to adapt my work to get it to work with the current implementation.

Changing my regex to a string, rather than /regex/ as this form does not have the length property required for the for loop

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/textModel.ts#L801

`" ..  [\\s\\S\\n]*? .. "`

To further this using the /regex/ form does not require the \\ things such as \n and \t
- I've found this line in the dev build output editor.js.  

`var BACKSLASH_CHAR_CODE = '\\'.charCodeAt(0);`

- So in general I think just sticking the string form of regex suits the implementation better.

I also adapted the string of JSON code I've given to the editor to ensure that \t and \n characters are present for my full JSON object.


A force multiline mode could be a nice edition.

**Comment by ZombieProtectionAgency** [comment] 2016-10-14 18:36
If they enable multi-line mode when they detect a linefeed character you could probably toss this in your query `\n{0}` lol

**Comment by alexandrudima** [comment] 2016-10-18 12:53
Yeah, it is sort of silly, but the single line case is implemented differently, a search is executed line-by-line, which involves less memory consumption. (in the multiline case) we need to join the entire text in a large string

**Comment by alexdima** [comment] 2019-12-10 14:37
A workable solution has been found, so closing this..

**Closed by alexdima** 2019-12-10 14:37 UTC
Labels: api, feature-request
