### ISSUE TITLE
scrollbar horizontal 'visible' behaves like 'auto'

### ISSUE THREAD

**Issue by pablonete** [microsoft/monaco-editor#1103] opened 2018-10-11 08:23 UTC
monaco-editor version: 0.14.3
Browser: Chrome
OS: Windows
Steps reproducing the issue:

1. Go to demo: https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-scrollbars
2. Note that options for horizontal scrollbar is 'visible':
```
horizontal: 'visible',
```
3. On the editor in the right side, delete the long line.

Actual: horizontal scrollbar hides up (like if it were 'auto').
Expected: horizontal scrollbar should stay always.

Indeed I cannot see any difference between 'auto' and 'visible' on this demo.

It's not only about this sample. We need this fixed, because we scroll-sync 2 editors and the optional horizontal scrollbar changes the bottom scrolling position, which breaks the synchronization.

**Comment by sungk44** [comment] 2018-10-14 20:05
I'll take a look at this and see what I can do!

**Comment by alexandrudima** [comment] 2018-11-12 09:51
Actually, I think I implemented it like this by design, i.e. the `visible` option is not a 100% equivalent to the CSS `overflow: visible`. The `visible` option is meant to make the editor behave like a native input area. Native input areas get no scrollbars if not necessary and then get scrollbars only when necessary. Those scrollbars do not disappear when the mouse is moved out of the input area... So `visible` means "when there are scrollbars, show them even when the mouse is outside the editor area".

I think for something that behaves similar to `overflow: visible` we would need to create/implement a different option.

**Comment by hediet** [comment] 2023-02-16 17:41
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

**Closed by hediet** 2023-02-16 17:41 UTC
Labels: feature-request, editor-core, out-of-scope
