### ISSUE TITLE
colorizeElement breaks on element with existing class

### ISSUE THREAD

**Issue by jjyyxx** [Microsoft/monaco-editor#752] opened 2018-03-13 06:26 UTC
monaco-editor version: 0.10.1
Browser: Chrome 65
OS: Windows 10
Steps or JS usage snippet reproducing the issue:

When I use `monaco.editor.colorizeElement` on an element with existing classnames, the Monaco colorizer simply appended its own classes and turned the previous classname `language-tm` to be 
`language-tmmonaco-editor tm` which led to unexpected result. Adding a space between `language-tm`  and `monaco-editor` solved the problem immediately. 

It seems that this issue related to the code in 
colorizer.ts L41 `domNode.className += 'monaco-editor ' + theme;`

Should this piece of code be improved or alternatively, do I misuse the `colorizeElement` method?

**Comment by alexandrudima** [comment] 2018-03-13 16:57
Duplicate of #696

**Closed by alexandrudima** 2018-03-13 16:57 UTC
