### ISSUE TITLE
"Uncaught Error: Cannot read property 'signatures' of undefined" in ParameterHintsModel

### ISSUE THREAD

**Issue by BennyHinrichs** [microsoft/monaco-editor#1582] opened 2019-09-12 18:04 UTC
Monaco@0.18.0
Chrome@76.0
Ubuntu@18.04.3

I have a function
```javascript
const add = (a: number, b: number): number => a + b;
```
When I type `add(` or hit <kbd>Ctrl</kbd>+<kbd>Space</kbd> inside `add()`, I would expect to see `(a: number, b: number): number` pop up. However, it fails inside `ParameterHintsModel.prototype.doTrigger` on the line 
```javascript
if (!result || !result.value.signatures || result.value.signatures.length === 0) {
```
When I pause it there, it shows that `result` exists and `result.signatures` exists (with the completion item I need!), but there is no `result.value`. Is this from the 0.18.0 update or am I missing something?

**Comment by alexandrudima** [comment] 2019-09-18 14:31
Duplicate of https://github.com/microsoft/monaco-editor/issues/1576

**Closed by alexandrudima** 2019-09-18 14:31 UTC
Labels: bug, important
