### ISSUE TITLE
Read Only Tooltip displays outside the container in first row

### ISSUE THREAD

**Issue by Oscarsgc** [microsoft/monaco-editor#1542] opened 2019-08-09 13:04 UTC
**monaco-editor version:** 0.15.6
**Browser:Chrome, Firefox, Safari**
**OS: Mac OS Mojave, Windows 10, Ubuntu** 

**Steps or JS usage snippet reproducing the issue:**
These are the steps to reproduce the issue:
- Configure the `read-only` option as true in the editor
- Go to the first or second row and try to write something, the editor doesn't allows you to do this 'cause it's in read only but a tooltip with this info should appear.
- The tooltip that displays " Cannot edit in read-only editor" doesn't appears or just a single part of it appears there.

Attached you'll find a screenshot.
<img width="547" alt="Screen Shot 2019-08-09 at 8 58 38 AM" src="https://user-images.githubusercontent.com/4324370/62780682-40f8b000-ba84-11e9-80ac-235b2b8c103d.png">

Here's a small video with the same behavior in the playgrounds (https://microsoft.github.io/monaco-editor/playground.html):
[MonacoTest.mov.zip](https://github.com/microsoft/monaco-editor/files/3486452/MonacoTest.mov.zip)

The expected behavior may be to display this tooltip on the bottom of the line instead of the top if we're in the first rows of the editor.

**Comment by andreymarchenko** [comment] 2019-08-15 15:34
It's actual problem

**Comment by alexdima** [comment] 2019-12-11 15:51
Duplicate of #1140

**Closed by alexdima** 2019-12-11 15:51 UTC
