### ISSUE TITLE
 [Screen Reader- Hubs - Resources Explorer] Screen Reader is not reading the Line number information on the Resources Explorer blade

### ISSUE THREAD

**Issue by samiyasultan** [Microsoft/monaco-editor#946] opened 2018-07-06 11:50 UTC
User Experience:
User who depends upon screen reader will not be able to interact with application efficiently if screen reader is not providing the line number information.

Pre-requisite : 
Narrator should be turned on.

Repro steps:
1-Navigate to url:-https://ms.portal.azure.com/
2-Navigate to Left sidebar and select All services option, Search for service 'Resource Explorer' and select it.
3-Now navigate to the code area on the Resource explore blade and verify if screen reader is providing the line number information or not 

Actual Result: Screen Reader is not reading the Line number information on the Resources Explorer blade.
 
Expected result: Screen Reader should read the Line number information on the Resources Explorer blade.

Note: Same issue exit with Chrome + Jaws

MAS Reference:
MAS 1.3.1 - Info and Relationships (40)

Test Environment:

Version : RS4 1803
OS Build: 17134.48
Browser : Edge

Attachment:
![mas1 3 1-screen reader not reading the line number information](https://user-images.githubusercontent.com/40890184/42377432-e92f1aee-8140-11e8-8051-64b519604149.png)

**Comment by alexandrudima** [comment] 2018-08-06 14:13
Duplicate of #410

**Closed by alexandrudima** 2018-08-06 14:13 UTC
