### ISSUE TITLE
Native "select all" shortcut (Ctrl + A) does not work in Editor searchbar input in Firefox

### ISSUE THREAD

**Issue by grindpride** [microsoft/monaco-editor#2238] opened 2020-12-01 15:02 UTC
1. Open link by Firefox https://microsoft.github.io/monaco-editor/playground.html
2. Focus editor
3. Press Ctrl+F to open searchbar in editor window
4. Input some text
5. Press Ctrl+A to select all text in input
![image](https://user-images.githubusercontent.com/25076736/100759678-f3831d80-3401-11eb-8a7e-c34693d52e08.png)

You can select all text using double click only.

**monaco-editor version:** 0.21.2
**Browser:** Firefox 83.0 (64-bit)
**OS:** Windows

**Comment by alexdima** [comment] 2020-12-29 08:07
I can reproduce on 0.21, but I cannot reproduce on `master`, so I think this was fixed in the meantime.

**Closed by alexdima** 2020-12-29 08:07 UTC
Labels: bug, firefox

**Comment by grindpride** [comment] 2021-01-12 16:55
@alexdima What version it would be?

**Comment by alexdima** [comment] 2021-01-21 15:38
`0.22.x` would have a fix for this, but it is not yet released.
