### ISSUE TITLE
Ctrl + V can't paste clipboard data to the editor.

### ISSUE THREAD

**Issue by Lushenggang** [Microsoft/monaco-editor#1046] opened 2018-09-03 08:28 UTC
monaco-editor version: 0.14.3
Browser:  Chrome 69, FireFox
OS:  Windows 10
Steps or JS usage snippet reproducing the issue:

I can't paste the clipboard data to the editor on my web page by pressing Ctrl + V, but it works on the doc page: https://microsoft.github.io/monaco-editor/.

**Comment by alexandrudima** [comment] 2018-09-06 11:18
@Lushenggang Are you using webpack? Are you ending up packaging the file `vs/editor/contrib/clipboard/clipboard.js` ?

**Comment by Lushenggang** [comment] 2018-09-10 09:56
@alexandrudima Yeah, I import the editor using ESM with webpack 4.0.and I  should I import 'vs/editor/contrib/clipboard/clipboard.js'

**Comment by Lushenggang** [comment] 2018-09-10 09:59
@alexandrudima Yeah, I import the editor using ESM with webpack 4.0. Should I import 'monaco-editor/esm/vs/editor/contrib/clipboard/clipboard.js' manually?

**Comment by alexandrudima** [comment] 2018-09-13 09:54
I cannot reproduce. When I run the test at https://github.com/Microsoft/monaco-editor-webpack-plugin (i.e. `npm run test` and then open in a browser the `test/dist` folder) the `clipboard.js` file gets packaged for me and I can use ctrl+c and ctrl+v correctly.

The `clipboard.js` file is inside the `monaco-editor` npm module. Can you please confirm your webpack configuration ends up packaging this file? You can look for it in developer tools with ctrl+p

![image](https://user-images.githubusercontent.com/5047891/45481400-b8767000-b74b-11e8-9508-d25c21f57575.png)

**Comment by Lushenggang** [comment] 2018-09-14 08:59
@alexandrudima Maybe I find the reason, but I don't know how to resolve this problem. 
I  looked over the file '/editor/contrib/clipboard/clipboard.js' and found that the paste command will be register or not according to the value of _supportsPaste_ . The problem is that _supportsPaste_ in my app is _true_ but it is _false_ in the sample. That is, in the sample ctrl + v will execute the default command of the browser. But in my app it will call document.execCommand('paste'), and it is not allowed.
And the reason results in this problem is the difference of _process.platform_ in different enviroment.
In my app the value of _process.platform_ is 'browser' but it is not 'undefined' in the sample, why?

![image](https://user-images.githubusercontent.com/33415699/45539564-b17b5a80-b83c-11e8-8939-20b77fc10d4c.png)
![image](https://user-images.githubusercontent.com/33415699/45540604-73cc0100-b83f-11e8-9fda-6b5fedf6aa38.png)
![image](https://user-images.githubusercontent.com/33415699/45540652-93632980-b83f-11e8-915d-bebdb66d4b08.png)

**Comment by alexandrudima** [comment] 2018-09-14 15:09
Ok, that is definitely wrong. 

Do you know why some piece of code in your app (or in your bundler) is defining `process` (which is a nodejs/electron concept)?

**Comment by rebornix** [comment] 2018-09-28 19:40
This is a duplicate of https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/17#issuecomment-408303369. Webpack sets `process` i

**Closed** 2018-09-28 19:40 UTC
Labels: duplicate
