### ISSUE TITLE
Suggestion icons change when being selected

### ISSUE THREAD

**Issue by mofux** [Microsoft/monaco-editor#553] opened 2017-08-18 15:50 UTC
## Environment
monaco-editor version: 0.10.0 and 0.9.0
Browser: Chrome / Electron
OS: MacOS Sierra
Steps or JS usage snippet reproducing the issue:

## What's wrong?
When moving through the suggestion list using the arrow keys, you can notice that the icons are changing. I am unable to reproduce this bug in vscode. This might have to do with the way the list renderer is reusing DOM elements, not sure...

![kapture 2017-08-18 at 17 29 32](https://user-images.githubusercontent.com/2785983/29465992-82e953c4-843b-11e7-9d3c-47e116203790.gif)

**Comment by alexandrudima** [comment] 2017-11-07 16:18
I can repro also on FF.

**Comment by alexandrudima** [comment] 2018-02-28 10:33
I can repro on Chrome too.

**Comment by joaomoreno** [comment] 2018-02-28 10:59
This seems to happen only in TypeScript. cc @mjbvz

**Comment by joaomoreno** [comment] 2018-03-01 07:52
It used to be that a focused element would render its documentation underneath itself, thus increasing its own height. A splice was necessary then. That feature seems long gone, so the splice is unnecessary. But that is not the bug.

Do the following changes:

![image](https://user-images.githubusercontent.com/22350/36832911-d928e606-1d2d-11e8-8cc3-fec2703abcb4.png)

You'll notice elements changing their type when asked the `resolve` method:

![image](https://user-images.githubusercontent.com/22350/36832929-ebe1cbdc-1d2d-11e8-8e23-fb8c156a288b.png)

**Comment by ramya-rao-a** [comment] 2018-03-02 01:37
The resolved item has a different type than the type on the item first returned by the provider. I believe the issue is with the provider itself. 
@mjbvz What version of typescript is used in Monaco? Maybe the reason we dont see this in VS Code is that we use different typescript version.

We should remove the obsolete splices regardless

**Comment by ramya-rao-a** [comment] 2018-03-06 17:14
https://github.com/Microsoft/vscode/pull/44951 fixes the visual issue here.
The underlying issue of typescript changing the type of suggestions remains the same

**Comment by mjbvz** [comment] 2018-03-06 23:20
Opened https://github.com/Microsoft/TypeScript/issues/22366 for this

**Comment by joaomoreno** [comment] 2018-03-07 08:49
Alright, then let's close this one.

**Closed by joaomoreno** 2018-03-07 08:49 UTC
Labels: bug, monaco-typescript
