### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JunMingLu** [microsoft/monaco-editor#3479] opened 2022-12-30 08:07 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
{"a":"mazXbvN菱EzFDnkicFuzcapPsidlqubQvqtGTfDmujKqGrWZCsuMeUMw菱uwWKjXiOAIFBFrckNmheecvnDYKIZcZUZJSIyPJfERNRuYaELVxkmgWMjQZrVQEEpxwpndyNTvMKdZZQYnRxWtXmL菱EhGSlikemiiBuPAyUbChvPbHyOxYNocptZJOUIwGULXCSWFTHvGlLMZBABcNsXGnJynYfGoeF菱vDftRjfOq菱ZgXaFMmhMDyOOytWHYIwtMQoWkGUcwMBjMmQutTgTAHgjQqScRbQGBeuVV菱xl菱ZUJxDmBY菱SIRIYSOCuyHUptsAaixVSsaOgaEbfBeiRHNDogwdSgliVsyqGXrZltjTEHFWLFHRwgHChGmsaHPqilLBEHshOoKXOErjJloinnXmaNjPwCdbznPbNOopDeqXfiXJoGoqOLkwPGWbomCbfrjOodBkPkZFWiOPAnMIKLwaXihcNFQsmykIIAqdpgMPJgGZFDRl菱TrfcrmxthJNdOPFGveNQKDaWjkTalXBGMtofNRIMCKsqbeNmDgAAouxKMjlwGfyinuKJzULKxzWkOEThzAFTlBsaAnaTqXjzdjI菱wHf菱gqpWZKavodwmgpsZhHPNJLxTSLxZHEucnRZzkXviTDVmafVpExCpqcVDLLPoweowDzBLB菱uGlIUDazMNuTrIwSKnQEABUKQtJLqwbERSHkRqsePdf菱LeEmMKqIUOpbdObStmXKqdnFgHOqxWEmgxYWJToKGwKjzKdxlLXsXDKTtZbFexVdndq菱u菱oQITKZFGDKpilStZYjTDnlKqKPUipYCdZInWkswWnDCePTUfyZZXLkxgDbUcoeWaDZOV菱MuThwNteHEJqlUTfkSmqHCOtJyXOSqWsPqBUyJSskQzzMxjCFPcDZrCywcoZcCxPNX菱OVDKFJlFUMhBuHbZyczSEpAaeFrRRgSNPjGYl菱tKIPwyPYAyvFcnayQaKbab菱CxeYi菱fmgzFAtlcDyftisS菱VwMJXeMTHRORBzlRHltBEQ菱tSRIkkHioJjQkELdREqW菱cYhsbtYESqhBDIwlWZvbVEwqmMdrlkzrnTzGuPZDdWENzvQCgklJhMWNpMhrQkJjhdMaUUse菱cEzdvUZJkdIBrSPGHljDNVcDXZFNFBcwVxwXDLlsbNynLVycTOxfkPhYPp菱FkDDiwehYdZg菱ADZUHvghqAjAZhMSRrnwD菱ZUnsHoCiZVfpDmEpID菱fNctGWWgCUkfOBAKzCAhOPfeE菱tdbwzeWvnkctDJzjzpAIxBuCnAKmDAHJNZZ菱MAgcxFxyPffHMdAaUYkXrjrQJbYbKHHXZHwerNlWwVLzdtEdAisZVL菱ARdWhjchyyBnRJeMJzGRZfqjoMAitAdZNDgNSrcnMukMHSaAlFezVGrrXEdWduMmqAlTNXilylGBfHOWYzpWsSJmSMJXvTKeIotKiUdzrGJVxxGWaTaHtupqYILrUmCodXmqPxZyJL菱kmOIOxbfyWKjDjaWWsyleWvvZiiWyu菱GaIdGjzrCvnzVxapoIbDpifrnNvlCikTTcqiWIpwcKptYTWsfbcUZwvvhtCjneSSCquonhXrZApkLNptWUyAwVFOHPjBqxJufnwkO菱GBGEIjIcLVkERoyUBkpSBdKHYaSvBvsKcJbMnMcxNvpoMNbiAEgevuhbmVtrJduOOeeWAsfIduouzFNasFmVgBDpCUYJ菱JseqYnqNPaaFVvlQWtcUiVhjFDkPCpFZdWgSWSxENrrtlKKuOWOAECfYbFNsusSxIeJhPsKGNeOiolRJFwFQVymcOOUmiedSLzxzbGUBkfgQRpTOgaZwmbViNmFGrqbXxoMipjWfUFztzylplGsYASENArwMdjzRC菱YQHcRRCzDWntKeXAyvrNSDfaJomMzXYuVRopXixyFvDCAAodvPKKyvhCEslghEKjUfPIlqqU菱ZkhascYbIDbJHmHEUlZtXlGNDRoIXfectQOUXxmBQlyCAnCCZRtDFgX菱bDPGFeoIwv菱rKESshXwfgHoIuuuZmOqWCnPhGRYCJUoLLpZXGGPfcKnzIHjUEybOoryYakYAn菱xEbFjOzlKjnFMobOBQjdKWFhPySWRwLTdcKGvoZPcaBNBoGupB菱GzOYYKrattqaYXBGijYntTvmZWIUyWfptOpufDhxdsMzygcSAOeaNpuGJxLFAfyKwEDOpBu菱D菱WPLKkZPljSRzcsMwNsLvRtUMwCXdirErkXiUjdOkIfjRtcXvMaBzVnDiNKADoFnyvioFuTMfCKuFUPSVdxGyaDGfPJsvagQSBhXon菱crgOKQfknrXBFCsqmJTvrzvEPmHqFtsBPJHTasFreNtgtipoviabpSGTKWAtQGYmmm菱tRtCxKnrtHDPpoWJrWoqMHRWFeVOrIiHKgYhNe菱LFFHkqFTYdhftzPNnFYGTx菱gTWYJSJOVihHOVuXCGdmGtLuhYJteVpaFLopwtLTbBVSSbOhhdWhFITJWihwjAdnoXaVpiRcoeT菱fCoLfTJNFTNqRtFQOaUWSeGPDyytHiFKGONPubJrJLqJFdVVxmTHoaSNYfgbXUzrpXGsTJAiQXkAJJFypDfssMUILvRXAMEgsWONwzsJMUgzLGVNmrFXoWDnqLCvcbvJTa菱tBRTVgNGsDzudkt菱aVyEbk菱If菱sNIpuKbYgzzSafSfpZEMsVzJnNxHSPSMLNrlMRlLfyJezeVSTsyHndaPHpsKHmwedVSGcTOcB菱bNyaekRqBPvrIhIQniaQmjwLrqcHxVCzZxVbivHTNhhllJAinuHhlPXb菱ONoocqxbCYLMixIsRctCdOeKGjMPeBejlkIwFjUsfrxKajDLVoeXuFLpGKVKRVlqnRIU菱vNTMAREwaXQcbQEagujABCcpMgHD菱Gm菱YVxhkAMLptCoQPeLUXPAttqloJXfGdTIXx菱菱wPHSJgSgwbLknjcHCkvmfPcAOqOyBmaZioSHTzNEiswIpmgLHVWBUsFznhdJMUwvXKrfRowhEeKneqPQHNfmGdjFHCcXuFQnWKkhXfdWkcn菱菱eGZglrdupgTKnmLVO菱HlGfi菱GOppBRUSMdoxWiydahiptHEEqvejyle菱FqhIHyVOrjNwIYKCDqfJfTqUPrxutwOGsAxHsZjAdMznStAVnSZttTLftzYAcvfqeOpa菱VEaNNqWIBmAOq菱PoR菱JBU菱MaIxuF菱raeedCjJYfShBwSIbWFyrMHyowcFTBtgCdrWfiwAKPpHczTKwbUokd菱RnrCcuyzuxfIOXfAmLL菱XUJtlUacNoPKEAUpcEZRRFajOjPLPHGbMiDVUpRyJNUTXkvMoMQjsaFKqpPuvSbyaKxCNrBRQaQSQXDfAqopMBVOwMIgDQSltd菱gxtvdagUoRHvYSPdDmNzphiAkszm菱iipVLPqXToLqtpyTPPFjhKHJq菱vjmuLoAUwQsCVqAQvpKkWaqOTTDceX菱jHak菱bMsXGLjLWKacEREDnd菱U菱yKHOHIiGtdDLVlbVsmbqfxuADdPbQAxHysjHqtfCdQkTWMccOOeBAwrHaSFHsDqSHDoaXNIfoEgWEDWtfKRqYGiDdmWplnCMMQbYXjFGhtRxKSjuedgXyvfbPpSxKNVEbuFjVUSdkvSuVwAVqYWBiCqLpwG菱ZxqKxhRDBuEPHjaJOlvcE菱QGhmCeUNHHkgVQPHWvVstiUVpFPiENeIVOYWPsjc菱cxivcBZYtVzIJBeKEgKmPPiRWiJiMxOITOEAZvQQGZzamVBCrSEROSXthFEURrutG菱FtPDVODqAzRcmqnuAEZSdzndfQRpzHedfsg菱mvjaSPsbemIsDKwijCWgNYrNnPCjtdqBKspmNEDVHekIaQlkq菱AlJamFBcSHMwYMNoxjsannKCQFnejxqsIRUZpoPnJRWujsSenjdewSjzXaHrhpZqFWfYoKjEisgQNiwUXIhXiDJKyEwFNzXbdZNDpgQoKzYijsITnLfDfeRSQgpEqOvwjGIchvbngQoeoFgqyZvqkVGdiFoRhgNyuNiqgwCmJJMoEVLADDrAIiKugRcxvJXXVWoyLbtevUZTwARkWKPUQlPkNgnqcifOrSXllzDkXchYgPNcbazFifNVjEllaePJDjAfqBpfKemMAFvvccyiWrNjIuKpMDYMDcbiLLdcFgdcuWNbliOCLsxJdwRJRUPzyaSoRnKOhjNFJt菱LKciaRkRLHRmEUDNCtczDPquGgsRTCmnBuTgdRIfmRdnXMUkHuTztwpIgASUVOTb菱KfkySNQjfQBacJLWZGbYRFZxYQNMxohMReEJXCgxnXBkrsugwpihWkD菱uJkDFsrsUYRRofSwCUCpEFbqjyfKgRNCSKIXxOdkgAKqnSxOSJjJrAebEQdJZVhHmLpnWrObFhvDqWkmOPMyAsFLtdGzYflsFPhRyJGcnwaFPXYAWceQqBTBFhetfGCjAFRDjAfEGlifokMaWG菱ZIUYYeutFxGggwRFhYaY菱ifawwYDhRXdTxXrFvWDtiMgpUbBsPpvMFqHesixtmiEKoZEYqjAkpbqOYWYiKlW菱uvHpgPGfsMKNbkynwGdOBZGNuXzWvnpfTMvFRQjFxjl菱lX菱TxtMtPMslVMmBljtJvZd菱rPCQohTdh菱SnxjWSriKeCrKKNVjefozfJjawMbRdmxixolTZtNGhoRZIZRwbeqOyaWVTKQmXRKyqKvWQrYF菱dotaIpbZyzTYXHqDMKLCQuVkSnYwpUZfPNSwYlpGfFqNYaWIpUFXlMZouHDgOJFvTKdtuJJGsKJEvEbtpGVDZiiSlpllEZLZfhXphmQLHPQWkahyGaboBYHnYXZkimmHEwyTDqMxNRcHjTbBkKbrogpeFeFhQQAyWqyza菱qIYMehhOxEHDV菱NgdASFroRTOPELSFnNsMVGyAtcFHEMEyteamaEdM菱XhfgfkHWVCoplmqGDhsTtZzhwNLQoSWxBOXUHsbFFTLZlGJWMHyOCCKZ菱suZNitX菱YCfCyEkLYQPRtPCyUeaLCXtkalOISAzfwyoxMcAnXuHTfoWH菱Zc菱lcPMpLAoLYGHODavXPCS菱QLMTrdEUuXTOYY菱BvkoMNFPRtLBop菱gvcqdqXcicmbPWobONdqNfJnqVvOIbEprbdXUUduFXCzuHqKrNysq菱Gdu菱tbFiUwxl菱hwhEJNVeOWcKQXMlJdIPWyuADjxfxWWwwTANGXZmjuTqJoRmiqIcovw菱RjlzANitKxiedYVoOjFZKGokqnHnnWoZkOxpNYZRgVTGXUAwANqv菱SpXKGzUiShFVSToLLiiHBztVQuSestqqDbnGbKRDK菱QCFQEmPstHwWYFwmvaitWGYwnWOwZWrjSOebsVyeqBbXsfeGdqebggtKaxaso菱pdlTCEQResXTAY菱ZJYOaIBJg菱vRyLsPjPvptji菱qUJJZPfaDeEXBnfiCqCtiwTzFXhymiP菱KDUdljtzRipeJANKzcujzLENjNEWbvENKuWqfWPWlQrqWMlolKUyycEkbjCeQXvbIGfBHliRPOptvcGjyCeUnIFQdNHNCw菱EgmnofvHxlAzofeSWtGPUI菱YvVrLWfJL菱LNWGyOZZqMpsiDSiaGrbaTDYAAa菱ykgyNehzApAGVhpJRTZmOhxWqMtgOvIpzSAnXDQIlWizJhabwqtrccs菱JAheEcuNCmdhPAUyqMMBRLsaQbjeMHzJDgLWgAfUceTfmzKuPkbUNzpNstDCkKOtfUUbSozOlnequPSLFlPhHYNHMicHrqXCSsRquvQcpeYbcie菱FQqaGgWuTyFKHGRsMEJiwEDuTPdwpen菱AgEJDBtwGmqxvSOLHIXuYVZITuUqcCZYlqyYCkMHACJldTlWDyg菱DiSETMdkonLJuhqr菱bvHMHNQRRNMaDgBOVPgwyFrXqZRAfLLLhtJGCaHIryPTEVeVems菱kOahvGkMSqODWlcXDuFgQFtpUSrapCTZcaBcGiQZHgTuEhzoWVGWNmglwQGAIBBIAEsrrbXlRiUwA菱OECfre菱NjFQhMrfxIQbvnexiroTRnVJzWxGdyrqzFhoRcMrzaqDjuwdXVnjqZDxyvETsrwyudAjQAerlseAIDRHILHuTEsiqNfmpEEzFWqIVWRGOImbHUmgZl菱gCHrjEaKCupNRs菱SoQtHRQcYcLVKajWGGWHogiJrznKHfDPThxzaelGzVjCoqDPBviaJFXqRpGNcdkzyGVLZGCJUyoEODiuaUhi菱VnDFhsEEaPejAoOZiwwfMBVt菱DzqAsBYRqnvbymCvDvLSERrwbTcIqCjzdfngTwoUSfNCvItUyfl菱DyEjhhxZpIYbDQNigjTRw菱BZxymvPrqNjTwuREviRRTTsi菱DUgwDUfXvlDbXB菱EezCREFzlWxntQlQiOmr菱zEgquWXjAGvpsRysmjrEpYjvvCOdUHEVEjLbasfQbxjRUNYAyVjNVxtimoIwOIcLxVmmpxtpTzECMRZuTRjfihPrbSgbQNMFZYgIBKvItYltlKIyJIBmRoffwlJrEnbmbTmwgZgOOutrKT菱aAUcfeea菱FzcUKCxUBjlvndNFvbgqpAIqGGJauGsSkNWtAfzRGkceEXckdNBrwAJIyqsihekHAboBTnKwGMTw菱dWfJMnTbruEAvWWYTdJ菱nqZDtdsMRAfODm菱FCDOsirSjWwRWcEYGUXmKnyMvunjUPDEZCvsmsxvhNOGezlJSAXZpKQRMvVnrg菱HxevbSOsROygDfRukrldcHsyFDrCUpNQBVUbQkewzRzILDArUtsGuilHFJzBKUgaTnEQMvddgACihoualaRARDRhKdnTHaZffTwKUFCogxpCFLvrOGxYE菱WngPUBLSpggWNjXZrDcb菱ZCTZftqRTWnAOBXpqKnqvrfnAAyGWVHF菱pUhJhGMKFDhbwCzKtayhHkFvwIiAEAmJArSSkwETukQStLeLzFxk菱XEryAoufaMapOIKzHDYNpbVJYukCoonPNJZhkdIYCSZAUJJNcBfnphJVYlUMxAIBOiVD菱OjlULQPhUXPsfLPorDWiAnpHkKsXzDlsykGRFrcYswTgJvkdKcOltpmoFHILOkXdyAPqYmnsa菱KJOzScBrUQIDLyUsLCHgJrmhpzWkOcCYPinSIXAjRCxgHsESsHenyQIFLwKYfsOXsRIySFvGQRlgcmoYJGhPdRSCpGlEIFBVkJGLgAhSg菱UWXrwCdMEjmmCsvKH菱muestkViqFOhdauxsyRNayugVUdGLGgKbQIXfHTLXGwxfSppkCDnUQUKwfQuyxIKEY菱QQElxOSRcnhGdNoxYdymzCKpXBDmoGWqKTxYMnpfHdmtIFGgszIzOiAWiiITvLSUxeqgJkY菱jmFYzpAhqaIfBFedZiKYwmKqDzNQFupyhvxTgLY菱hNACspSgC菱vXHYQmQ菱YomeDUBlYDoaQoTEHdULkiwXFmpGVN菱LBetVarcQtfjvkxMFsYllXXUdLKdYFmFJSOLvzYiKmXSSYIVRKfaoOKxSoRUTrNAfwTKoOuVtVnuyuqSQegGLILGdnStatzyuC菱nljlbZmeoVBekPXkpxIGlHqOouijXOTaYRHwKkzODOXwREBFaNwAWfbiUdfDqIFOlYYZR菱DclTcjiZZfmdAaGyQfEkHkOXRvXpyiWKKPaKyUlcSJFfYx菱KglEXFQedZHnmjcvpJXefREhcJFbEsBbCZJPEVMUxwvZcBp菱ohgBjnRJNNPpiVxFpnFTmWZaSuxVTiuA菱TIFWOdi菱RTvIZnyAhRQYOTCLXisDIN菱GvGxUfgHMnuuWQNXomxTEFVojf菱WcSomIqTjPAwISlzOdHhrLioFzvXWctwXKsazkpQkcjfAqwTPBlAoKAIZDokpUzhtfPVlhUFPYwMjhhwNKaEdMsWAbbxvAcaXzOnmUcqXRBazmS菱BMJSPaXpttwRWqEnOsJHtGNK菱XxuMlHNNWuEqSGvkXvJhhvLQbDvjRGpKVLfsxXWZGJSprmdylzFcDjOqIeDiRxZdLxPoHbdLbjqDoFvvgWLIoqXILIUaTnfCVQcBsDVdivFgTLJmNyqjrbTBIWome菱BnWz菱菱RedHIpjUbCYaIdJPodRJLTZRybmeLXeFII菱RwDZlDFPdkkdLFmWXhemkiOtyLPEJcrpFfVOahiyyKMmrVUVkQENagDkYfRxOyfqCoiiHiskvDWTVuOgEUSpqKlLlbimoTfyCotD菱fsbtftPEiUXgunkmtyBxeNrOHAbILgBuEqNYigHsPbLqpmcMsdjEbOlonMIVzzQKYnXnAjgCjXNEmyIN菱ozpUluLaudUTnpjYuXATPcoyjzWmVBdJOzqmBiJJnnkIelPydUQkjjKNXPYPdkEkatidmzYJHscJeLlfWCiWYYBgBJHfQqdPJEBLHi菱DSclfQUaRdrelChulEiBZrU菱xfcjZezDsXoOAXIetibcEumzCjWtaObduHUhtnYlIVMcqsIsCuXjBuHNUkfPRsz菱OzexucnmgKehdgPmxUUqNVaQRxbzDHvCgNBvqJmbAFoMuFcIQUiHWPTAIgOCPmEbXkxrmh菱qcXtazUveloFFCJIdjXuNZymRJKNPptyKeWtBrWUPxbsgHWBWEmCyOLJZnBxmy菱EvjaYvcpzGccobOPtCJJVTFknkOWFrERj菱XgzwgmrVWawvQWkbLordGbcqbyFEFA菱QvVhDWGusjlbLruHjyddIINPZvYnQURljJNkzMljdKFrdSQzvSfysiNjVJXfhJBlnOYRbBEuaYiaGRfgEOZOAfCgoTqQEXptTgXhnRieZXIznm菱bDabaiQafzkqHZefgIKiocwhFiXznTQuTyBNJCcLpeqRedKZQYdAMLHmplRIGBRJEGOOSSRSjgJrUhLGgInsTursbecdKDzdEudtpCJzDpKGrcWJckIkHfyrvGwbkwnsfpQXkohzCLMEyVXBSqvywEHOXVYWuvWadgSgf菱gsPWcYfWNIvINmwetGYQksCXVTZmhxsAKIlIEJvxsq菱jwmJrPnkrXiLkQFrwkpRWlcdnaVCENGxbvgiqQsNkDachmpClon菱oIzvNKulvlWtZeo菱PklkAErikCMWHwNiElUKttvYhXYjZEEtxoLQrwOKsPJfWSoxqGNDggybUKnYyzQImbL菱lFJnWEyzakfqfzmPeNxyflhkGELEQZRRiUBYQeiFfWiDgKpOIwAEWHVcuxZewNFGGMQxvVyAhDKFvYYSgFAqYEDWLUwyugZMIzhWjSDzjdmamHUpxWdRkouOBFDcIVVljqNsurDIhxcdquLTqYMDigEKDPzfPXVOtvYhNdROsllPyTInPvtt菱ScMWbKCsIkeZuBSFMCdCgOBLUSDIeQtoplJxoKJuQMZWLaan菱siaHBTdDvmJjVmckPTnYRfVdXExcYDQfuhlkUtGfnhpZNVm菱poUjPYVOJYlQizswKdouAxJQaffjJJmaM菱QzdKmYXEALDHDhYNouJxgEmcF菱lXdgULcNNvdNXRcqURaeqEeTCLFJLbFUSrLGqNsvMPMeuEiaYXTlxxWUKOeciWXVHhlGrdFtNBwCILhktASqQeCPtnmxlxauefRTKDrXvGrmkQIgwUWZE菱zwBAAuyFoWYUGvIuCzLkEbZXsWXVDqzRWjSstGWvCRsoZUAETAItqohoBQGthUzvOilshASDgdKOh菱pYApXDmYKnaLVkytqTeTuTRJvdtAKUHlbMoqbCbQXGanOucVgdMqnBxtHJrMhC菱ZlwtqdX菱KzIYfddmfrrQEBKSqpXvAlBcWEPjjVzboYyfrLESkxApIEsNtIBzANTohquUORzPqPhRdipPWtttgSGQavJgleBMlx菱CDBqBqPbJljEjbPsA菱OQjsBqJrukxDODkogRoGnXKAC菱菱Z菱QjRIFxyFKcGOtyKgBBjySDMhctfIisArZDJRgUZFqVjyZcHZnUUfpZvFmYAmaKjrQUMOUSLoiyQzsjuKrPzaHypftiyVKdzxHYpdmo菱BcQb菱jbLialFPo菱eeYWQgmuMdyTPXLPDqJMwNzV"}
```

### Reproduction Steps

when paste the above json string in the editor, the content in the end will display overlap

### Actual (Problematic) Behavior

json string is too long , content display overlap

![image](https://user-images.githubusercontent.com/35445041/210048366-4686137f-2f3e-4fa2-b100-26bef588f720.png)

### Expected Behavior

the content is expect to be normal as shorter json string , like below
![image](https://user-images.githubusercontent.com/35445041/210048479-65a8c29b-040f-4374-ad1b-7b55d708ab9b.png)

**Comment by hediet** [comment] 2023-01-03 14:52
I cannot reproduce. Which browser do you use?

![image](https://user-images.githubusercontent.com/2931520/210381422-0ddb5e14-a86a-45d9-a548-52a6b6bf7e40.png)

**Comment by JunMingLu** [comment] 2023-01-04 09:45
Google Chrome version is 108.0.5359.124  and the operating system is macos 13.1 (22C65)

**Comment by hediet** [comment] 2023-03-13 13:28
Closing as we cannot reproduce.

**Closed by hediet** 2023-03-13 13:28 UTC
Labels: bug, editor-core, mac
