### ISSUE TITLE
Missing suggestions for JS object

### ISSUE THREAD

**Issue by sicak333** [microsoft/monaco-editor#2573] opened 2021-07-14 07:59 UTC
monaco-editor version: 0.24.0
Browser: chrome
OS: win10

**Playground code that reproduces the issue:**

''. Ctrl+Space to show suggestions -> There are suggestions (charAt, concat...).

{}. Ctrl+Space to show suggestions -> No suggestions (hasOwnProperty, toString...) for JS object.

**Comment by Pranomvignesh** [comment] 2021-07-14 08:07
@sicak333 This issue has been already addressed in https://github.com/microsoft/monaco-editor/issues/1944 and https://github.com/microsoft/TypeScript/issues/42086

This issue is marked as `Working as Indented` by Typescript team

**Comment by hediet** [comment] 2021-07-14 08:16
@Pranomvignesh thanks for pointing out the duplicate!

Closing this as duplicate of #1944.

**Closed by hediet** 2021-07-14 08:16 UTC
