### ISSUE TITLE
[Bug] Don't work json schema with model creation

### ISSUE THREAD

**Issue by ariran5** [microsoft/monaco-editor#4146] opened 2023-08-29 20:43 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0#example-extending-language-services-configure-json-defaults

### Monaco Editor Playground Code

```typescript
// Configures two JSON schemas, with references.

var jsonCode = ["{", '    "p1": "v3",', '    "p2": false', "}"].join("\n");
var modelUri = monaco.Uri.parse("a://b/foo.json"); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, "json", modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	validate: true,
	schemas: [
		{
			uri: "http://myserver/foo-schema.json", // id of the first schema
			fileMatch: [modelUri.toString()], // associate with our model
			schema: {
				type: "object",
				properties: {
					p1: {
						enum: ["v1", "v2"],
					},
					p2: {
						$ref: "http://myserver/bar-schema.json", // reference the second schema
					},
				},
			},
		},
		{
			uri: "http://myserver/bar-schema.json", // id of the second schema
			schema: {
				type: "object",
				properties: {
					q1: {
						enum: ["x1", "x2"],
					},
				},
			},
		},
	],
});

monaco.editor.create(document.getElementById("container"), {
	model: model,
});
```

### Reproduction Steps

try type json, Monaco editor autocomplete doesn't work

### Actual (Problematic) Behavior

I expect json autocomplete. Autocomplete and syntax highlight not work.

If I *use creation without model - all is fine*, but, I can't use URI for editors windows 

for example 
```js
var jsonCode = ["{", '    "p1": "v3",', '    "p2": false', "}"].join("\n");

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	validate: true,
	schemas: [
		{
			uri: "http://myserver/foo-schema.json", // id of the first schema
			fileMatch: ["*"], // associate with our model
			schema: {
				type: "object",
				properties: {
					p1: {
						enum: ["v1", "v2"],
					},
					p2: {
						$ref: "http://myserver/bar-schema.json", // reference the second schema
					},
				},
			},
		},
		{
			uri: "http://myserver/bar-schema.json", // id of the second schema
			schema: {
				type: "object",
				properties: {
					q1: {
						enum: ["x1", "x2"],
					},
				},
			},
		},
	],
});

monaco.editor.create(document.getElementById("container"), {
	language: 'json',
	value: '{\n\t\n}',
});

```

### Expected Behavior

I expect syntax highlight and json autocomplete when I create editor with model

### Additional Context

Bug in 0.41 version and higher. Works good in 0.40. Critical.

**Comment by Maximuschka** [comment] 2023-09-07 12:50
I can confirm the same behavior:

Up to v0.40, the remote fetch of a schema worked well:
![image](https://github.com/microsoft/monaco-editor/assets/32708605/e4796d4f-71b7-48dc-9974-aacc76ca1538)

Since v0.41 the schemaRequest is not transmitted anymore, no schema is loaded and hence editor highlighting and automcomplete features are not available. 
The onMount configuration of the editor has not changed in the meantime and looks as follows:

`  private onMount(editor: editor.IStandaloneCodeEditor, monaco) {
    const defaultOptions: editor.IEditorOptions & editor.IGlobalEditorOptions = {
      tabSize: 2,
      readOnly: options.readonly,
    };

    editor
      .getAction('editor.action.formatDocument')
      .run()
      .then(() => {
        if (options.schemaUrl) {
          monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
            validate: true,
            enableSchemaRequest: true,
            schemas: [
              {
                uri: options.schemaUrl,
                fileMatch: ['*'],
              },
            ],
          });
        }

        editor.updateOptions(defaultOptions);
      });
  }`

**Comment by hediet** [comment] 2023-10-05 14:13
This is fixed now.

**Closed by hediet** 2023-10-05 14:13 UTC
