### ISSUE TITLE
right click paste issue

### ISSUE THREAD

**Issue by netglobaltr** [microsoft/monaco-editor#1928] opened 2020-04-16 16:38 UTC
**monaco-editor version:** 0.X.Y
**Browser:**
**OS:**
**Playground code that reproduces the issue:**

```js
```

**Comment by alexdima** [comment] 2020-09-04 13:16
Duplicate of https://github.com/microsoft/vscode/issues/82604

**Closed by alexdima** 2020-09-04 13:16 UTC
