### ISSUE TITLE
JSDoc type annotations work in VSCode but not Monaco

### ISSUE THREAD

**Issue by greggman** [Microsoft/monaco-editor#203] opened 2016-09-26 04:39 UTC
monaco-editor npm version: 0.6.1
Browser: All
OS: all

If I put this code in VSCode 1.5.3

```
/** @type {WebGLRenderingContext} */
var gl = canvas1.getContext("webgl");

/** @type {CanvasRenderingContext2D} */
var ctx = canvas1.getContext("2d");
```

Both `gl` and `ctx` will get the correct auto-completion for their respective types but the same code does not get auto completions in Monaco.  Note: Monaco does know the definitions of `WebGLRenderingContext` and `CanvasRenderingContext2D` as I can type `WebGLRenderingContext.prototype.` and see all the completions.

Is this a feature I just need to enable? Is it just not yet pulled from VSCode? Or is it a feature that's not meant to be part of Monaco?

**Comment by alexandrudima** [comment] 2016-09-26 20:48
Hmm, it's a surprise for me too. @jrieken any ideas?

I've also found function annotations to not be working
```js
/**
 * @returns {string}
 */
function f() {
	return canvas1;
}
```

**Comment by jrieken** [comment] 2016-09-27 07:21
We ship different versions of TypeScript in the standalone editor and VS Code

**Comment by greggman** [comment] 2016-09-27 10:12
Meaning if I just upgrade the TypeScript support to the same version in VS Code it will start working? Or, meaning the stuff in VS Code is not compatible with Monaco?

**Comment by greggman** [comment] 2016-09-29 04:55
Well if you're curious I added the monaco editor to http://webglfundamentals.org.  All of the examples run in a codepen style editor using monaco. Every sample has this at the top

      /** @type {HTMLCanvasElement} */
      var canvas = document.getElementById("canvas");
      var gl = canvas.getContext("webgl");

If monaco supported type annotations like VSCode then from that both `canvas` and `gl` would support all the intellisense like functions. 

If there's a way to make that work that would be great.

**Comment by nkev** [comment] 2016-12-27 12:52
@jrieken is there any progress with this issue?

**Comment by jrieken** [comment] 2017-01-16 14:19
closing as dupe of #177

**Comment by greggman** [comment] 2017-02-03 04:16
I'm confused how #177 relates to this. #177 is closed saying the project is now on TypeScript 2.1 but this issue, issue #203 still doesn't work.

Is there's a way to make it work? Or if not could you please re-open this issue?

**Comment by alexandrudima** [comment] 2017-02-03 07:49
I can confirm JSDoc annotations still don't work.

@jrieken Perhaps there is more to getting them work than updating to TS 2.1

**Comment by jonnermut** [comment] 2017-03-27 04:00
Is there any way to hint Monaco of the type of a given function parameter dynamically (eg without modifying the editor source) ?
I tried dynamically creating a d.ts for a given function signature, but when you declare that function in the editor it treats it as an override, and ignores the type information I added.
See
http://stackoverflow.com/questions/43037243/provide-type-hints-to-monaco-editor

**Comment by kitsonk** [comment] 2017-06-18 01:48
I have added a PR in `monaco-typescript`.  The providers for `monaco-editor` are greatly simplified from the language features for `vscode`.  In `vscode` there is now further abstraction away from the language services which also extractions the documentation and tags from the quick info and returns them from the hover provider.

**Comment by jonnermut** [comment] 2017-06-18 23:56
@kitsonk  I had a quick look at your PR ( https://github.com/Microsoft/monaco-typescript/pull/14 ), I don't think it actually fixes this issue, which is about having the Monaco know the type of a parameter from the JSDoc annotations, so that code complete / intellisense works on that parameter?

**Comment by jrieken** [comment] 2017-06-19 09:16
<img width="408" alt="screen shot 2017-06-19 at 11 13 45" src="https://user-images.githubusercontent.com/1794099/27277977-680c9a00-54e0-11e7-8ebd-0edfc5432336.png">

This works for me (without https://github.com/Microsoft/monaco-typescript/issues/14) on master. It is important to know that this is supported in JS files only and the we interpret files as JS when they have an uri-path that ending in `.js` like `some/path/some/file.js`. When no ending is available make sure to use the `allowJs`-compiler setting

**Comment by jrieken** [comment] 2017-06-19 09:17
The fix for this (https://github.com/Microsoft/monaco-typescript/commit/9b5c885b40c385b726f70627c7957c2e1436aa0e) will be in the next release.

**Closed by jrieken** 2017-06-19 09:17 UTC

**Comment by jonnermut** [comment] 2017-06-19 09:27
Cool. Just to confirm @jrieken, a and b will have code complete within the body of foo()?
