### ISSUE TITLE
`getDocumentSymbols` returns incorrect ordered symbol list in flatten mode

### ISSUE THREAD

**Issue by JounQin** [microsoft/monaco-editor#2517] opened 2021-06-09 10:28 UTC
**monaco-editor version:** 0.24.0
**Browser: Chrome 91.0.4472.77
**OS: macOS 12.0 Beta
**Playground code that reproduces the issue:**

https://alauda.github.io/k8s-form-in-action/demo/

Change the yaml content like the following:

```yaml
containers:
  - name: nginx
    ports:
      - containerPort: 80
```

open devtool, execute `window.DEBUG = true`, click the yaml content you will get

![image](https://user-images.githubusercontent.com/8336744/121338286-f2522080-c94f-11eb-9c51-556fa8c48493.png)

As you can see, `name` symbol comes before `0` which is incorrect obviously, while `containerPort` comes after `0` which is correct.

What means when a symbol has multi children, the flatted result is incorrect.

If you want to run this sample locally, you can check https://github.com/alauda/k8s-form-in-action

run `yarn && yarn dev` and then visit http://localhost:4200

The related source code is at https://github.com/alauda/k8s-form-in-action/blob/master/src/app/demo/component.ts#L168

**Comment by hediet** [comment] 2021-06-09 13:04
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community!

I'll close this issue, but if you have specific follow up questions, we'll try to help as good as we can given the limited resources that we have.

Thanks for your understanding!

**Comment by JounQin** [comment] 2021-06-09 13:20
@hediet I don't understand what's your meaning, it is a bug of `getDocumentSymbols` in vscode https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/documentSymbols/documentSymbols.ts

The non-flatten result of `getDocumentSymbols(model, false, NEVER_CANCEL_TOKEN)` is correct, so I can fix it on our side by using a custom util:

```ts
/**
 * fix https://github.com/microsoft/monaco-editor/issues/2517 temporarily.
 * Ideally, we should use the `flat` parameter of `getDocumentSymbols` instead.
 */
const flatSymbols = (symbols: languages.DocumentSymbol[]) => {
  const flattenSymbols: languages.DocumentSymbol[] = [];
  for (const symbol of symbols) {
    flattenSymbols.push(symbol);
    if (symbol.children?.length) {
      flattenSymbols.push(...flatSymbols(symbol.children));
    }
  }
  return flattenSymbols;
};
```

Is this an invalid bug? My English is not good enough to understand why you close it.

**Comment by hediet** [comment] 2021-06-09 13:40
I guess this sort should use a stable sort:

https://github.com/microsoft/vscode/blob/b5d6d7e62e3c2ae4faec100a81f7ba16e1418b7c/src/vs/editor/contrib/documentSymbols/outlineModel.ts#L463

See https://github.com/microsoft/vscode/issues/125840.

**Comment by JounQin** [comment] 2021-06-09 13:41
@hediet Yeah, thanks for raising the new related issue in vscode.

**Comment by hediet** [comment] 2021-06-09 15:01
@JounQin unfortunately the sorting operation should not be an issue, as it is stable.

Can you find out what the issue is in the vscode codebase? I'll probably wont find time this week to look into it.

**Comment by JounQin** [comment] 2021-06-09 15:22
Sorry, I'm not familiar with vscode codebase, but I'll try to find out when I'm free tomorrow.

**Comment by spahnke** [comment] 2021-06-09 15:44
Can't offer much help here, but as far as I know the Monaco editor does not provide any language intelligence for YAML out-of-the-box. So where are these symbols computed? Where does the `DocumentSymbolProvider` come from? I would start there and look into the ordering coming directly from that provider. That would probably also help you in providing a minimal repro if there should be a bug on Monaco's side.

**Comment by JounQin** [comment] 2021-06-10 00:17
@spshnke I'm using monaco-yaml.

**Comment by JounQin** [comment] 2021-06-15 04:48
@spahnke Here you go: https://github.com/JounQin/test/blob/monaco-editor/src/App.vue#L35

It's use monaco manually at https://github.com/JounQin/test/blob/monaco-editor/src/components/monaco-editor/setup-monaco.ts

**Comment by rcjsuen** [comment] 2021-07-02 12:29
I did some digging into this...

```JavaScript
const value =
    `containers:
  - name: nginx
    ports:
      - containerPort: 80`;

monaco.editor.create(document.getElementById("container"), {
    value: value,
    language: "yaml"
});

const symbols = [
    {
        name: "containers",
        range: {
            startLineNumber: 1, startColumn: 1,
            endLineNumber: 4, endColumn: 26
        }
    },
    {
        name: "container 0",
        range: {
            startLineNumber: 2, startColumn: 5,
            endLineNumber: 5, endColumn: 1
        },
    },
    {
        name: "name",
        range: {
            startLineNumber: 2, startColumn: 5,
            endLineNumber: 2, endColumn: 16
        }
    },
    {
        name: "ports",
        range: {
            startLineNumber: 3, startColumn: 5,
            endLineNumber: 5, endColumn: 1
        }
    },
    {
        name: "ports 0",
        range: {
            startLineNumber: 4, startColumn: 9,
            endLineNumber: 4, endColumn: 26
        }

    },
    {
        name: "containerPort",
        range: {
            startLineNumber: 4, startColumn: 9,
            endLineNumber: 4, endColumn: 26
        }
    }
]

monaco.languages.registerDocumentSymbolProvider("yaml", {
    provideDocumentSymbols: (model, token) => {
        return symbols.map(s => {
            return {
                name: s.name,
                range: s.range,
                selectionRange: s.range,
                kind: monaco.languages.SymbolKind.Object
            }
        });
    }
});
```
![image](https://user-images.githubusercontent.com/15629116/124274053-cd943780-db0e-11eb-8d4b-07be62824017.png)
1. You can reproduce this issue by running the above JavaScript code in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html). Use F1 in the editor and use `@` to jump to the symbol. In my screenshot I've added some whitespace after creating the editor so you can see both the code and the list of symbols for illustrative purposes.
```JavaScript
const ranges = [
    {startLineNumber: 1, startColumn: 1, endLineNumber: 5, endColumn: 1}, // containers
    {startLineNumber: 2, startColumn: 5, endLineNumber: 5, endColumn: 1}, // 0-th element of containers
    {startLineNumber: 2, startColumn: 5, endLineNumber: 2, endColumn: 16}, // name
    {startLineNumber: 3, startColumn: 5, endLineNumber: 5, endColumn: 1}, // ports
    {startLineNumber: 4, startColumn: 9, endLineNumber: 4, endColumn: 26}, // 0-th element of ports
    {startLineNumber: 4, startColumn: 9, endLineNumber: 4, endColumn: 26}, // containerPort
]
ranges.sort((a, b) => {
    return monaco.Range.compareRangesUsingStarts(a, b);
});
console.log(ranges);
```
2. The reason the symbols are getting "moved around" is because of how VS Code is sorting them in [`compareRangesUsingStarts(*)`](https://github.com/microsoft/vscode/blob/062e6519f8973fede2ca736e80682bd19007460a/src/vs/editor/common/core/range.ts#L397-L424). You can see this change by running the above JavaScript code in the Monaco Editor Playground. The calling code can be found [here](https://github.com/microsoft/vscode/blob/062e6519f8973fede2ca736e80682bd19007460a/src/vs/editor/contrib/documentSymbols/outlineModel.ts#L459-L464) and you can keep walking backwards from there as desired.
3. @JounQin I should note to you that the `getDocumentSymbols(*)` function is not considered API based on the contents of the [`vscode.d.ts` file](https://github.com/microsoft/vscode/blob/062e6519f8973fede2ca736e80682bd19007460a/src/vs/vscode.d.ts) or the [`monaco.d.ts` file](https://github.com/microsoft/vscode/blob/f45814f108dbc65c47ae2514eb181e4c01906b69/src/vs/monaco.d.ts) so you shouldn't be using it to get an outline of the symbols from a model.

**Comment by hediet** [comment] 2021-07-02 12:48
@rcjsuen thanks a lot for investigating! Did you spot the bug in the code base? Is there something wrong in `compareRangesUsingStarts`?

> should note to you that the getDocumentSymbols(*) function is not considered API based

This is right. We are open for PRs though if they fix reproducible bugs.

**Comment by rcjsuen** [comment] 2021-07-02 13:19
> Is there something wrong in `compareRangesUsingStarts`?

@hediet Depends who you ask. The function may be working as intended but it's the document symbol provider that should be using a different algorithm for sorting purposes.
```TypeScript
/**
  * A function that compares ranges, useful for sorting ranges
  * It will first compare ranges on the startPosition and then on the endPosition
  */
```
The documentation for the function doesn't tell us whether it considers "longer" or "bigger" ranges as being "greater" or "lesser" for comparison purposes.

**Comment by JounQin** [comment] 2021-08-15 02:26
> I should note to you that the getDocumentSymbols(*) function is not considered API based on the contents of the vscode.d.ts file or the monaco.d.ts file so you shouldn't be using it to get an outline of the symbols from a model.

@rcjsuen Thank you, I understand it, and I'm just using it for a demo example only.

But obviously, it is a bug of vscode/monaco-editor, right?

**Comment by alexdima** [comment] 2021-12-06 11:17
Let's track at https://github.com/microsoft/vscode/issues/138502

**Closed by alexdima** 2021-12-06 11:17 UTC
Labels: bug
