### ISSUE TITLE
[Bug] suggest-details element way off screen in swagger pages

### ISSUE THREAD

**Issue by kolodny** [microsoft/monaco-editor#2945] opened 2022-02-07 01:45 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Additional Context

I'm only encountering this issue on swagger ui pages. The easiest way to explain is to go to https://petstore.swagger.io/ and paste this into the devtools to load up a monaco instance:

```js
var script = document.createElement('script');
script.src = 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.26.1/min/vs/loader.min.js'
document.head.appendChild(script)
await new Promise(r => setTimeout(r, 200))
require.config({ paths: { 'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.26.1/min/vs' }});
require(["vs/editor/editor.main"], () => {
  const el = document.createElement('div');
  el.style.height = '400px';
  el.style.width = '50%';
  document.body.appendChild(el)
  monaco.editor.create(el, {
    value: `{
  
}`,
    language: 'json',
    theme: 'vs-dark',
  });
});
```

If you then try to view the expanded suggestions pane it will render them off screen. To see this I just paste `setTimeout(() => {debugger;}, 3000)` into the devtools and open up the suggestions:

![image](https://user-images.githubusercontent.com/1187604/152712085-f9274445-3066-4963-8c23-a66343949669.png)

As you can see the suggest-details are positioned offscreen.

![image](https://user-images.githubusercontent.com/1187604/152712289-28dc1ae5-b838-4bd4-b954-12f6319abd4b.png)

If we were to remove the position fixed on that container we'd at least see it on screen (but still off of where it should be)

![image](https://user-images.githubusercontent.com/1187604/152712202-dafa4a9c-f2a8-464f-b49b-b14554e83742.png)

**Comment by JarvisArt** [comment] 2022-02-22 06:28
I have the same problem

**Comment by jrieken** [comment] 2023-12-13 08:39
/duplicate of https://github.com/microsoft/monaco-editor/issues/3373

**Closed by jrieken** 2023-12-13 08:39 UTC
Labels: suggest
