### ISSUE TITLE
no code emitted when noEmitOnError=true

### ISSUE THREAD

**Issue by meriturva** [Microsoft/monaco-editor#324] opened 2017-01-18 09:02 UTC
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: Windows

I have created an easy Plunker https://plnkr.co/edit/8W7B4X?p=preview
As you can see i set option `noEmitOnError = true` but no code is generated when code is correct.
Maybe i miss something but documentation https://www.typescriptlang.org/docs/handbook/compiler-options.html just say: 

> --noEmitOnError Do not emit outputs if any errors were reported.

To test plunker:

1. Open plunker
2. Open console
3. Modify code and see "result" object on console
4. No code is generated ad all

If you set `noEmitOnError = false` code is present...always.
Thanks
Diego

**Comment by Smesharikable** [comment] 2017-01-31 10:16
I think there is no problem with "noEmitError" option. As I can see monaco just can not create typescript worker to transpile code and log about it to console:

`Failed to construct 'Worker': Script at 'https://unpkg.com/monaco-editor@0.7.0/min/vs/base/worker/workerMain.js#typescript' cannot be accessed from origin 'https://run.plnkr.co'.
a @ unpkg.com/monaco-editor@0.7.0/min/vs/editor/editor.main.js:37
`

**Comment by meriturva** [comment] 2017-01-31 10:27
Thanks for you answer @Smesharikable .
Main problem is to test monaco editor with plunker and web workers.
You could test example locally and see that with no worker errors but `noEmitError` ignored

**Comment by Smesharikable** [comment] 2017-01-31 11:06
It seems like the problem is **noLib: true** option. If you decided to turn off standard lib, then you must provide you own, otherwise [compiler will throw erros](https://github.com/Microsoft/TypeScript/issues/3930), so **noEmitError** option is working like intended. You can see it by changing it to **false**, or **noLib** to **false**.

**Comment by jrieken** [comment] 2017-06-19 08:42
Closing as question because this is about setting up the compiler for relaxed or strict emitting with all pre-reqs full-filled.

**Closed by jrieken** 2017-06-19 08:42 UTC
Labels: monaco-typescript, question
