### ISSUE TITLE
[Feature Request] Add a way to pass in args to a code action

### ISSUE THREAD

**Issue by BeishaoCao-db** [microsoft/monaco-editor#3833] opened 2023-03-14 19:24 UTC
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

When we call addAction, the run function can have args, but it seems we don't have a way to pass in args

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAALBBQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw9fqCIXz0ZtUutrzmzM_2QKgeoqtXwswxDNWQ4iBjVtVYFiU6U25SrsLN94I90o4J21rgqHHZHLD2B5LvmtHuRtdRN5VtGM3ke73nTSkPeFDHz8ibO4SyHJYPp1pZ5jW52BYjoxneRtjyU3zv3lp2XlN1wRe4ZSXD4S-DtzX688qCh-cFWMkkwmzSOTQvDrwDV7YEKR9QVoZHHd_68FSflpi-T-htb8bh8dAMBGjFZ69DT8bFvEOZwZ5w8GGMHJVw7o5EYECS4fCWQ1i0tNp5M514C5O6OJIf7lAHlM0C7oYwYcndRgICqdlmEKe0Byec2LZssHxPsu_N-PQc2T2DuAkoSz_qfr2ofsJx3EiN1gpJt7o4ebQdC92N4mpk8gPFBFy8O1d8kUHpqxRtCwCAbBUoY6R8uIKSQ51ZAs43MwB0PIlCGVTmI05dkLcDiFaBj9CwVQN6BwYLJPwh389pZNjrRLfOlQqd0rNMuuFa4wtvTp4IBTiq-Sb-w2nTTxsUZ1E-a74s0eQGFkoOiROgezL53fGiDavnS-wVg01R-SOq7RNagjWMxeWCz_Vb4riCgSHpcf9UW2QFeeQUA2svbd2tyyMTP-NWDUUu8AY6pzW0kLFA3X0Q_yd1q1mY-Gk2RtCJdIf7w6cNYcJEsnCD6xFJFLSh__fKWMF_i29-MNHwsge36khlclOX3DhezRbkqtSDn1FRNpzaFNfbFKKP_rIL9rymrpbnSzpljn9AnokguBAQmaAc4NWqiFTaBHfSSu9PCtwbnPqRYwyz7G5sb-7cbmQHecSQ5MT-VWogb6GpfFkZMSLD3YfnTsh4RNnhbO1b9NC3B6qRBRjKMqtmuiqz0dEtOvQvZ--pBrwto8XJknIglRSP3rio9Vsb2rEdOGdcDsyBvN39PAfnh1rvEEhKWZ75b7jJJYljV9ehNLPUSqC2AuKp_-EXglY

### Monaco Editor Playground Code

```typescript
var editor = monaco.editor.create(document.getElementById("container"), {
	value: [
		"",
		"class Example {",
		"\tprivate m:number;",
		"",
		"\tpublic met(): string {",
		'\t\treturn "Hello world!";',
		"\t}",
		"}",
	].join("\n"),
	language: "typescript",
});

// Explanation:
// Press F1 => the action will appear and run if it is enabled
// Press Ctrl-F10 => the action will run if it is enabled
// Press Chord Ctrl-K, Ctrl-M => the action will run if it is enabled

editor.addAction({
	// An unique identifier of the contributed action.
	id: "my-unique-id",

	// A label of the action that will be presented to the user.
	label: "My Label!!!",

	// An optional array of keybindings for the action.
	keybindings: [
		monaco.KeyMod.CtrlCmd | monaco.KeyCode.F10,
		// chord
		monaco.KeyMod.chord(
			monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyK,
			monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyM
		),
	],

	// A precondition for this action.
	precondition: null,

	// A rule to evaluate on top of the precondition in order to dispatch the keybindings.
	keybindingContext: null,

	contextMenuGroupId: "navigation",

	contextMenuOrder: 1.5,

	// Method that will be executed when the action is triggered.
	// @param editor The editor instance is passed in as a convenience
	run: function (ed, a) {
		alert("i'm running => " + ed.getPosition() + a);
	},
});

editor.trigger('', "my-unique-id", [editor, 'i'])
```

**Comment by spahnke** [comment] 2023-03-15 11:12
I believe this is a duplicate of #2547 which was fixed a couple of days ago.

**Comment by hediet** [comment] 2023-03-15 11:41
Unfortunately my fix wasn't proper, working on it.

**Closed** 2023-03-15 13:36 UTC
Labels: feature-request

**Comment by BeishaoCao-db** [comment] 2023-03-17 22:37
Thanks for the fix! When will this feature publish? As well as that of https://github.com/microsoft/monaco-editor/issues/2547
