### ISSUE TITLE
How to indent/prettify code on load of Monaco Editor

### ISSUE THREAD

**Issue by batata004** [microsoft/monaco-editor#2664] opened 2021-09-17 17:35 UTC
Hi,

I am using this code:
```

monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {alert('Hello world!');}",
	language: "javascript",
    "autoIndent": true,
    "formatOnPaste": true,
    "formatOnType": true
});

```

I would like it to prettify/indent the JS code in the "value" when it loads, but it never works. I already tried using methods like `window.editor.getModel().updateOptions({ "autoIndent": true,tabSize: 2 })` but also never works. Any idea how I can make monaco editor prettify the code as it loads, indenting or adding tabs to make it more readable?

**Comment by rcjsuen** [comment] 2021-09-17 19:46
> Any idea how I can make monaco editor prettify the code as it loads, indenting or adding tabs to make it more readable?

You can use `editor.getAction('editor.action.formatDocument').run()` to format the document.

I am not aware of any initialization event. See #115.

**Comment by batata004** [comment] 2021-09-17 20:03
@rcjsuen I tried your suggestion but it looks like it only works with `language:html`. I am doing something wrong? When using `css`, `php`, `js`... your code will do nothing. Any idea?

**Comment by rcjsuen** [comment] 2021-09-17 21:31
> When using `css`, `php`, `js`... your code will do nothing. Any idea?

I tried it in JavaScript in the [playground](https://microsoft.github.io/monaco-editor/playground.html) and it seems to work.

```JavaScript
const editor = monaco.editor.create(document.getElementById("container"), {
    value: "function hello(){\nalert('Hello world!');}",
    language: "javascript",
    "autoIndent": true,
    "formatOnPaste": true,
    "formatOnType": true
});

setTimeout(() => {
    editor.getAction('editor.action.formatDocument').run();
}, 1000)
```

**Comment by batata004** [comment] 2021-09-17 21:42
You are right! Javascript work too! That's already pretty nice, cause it was the main reason why I needed it! Thank you so much my friend!

One final question: I know I can select the amount of spaces/tabs to indent the code. Do you know if is possible to tell it to skip lines?

Instead of:

```
function xxx(){
    a = 3;
}
```

it would do:

```
function xxx(){

    a = 3;

}
```

?

**Comment by rcjsuen** [comment] 2021-09-17 23:27
> One final question: I know I can select the amount of spaces/tabs to indent the code. Do you know if is possible to tell it to skip lines?

No, I don't know how to configure the formatter or if you even can.

**Comment by lsycxyj** [comment] 2022-10-13 12:04
> > When using `css`, `php`, `js`... your code will do nothing. Any idea?
> 
> I tried it in JavaScript in the [playground](https://microsoft.github.io/monaco-editor/playground.html) and it seems to work.
> 
> ```js
> const editor = monaco.editor.create(document.getElementById("container"), {
>     value: "function hello(){\nalert('Hello world!');}",
>     language: "javascript",
>     "autoIndent": true,
>     "formatOnPaste": true,
>     "formatOnType": true
> });
> 
> setTimeout(() => {
>     editor.getAction('editor.action.formatDocument').run();
> }, 1000)
> ```

It doesn't always work. For some slow pages (eg. multiple monaco editor instances), it doesn't work at all.

**Comment by kyr0** [comment] 2023-03-13 10:42
None of these solutions worked for me. I'm calling `editor.action.formatDocument` when the editor is initialized and fires an  `onDidLayoutChange`, but nothing happens. So, to deal with that, I'm simply simulating a scroll event, as this triggers the Monaco internal implementation to syntax-highlight:

```ts
editorInstance.onDidLayoutChange(() => {
  requestAnimationFrame(() => {
    editorInstance
    .getDomNode()
        ?.querySelector(".editor-scrollable")
        ?.scroll({
          behavior: "smooth",
          top: 5,
        });
  });
});
```

**Comment by hediet** [comment] 2023-03-13 11:00
Closing as duplicate of https://github.com/microsoft/monaco-editor/issues/115

**Closed by hediet** 2023-03-13 11:00 UTC
Labels: feature-request, editor-core
