### ISSUE TITLE
[Bug] accessibilityHelp feature disabled narrator still announces accessibility

### ISSUE THREAD

**Issue by easyas123l1** [microsoft/monaco-editor#3555] opened 2023-02-13 21:25 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

install MonacoEditorWebpackPlugin as a dependency -> follow these instructions to add MonacoEditorWebpackPlugin https://www.npmjs.com/package/monaco-editor-webpack-plugin?activeTab=readme.  

in the features array disable 'accessibilityHelp' by commenting it out.

restart your server for changes to take place.

test with a accessibility narrator IE I used JAWS 2019.  

### Actual (Problematic) Behavior

when focus enters the monaco editor it prompts the user to press alt + f1 for a list of more accessibility options even though the feature is turned off.

### Expected Behavior

when focus enters the monaco editor and accessibilityHelp feature is disabled it should skip prompting user to press alt + f1 for more accessibility options.

**Comment by rzhao271** [comment] 2024-12-18 19:58
Duplicate of https://github.com/microsoft/monaco-editor/issues/4674

**Closed by rzhao271** 2024-12-18 19:58 UTC
Labels: feature-request, editor-core
