### ISSUE TITLE
Diff editor interactive merging like Ace-Diff

### ISSUE THREAD

**Issue by prashant-saxena** [microsoft/monaco-editor#2635] opened 2021-08-25 05:19 UTC
Hi,
It would be great if we can have something like [Ace-Diff](https://github.com/ace-diff/ace-diff) interactive merging of diff.
Is it possible to implement such feature with the current state of API at simple level?

For e.g. an option to merge the current partial on right click context menu based on the cursor's position, similar to Ace-diff arrows.

Regards

**Comment by spahnke** [comment] 2021-08-25 06:38
Duplicate of https://github.com/microsoft/monaco-editor/issues/2269. Maybe you can add your example in that thread.

**Closed** 2021-08-25 09:47 UTC
