### ISSUE TITLE
Monarch languages typescript interfaces are inconsistent

### ISSUE THREAD

**Issue by Geloosa** [Microsoft/monaco-editor#1008] opened 2018-08-15 10:54 UTC
monaco-editor version: 0.13.1

1. Shortend expressions can't be used in a Monarch language definition. For example, `IMonarchLanguageBracket ` interface is
```
   /**
     * This interface can be shortened as an array, ie. ['{','}','delimiter.curly']
     */
    export interface IMonarchLanguageBracket {
        /**
         * open bracket
         */
        open: string;
        /**
         * closeing bracket
         */
        close: string;
        /**
         * token class
         */
        token: string;
    }
```
so I can't use proposed `['{','}','delimiter.curly']` shorthand.

2. Moreover, I can't declare any common regular expressions or keywords or operators in a language definition without extending `IMonarchLanguage` interface. Cause it's the following: 
```
   /**
     * A Monarch language definition
     */
    export interface IMonarchLanguage {
        /**
         * map from string to ILanguageRule[]
         */
        tokenizer: {
            [name: string]: IMonarchLanguageRule[];
        };
        /**
         * is the language case insensitive?
         */
        ignoreCase?: boolean;
        /**
         * if no match in the tokenizer assign this token class (default 'source')
         */
        defaultToken?: string;
        /**
         * for example [['{','}','delimiter.curly']]
         */
        brackets?: IMonarchLanguageBracket[];
        /**
         * start symbol in the tokenizer (by default the first entry is used)
         */
        start?: string;
        /**
         * attach this to every token class (by default '.' + name)
         */
        tokenPostfix: string;
    }
```

And `tokenPostfix` is not optional though here it has a default value.

3. And the biggest problem - `IMonarchLanguageAction ` interface:
```
export interface IMonarchLanguageAction {
        /**
         * array of actions for each parenthesized match group
         */
        group?: IMonarchLanguageAction[];
        /**
         * map from string to ILanguageAction
         */
        cases?: Object;
        /**
         * token class (ie. css class) (or "@brackets" or "@rematch")
         */
        token?: string;
        /**
         * the next state to push, or "@push", "@pop", "@popall"
         */
        next?: string;
        /**
         * switch to this state
         */
        switchTo?: string;
        /**
         * go back n characters in the stream
         */
        goBack?: number;
        /**
         * @open or @close
         */
        bracket?: string;
        /**
         * switch to embedded language (useing the mimetype) or get out using "@pop"
         */
        nextEmbedded?: string;
        /**
         * log a message to the browser console window
         */
        log?: string;
    }
```

If I declare a group of actions 'action: {group: [{token: 'keyword'}, {token: 'entity'}]}' for parenthesized match groups '/(first)(second)/' the code iscompiled succefully. But I get this error in runtime:
**Error: myLanguage: an action must be a string, an object with a 'token' or 'cases' attribute, or an array of actions; in rule: tokenizer.root: (first)(second)**

If I declare just an array of actions 'action : [{token: 'keyword'}, {token: 'entity'}]' which runs perfectly, thus I get a type error **Type '{ token: string; }[]' has no properties in common with type 'IMonarchLanguageAction'** during compilation.

**Comment by alexandrudima** [comment] 2018-08-15 14:32
@Geloosa PR welcome. The type definitions for a monarch language are not stellar. The root cause is that monarch was contributed to our project and was initially written in JavaScript. Ever since, we are trying to untangle the types it uses.

**Comment by alexandrudima** [comment] 2018-08-29 12:00
Fixed via https://github.com/Microsoft/vscode/pull/57439

**Closed by alexandrudima** 2018-08-29 12:00 UTC

**Comment by cport1** [comment] 2018-12-11 21:00
Is this fix published to npm?

**Comment by davidgomes** [comment] 2019-01-02 16:36
@cport1 it has.
