### ISSUE TITLE
[Bug] Chinese input causes the line to jump abnormally

### ISSUE THREAD

**Issue by tingjiangcao** [microsoft/monaco-editor#4602] opened 2024-07-13 15:02 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://github.com/user-attachments/assets/ecccd115-74fc-4992-ab84-dfb39bdca538

https://github.com/user-attachments/assets/4e27e1bc-43e1-4736-b6bc-a023e7c878a8

**Comment by rzhao271** [comment] 2024-12-18 22:03
Duplicate of https://github.com/microsoft/monaco-editor/issues/4592

**Closed by rzhao271** 2024-12-18 22:03 UTC
