### ISSUE TITLE
[Bug] In the same span, some of characters are invisible

### ISSUE THREAD

**Issue by henryhe1993** [microsoft/monaco-editor#3042] opened 2022-03-28 09:28 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

![bug](https://user-images.githubusercontent.com/30046120/160367184-e3b99d46-a33b-4b5c-b640-cc1ba5712b1c.png)

### Additional Context

Completely have no idea of what is happening. Even don't think it is a bug of monaco editor.
Maybe it is a bug of Chrome, cos I use dual monitor on mac. It happens on the external one, but works on the native one.
Not a consistent bug.

Environment
Mac:
macOS Monterey
12.2.1 (21D62)
MacBook Pro (16-inch, 2019)

Chrome: 
99.0.4844.83  (x86_64)

Happens on m1 too.

----- Additional Information -------
mtk1 is set to be rbg(255, 255, 255) which is not on the screenshot.
If i change any one of the RGB value under 224 (not include), it works....so strange.

**Comment by henryhe1993** [comment] 2022-03-28 09:32
if i change any one of the RGB value under 224 (not include), it works....so strange.

**Comment by hediet** [comment] 2022-03-29 08:27
Can you provide a reproducible example?

**Comment by henryhe1993** [comment] 2022-03-30 02:19
> Can you provide a reproducible example?

Sorry, no. Even in the same environment (software & hardware), it works as expected for most of the time.

**Comment by hediet** [comment] 2022-03-30 09:02
Hmm, given that we cannot reproduce it in a reasonable amount of time and it is likely a chrome issue, I have to close this issue.

**Closed by hediet** 2022-03-30 09:02 UTC
