### ISSUE TITLE
node.parent undefined

### ISSUE THREAD

**Issue by pgherveou** [microsoft/monaco-editor#1985] opened 2020-05-27 14:36 UTC
Hi, I ran into this error today where typescript is trying to run a function on a parent node that does not exist. (see screenshot below)

Is it something that should be reported to https://github.com/microsoft/typescript instead?

<img width="696" alt="Screen Shot 2020-05-27 at 10 26 41 AM" src="https://user-images.githubusercontent.com/521091/83033339-fe996300-a004-11ea-885e-522c6503e2e0.png">

It also triggers on https://microsoft.github.io/monaco-editor/ with this error
```
errors.ts:22 Uncaught Error: Cannot read property 'kind' of undefined

TypeError: Cannot read property 'kind' of undefined
    at Object.e.isImportClause (tsWorker.js:21)
    at Object.n.deleteDeclaration (tsWorker.js:21)
    at r (tsWorker.js:21)
    at n.finishDeleteDeclarations (tsWorker.js:21)
    at n.getChanges (tsWorker.js:21)
    at Function.n.with (tsWorker.js:21)
    at Object.getCodeActions (tsWorker.js:21)
    at tsWorker.js:21
    at Object.e.flatMap (tsWorker.js:21)
    at Object.n.getFixes (tsWorker.js:21)
    at errors.ts:22
(anonymous) @ diffChange.ts:41
setTimeout (async)
unexpectedErrorHandler @ diffChange.ts:41
e.onUnexpectedExternalError @ diffChange.ts:41
t.onUnexpectedExternalError @ diffChange.ts:41
(anonymous) @ codeAction.ts:59
(anonymous) @ marked.js:8
(anonymous) @ marked.js:8
a @ compressedObjectTreeModel.ts:353
Promise.then (async)
l @ compressedObjectTreeModel.ts:353
(anonymous) @ compressedObjectTreeModel.ts:353
d @ compressedObjectTreeModel.ts:353
(anonymous) @ codeAction.ts:59
y @ codeAction.ts:59
(anonymous) @ codeActionModel.ts:202
r @ cancellation.ts:126
(anonymous) @ codeActionModel.ts:202
t._createEventAndSignalChange @ codeActionModel.ts:71
t.trigger @ codeActionModel.ts:23
(anonymous) @ codeActionModel.ts:23
(anonymous) @ async.ts:165
setTimeout (async)
e.cancelAndSet @ async.ts:165
t._onCursorChange @ codeActionModel.ts:23
(anonymous) @ codeActionModel.ts:23
e.fire @ event.ts:538
(anonymous) @ codeEditorWidget.ts:1299
e.fire @ event.ts:538
t._emitStateChangedIfNecessary @ cursor.ts:518
t.setStates @ cursor.ts:284
t.runCoreEditorCommand @ coreCommands.ts:216
executeEditorCommand @ codeEditorWidget.ts:1343
e._execMouseCommand @ editorState.ts:145
e.moveTo @ viewController.ts:202
e.dispatchMouse @ viewController.ts:136
t._dispatchMouse @ mouseHandler.ts:498
t.start @ mouseHandler.ts:333
t._onMouseDown @ mouseHandler.ts:196
(anonymous) @ mouseHandler.ts:106
(anonymous) @ editorDom.ts:95
```

**monaco-editor version:** 0.20.0
**Browser:**: electron
**OS:**  macOS catalina
**Playground code that reproduces the issue:**
```js
import {Observable} from 'rxjs'
```

**Comment by orta** [comment] 2020-09-08 11:29
Yep, this looks like a TypeScript bug rather than one in Monaco-editor 👍🏻

**Comment by alexdima** [comment] 2020-09-18 18:26
Duplicate of #1638, because this is also fixed by https://github.com/microsoft/monaco-typescript/commit/0ac03ae5cd15be689e7806c038269eb162bc5bf0

**Closed by alexdima** 2020-09-18 18:26 UTC
Labels: bug, monaco-typescript, upstream
