### ISSUE TITLE
Language syntax VB: backslash is not an escape character

### ISSUE THREAD

**Issue by pablonete** [microsoft/monaco-editor#1996] opened 2020-06-02 15:45 UTC
**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Windows
**Playground code that reproduces the issue:**

Open https://microsoft.github.io/monaco-editor/
Select Language vb

```
Print "Hola" & "\" & Name
' This line should be green. \ is not an escape in VB.
```

The backslash is not an escape character, so ending quote should be considered.

**Comment by kinloongTong** [comment] 2020-06-22 01:04
I have the same problem.

**Comment by chilipepperpizza** [comment] 2020-07-08 13:26
Looks like there is a PR for this issue - https://github.com/microsoft/monaco-languages/pull/90

**Comment by fowl2** [comment] 2020-08-07 08:27
this issue is a duplicate of #1958

**Closed** 2020-09-10 08:18 UTC
Labels: *duplicate
