### ISSUE TITLE
Monaco editor encodes URL when doing Ctrl + click to follow link

### ISSUE THREAD

**Issue by nikhilexe** [Microsoft/monaco-editor#1048] opened 2018-09-04 10:14 UTC
See this code pen link https://codepen.io/nikhilexe/pen/RYwveN 

If you ctrl + click on the URL, browser will open with this URL https://abc.com/id//def/ghi basically it encodes %2F to /

If you paste this URL directly into the browser https://abc.com/id/%2Fdef%2Fghi nothing changes.

**Comment by Ajay-MS** [comment] 2018-09-24 05:50
+1  
We are seeing a similar issue.

**Comment by jrieken** [comment] 2018-09-24 07:11
duplicate of https://github.com/Microsoft/vscode/issues/25852

**Closed by jrieken** 2018-09-24 07:11 UTC
