### ISSUE TITLE
Load css for colorizing an element or a string, without an editor.

### ISSUE THREAD

**Issue by Kedyn** [microsoft/monaco-editor#1948] opened 2020-04-30 06:47 UTC
As clearly seen on the playground:
https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-syntax-highlighting-for-html-elements

The element is "colorized", but it lacks the appropriate styles to show said colorization. This is due to the fact that without an editor there is no call to StandaloneThemeServiceImpl.registerEditorContainer, which creates the monaco-colors style.

Allowing us to some how call the function to generate said style will also allow us to utilize the syntax highlighting feature of monaco-editor in places where we only want to colorize code.

**Comment by buremba** [comment] 2020-08-14 09:56
Is there any plan on making it possible? Without this feature, `monaco.editor.colorize` is useless without the actual editor in the same page.

**Comment by Kedyn** [comment] 2020-08-15 10:34
Note: one can create a page with the editor, copy the css, add said css to whatever page that uses `monaco.editor.colorize`. The only downside to said method is that one must remember to do said thing any time the editor is updated, incase something in the css is added or changed.

**Comment by alexdima** [comment] 2020-09-18 15:21
:+1: Duplicate of https://github.com/microsoft/monaco-editor/issues/1828

**Closed by alexdima** 2020-09-18 15:21 UTC
Labels: bug
