### ISSUE TITLE
URI encoded references are not resolved in JSON schema

### ISSUE THREAD

**Issue by domoritz** [microsoft/monaco-editor#1804] opened 2020-02-03 16:59 UTC
**VSCode version:** 1.41.1
**Browser:** Electron, Chrome
**OS:** MacOS

This schema encoded special characters in the reference URI. The standard says that references must be valid URIs: https://json-schema.org/draft/2019-09/json-schema-core.html#ref and can, therefore, be encoded. 

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Foo<number>": {
      "type": "object",
      "properties": {"q1": {"enum": ["x1", "x2"]}}
    }
  },
  "type": "object",
  "properties": {
    "p1": {"enum": ["v1", "v2"]},
    "p2": {"$ref": "#/definitions/Foo%3Cnumber%3E"}
  }
}
```

Monaco doesn't correctly resolve the references. 

```json
{
  "$schema": "https://gist.githubusercontent.com/domoritz/3cd0ddb8cad62ad611f301b2a8743ebf/raw/3bc4ff9350a8e9a7acb54d9683ce3a6d3c179377/schema.json", 
}
```

<img width="1616" alt="Screen Shot 2020-02-03 at 08 55 56" src="https://user-images.githubusercontent.com/589034/73673138-fe92e300-4662-11ea-92da-b04c97788d17.png">

**Comment by aeschli** [comment] 2020-02-04 07:40
duplicate of https://github.com/microsoft/vscode-json-languageservice/issues/49

**Closed by aeschli** 2020-02-04 07:40 UTC

**Comment by domoritz** [comment] 2020-02-04 15:54
Ahh, that’s where I filed the issue. Thanks.
