### ISSUE TITLE
setSelection: I get a Worker thread error on console when setting setSelection

### ISSUE THREAD

**Issue by khoshrou** [microsoft/monaco-editor#1989] opened 2020-05-28 17:08 UTC
I see a strange behaviour and I checked it in playground and seems its a general problem
I use:
**monaco-editor version:** 0.20.0
**Browser: chrome 83
**OS: windows
**Playground code that reproduces the issue:**

When i run following code i get a strange error in console
```js
// compiler options
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.ES6,
    allowNonTsExtensions: true
});

var jsCode = `
export function isNull(obj) {
    if (typeof obj == 'undefined' || obj == null) {
        return true;
    }
    return false;
}
`;

var editor = monaco.editor.create(document.getElementById("container"), {
    value: jsCode,
    language: "javascript"
});

editor.setSelection({
    startColumn: 17,
    endColumn: 24,
    startLineNumber: 2,
    endLineNumber: 2
})
```

I see this in console:

![image](https://user-images.githubusercontent.com/5165520/83171409-5336fe00-a12b-11ea-88d9-3b8697d55189.png)

if you comment compiler options error goes away.
if you change end column to 23 also error goes away

**Comment by alexdima** [comment] 2020-09-04 15:36
I can reproduce even when running `monaco-typescript` from source.

FYI @orta

**Comment by alexdima** [comment] 2020-09-18 18:26
Duplicate of #1638, because this is also fixed by https://github.com/microsoft/monaco-typescript/commit/0ac03ae5cd15be689e7806c038269eb162bc5bf0

**Closed by alexdima** 2020-09-18 18:26 UTC
Labels: bug, monaco-typescript, upstream
