### ISSUE TITLE
IPad Pro arrows don't work in editor

### ISSUE THREAD

**Issue by ryskin** [Microsoft/monaco-editor#556] opened 2017-08-21 08:14 UTC
I tested in Chrome and Safari. That's making very hard to use.

**Comment by svdoever** [comment] 2017-12-22 11:16
Only editor  found that supports ipad pro with keyboard (I use the logitech keyboard) is http://codeanywhere.com.

**Comment by 0fork** [comment] 2018-02-25 04:57
I was very excited to find Monaco because it looks fantastic for coding on-the-move but lack of proper ”smart” keyboard support is obviously a showstopper.

I know this is most likely just something that nobody implemented because nobody happened to have iPad Pro so maybe I can help. The codebase is not trivial in size anymore so I was hoping if somebody familiar with the structure could point me to the part of the code where inputs are handled?

**Comment by alexandrudima** [comment] 2018-02-28 14:13
Duplicate of #293

**Closed by alexandrudima** 2018-02-28 14:13 UTC
Labels: feature-request
