### ISSUE TITLE
ReadMore window jumps.

### ISSUE THREAD

**Issue by shoorlyne** [microsoft/monaco-editor#1031] opened 2018-08-27 13:17 UTC
monaco-editor version: 0.14.3
Browser: Chrome 67.0.3396.99
OS: macOS 10.12

When the ReadMore window is visible, scroll down the editor, and the window (along with the hover popover) jumps by a sizeable offset, which looks like below:

<img width="893" alt="screen shot 2018-08-27 at 9 09 34 pm" src="https://user-images.githubusercontent.com/20250340/44661654-d64e9000-aa3d-11e8-95c6-1d5d3948333f.png">

To repro this:
1 enter some code (Ruby in the screenshot, although I don't think it's language dependent);
2 try to bring up a completion list by entering some partial function name;
3 click the blue `Read More...` icon on the right of one of the items in the completion list, now the ReadMore window appears;
4 scroll down (or up, depending your relative position in the editor), the ReadMore window jumps, with the hover popover.

**Comment by joaomoreno** [comment] 2018-11-15 14:59
Fixed by same as #1186

**Comment by hediet** [comment] 2023-03-02 11:11
Closing due to inactivity.

If this bug still applies, please create a new issue. Make sure to select the form for bugs and include a minimal reproducible example. Thanks!

**Closed by hediet** 2023-03-02 11:11 UTC
Labels: bug, suggest
