### ISSUE TITLE
Support fontSize expressions (like "calc(16px + 1vh)"), instead of only px

### ISSUE THREAD

**Issue by cloud-walker** [microsoft/monaco-editor#1092] opened 2018-10-08 13:37 UTC
# Note
This is an issue coming from the codesandbox-client repo: https://github.com/CompuIves/codesandbox-client/issues/1152

# Why
I personally have different monitors during my work week and I often have to tweak manually the fontSize of the Editor.

# What
We can support the fontSize not only as a number, but leaving to the user the ability to use every fontSize css expression possible, this way it should be possible to hack the font size formula to automatically adapt to the user screen resolution.

**Comment by hediet** [comment] 2023-02-16 17:39
Closing as duplicate of https://github.com/microsoft/monaco-editor/issues/2242

**Closed by hediet** 2023-02-16 17:39 UTC
Labels: feature-request
