### ISSUE TITLE
[Bug] editor.getContainerDemoNode().addEventListener('paste') not working in 0.39.0 or 0.40.0

### ISSUE THREAD

**Issue by RobM-ADP** [microsoft/monaco-editor#4099] opened 2023-07-26 14:55 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#XQAAAAIkAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0kd0FVciAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8ulrCVzjWBVWZVl-YrARXWjHX0-tquUNesdygYRbQM1JUnBYwQMtMcxQzsinei1xovkFA42ozuy9UO6FfgX3AgA0708lkxObWouKxlpQ9VIV6jD4_cvjL6CTEphhzvDzcn78CW_GJj9aD-XtGoahrPQipE-nToykCS36_Uhw7D9rHqtkOUQnFRYb8CYwg06inFH0WTUAJ6hpFDrLGjJCB49De-0W0kpfQ-zp4bTyKxU5dTxp4IWgE95l_46U9f14s6uEtwU2HcGiem1NA6r6vRQnqb9QFFaOrGMs9UzodgvMJ8BaDZWnI1u62D3HFKiMCamPf8yoSebo7ICzqkaAi-BExXR8_CmakRjQrA8CLuNtEorr47qsBC5j32qsvnALnsansoOms4w7_uGl4AA

### Monaco Editor Playground Code

```typescript
const value = /* set from `myEditor.getModel()`: */ `function hello() {
	alert('Hello world!'); //<-- copy this and paste it below to reproduce issue in > 0.39.0
}
`;

// Hover on each property to see its docs!
const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "javascript",
	automaticLayout: true,
});
// in 0.39.0 and 0.40.0, this alert doesn't happen
myEditor.getContainerDomNode().addEventListener('paste', () => alert('paste'));
```

### Reproduction Steps

attempt to paste anything into the editor.

### Actual (Problematic) Behavior

 the `paste` event is not triggered. It works in 0.38.0 and earlier

### Expected Behavior

in the above code, an alert should be triggered with the text "paste" in it

**Comment by mjbvz** [comment] 2023-08-03 20:57
Duplicate of #4030

**Closed by mjbvz** 2023-08-03 20:57 UTC
