### ISSUE TITLE
SetModelMarkers shows "Undefined" as error message

### ISSUE THREAD

**Issue by valarGuru** [microsoft/monaco-editor#790] opened 2018-03-28 06:48 UTC
Hi,
I am using "[setModelMarkers()](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#setmodelmarkers)" to highlight the syntax errors in Monaco editor for my custom language. 
The message added to the marker is not getting displayed on hovering over the highlighted text.
```
{
                code: null, 
                source: null,
                severity: 3,
                startLineNumber: 1,
                startColumn: 1,
                endLineNumber: 1,
                endColumn: 4 + 1,
                message: 'Syntax error\n'
 }
```
The message always shows as "undefined".
![image](https://user-images.githubusercontent.com/37861420/38013133-a9fb3564-3281-11e8-8e45-a995640d00b0.png)
Please let me know if any thing is missed or done wrong.

monaco-editor version: 0.11.1
Browser: Chrome
OS: win 7

**Comment by alexandrudima** [comment] 2018-03-29 15:27
This works fine for me:

```js
var ed = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

monaco.editor.setModelMarkers(ed.getModel(), 'test', [{
    startLineNumber: 2,
    startColumn: 1,
    endLineNumber: 2,
    endColumn: 1000,
    message: "a message",
    severity: monaco.Severity.Warning
}])
```

![image](https://user-images.githubusercontent.com/5047891/38097739-7cb51d04-3376-11e8-8cba-b53409273aa6.png)

**Comment by valarGuru** [comment] 2018-04-02 06:19
I have tried the same, still the message says "undefined". 
` let myDiv = this.editorContent.nativeElement;
        this.editor  = monaco.editor.create(myDiv, {
            value: "function hello() {\n\talert('Hello world!');\n}",
            language: "javascript"
        });
        
        monaco.editor.setModelMarkers(this.editor.getModel(), 'test', [{
            startLineNumber: 2,
            startColumn: 1,
            endLineNumber: 2,
            endColumn: 1000,
            message: "a message",
            severity: monaco.Severity.Warning
        }])`
![image](https://user-images.githubusercontent.com/37861420/38185244-de0214f8-366a-11e8-874b-9363082f69f9.png)

Also pressing enter key it go to new line when the auto-suggestion is listed. It is expected to update the editor with the selected item from the suggestion list. 
![image](https://user-images.githubusercontent.com/37861420/38185394-7fbaa792-366b-11e8-90d2-202b49d890a7.png)

![image](https://user-images.githubusercontent.com/37861420/38185417-8accce4e-366b-11e8-8225-ea93f46aa7c9.png)


I am using Monaco editor with the angular 4. Do all these issues occur due to any incompatibility or could there be any other possible reasons?.

**Comment by ryanlin1986** [comment] 2018-04-04 00:01
I have same issue to, after upgrading to latest manco version.

**Comment by rcjsuen** [comment] 2018-04-04 00:16
@ryanlin1986 Are you also using Angular 4?

**Comment by taras-mytofir** [comment] 2018-04-04 01:40
I have similar "undefined" issue with a bit different steps but I think root cause is the same.

This example from [monaco playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults) when running from Angular 5 application produces "undefined" when you hover over warning on enum value, other warnings like "Missing property XXX" are affected too.
 
Issue is happening when [signalInnerHTML](https://github.com/Microsoft/vscode/blob/739dac65c502ba88c703b95a046150bb051b7e46/src/vs/base/browser/htmlContentRenderer.ts#L168) is executed which triggers [Promise.all](https://github.com/Microsoft/vscode/blob/739dac65c502ba88c703b95a046150bb051b7e46/src/vs/base/browser/htmlContentRenderer.ts#L127) resolving above it.

But the issue is actually on Angular's [Zone.js](https://github.com/angular/zone.js/) side as it re-defines promises. It has to be fixed in [Promise.all](https://github.com/angular/zone.js/blob/c8c599073b87025d44a4b7d6e2efea9cedfbd3e2/lib/common/promise.ts#L305) definition, index/count mismatch is happening in monaco-editor case.

The only workaround I have for now is by redefining Promise.all with a fix locally (e.g. within polyfills.ts)

```
Promise.all = function (values: any): Promise<any> {
    let resolve: (v: any) => void;
    let reject: (v: any) => void;
    let promise = new this((res, rej) => {
      resolve = res;
      reject = rej;
    });
    let count = 0;
    let index = 0;
    const resolvedValues: any[] = [];
    for (let value of values) {
      if (!(value && value.then)) {
        value = this.resolve(value);
      }
      value.then(
          ((index) => (value: any) => {
            resolvedValues[index] = value;
            count--;
            if (!count) {
                resolve(resolvedValues);
            }
          })(index),
          reject);
      count++;
      index++;
    }
    if (!count) resolve(resolvedValues);
    return promise;
}
```

**Comment by ryanlin1986** [comment] 2018-04-04 19:43
@rcjsuen  Hi, I'm not using angular at all, just plain javascript

**Comment by rcjsuen** [comment] 2018-04-04 22:00
@ryanlin1986 Can you reproduce the problem in the playground?

**Comment by valarGuru** [comment] 2018-04-05 05:28
@ryanlin1986 try using Monaco editor version 0.10.1. The "undefined" issue is there from version 0.11.0.

**Comment by ryanlin1986** [comment] 2018-04-05 16:05
@rcjsuen  turns out it is because of the Promise polyfills, same as angular issue.
Solved by myself now. Thanks for the response.
(I believe the previous version works without issue)

**Comment by taras-mytofir** [comment] 2018-04-05 22:56
Previous version of monaco-editor doesn't have this issue because there was no [signalInnerHTML](https://github.com/Microsoft/vscode/blob/739dac65c502ba88c703b95a046150bb051b7e46/src/vs/base/browser/htmlContentRenderer.ts#L168) routine there. Monaco-editor can actually do proactive check to don't have this issue by verifying if strValue is truthy [here](https://github.com/Microsoft/vscode/blob/739dac65c502ba88c703b95a046150bb051b7e46/src/vs/base/browser/htmlContentRenderer.ts#L130).

**Comment by alexandrudima** [comment] 2018-04-10 08:36
@taras-mytofir Is this an issue we should file against Angular's [Zone.js](https://github.com/angular/zone.js/). I think `Promise.all` should return resolved promises in order.

**Comment by taras-mytofir** [comment] 2018-04-10 14:31
@alexandrudima I wanted to do that but wasn't able to prepare inline example quickly which would illustrate this issue as some specific promises are created inside monaco and I didn't have time to further dig into the monaco-editor's code. Some example like [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) (this one works fine) would be good.

If somebody understands better what exactly is happening inside monaco-editor's case this is [angular 5 plunkr app](https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview) which can be used to prepare such inline example using developer tools console as promises there are Zone.js' ones.

I think after we  have such example we can create issue on Zone.js side.

**Comment by alexandrudima** [comment] 2018-04-10 16:10
@taras-mytofir Here is the repro

https://plnkr.co/edit/UO2QhIa5eeLm6tPAyAjt?p=preview

VSCode historically used WinJS Promises... and we are slowly moving to the standard `Promise`, sometimes by using `Promise.all` ...

```
  let p1 = WinJSPromise.as(3);
  let p2 = Promise.resolve(45);
  Promise.all([p1, p2]).then(res => {
    console.log(`Promise.all: `, res);
  })
  WinJSPromise.join([p1, p2]).then(res => {
    console.log(`WinJSPromise.join: `, res);
  });
```

The output I get from `Promise.all` is  `[45]`, where I would have expected `[3, 45]`, like the one from `WinJSPromise.join`. I suspect `instanceof` is used in the `Promise.all` implementation instead of checking for a `then` method...

**Comment by taras-mytofir** [comment] 2018-04-19 02:14
Created it here https://github.com/angular/zone.js/issues/1077.
Thanks for the example! Will see where discussion goes.

**Comment by buinhansinh** [comment] 2018-06-16 06:51
@taras-mytofir . Can you suggest a solution to work around this ? . I am using monaco-edtior version 0.13 with angular 5 and face the same issue

**Comment by taras-mytofir** [comment] 2018-06-18 18:54
@buinhansinh I mentioned my workaround in this [comment](https://github.com/Microsoft/monaco-editor/issues/790#issuecomment-378452532). 
There is other workaround mentioned in [linked issue](https://github.com/angular/zone.js/issues/1077#issuecomment-382882842) but I have not tried it myself.

**Comment by buinhansinh** [comment] 2018-06-19 01:43
@taras-mytofir , is it possible to use Line Decorator instead of Model Markers ? [Decorators](https://github.com/Microsoft/monaco-editor/blob/master/test/playground.generated/interacting-with-the-editor-line-and-inline-decorations.html)

**Comment by DenisVuyka** [comment] 2018-08-08 14:52
I've spent days trying to figure out why JSON validation messages won't work in Angular.  Thanks @taras-mytofir  for the https://github.com/Microsoft/monaco-editor/issues/790#issuecomment-378452532. Helps a lot as a short term solution.

**Comment by tnclark8012** [comment] 2018-09-12 18:42
@jrieken I see that removal of WinJS.Promise is an epic you're working on. Would you be open to a PR fixing this issue specifically? Changing MarkdownRenderer.getOptions' codeBlockRenderer to return a native promise? Or perhaps ModeServiceImpl._onReady to use Promise.resolve(true) instead of WinJS.Promise.as(true) ?

**Comment by jrieken** [comment] 2018-09-13 08:06
Sure, go ahead.

**Comment by alexdima** [comment] 2019-12-10 16:39
We have now migrated to native promises entirely.

**Closed by alexdima** 2019-12-10 16:39 UTC
Labels: question
