### ISSUE TITLE
Support for MarkdownString in CompletionItem

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/monaco-editor#695] opened 2018-01-19 06:41 UTC
monaco-editor version: 0.10.1
Browser: Chrome
OS: macOS

I'm building a custom completion provider and want to have support for some styling. I guess this can be done with [`MarkdownString`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#MarkdownString) as documented in the [VSCode CompletionItem API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#CompletionItem.new CompletionItem).

The [monaco API](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitem.html#documentation) does not seem to expose `MarkdownString`.

**Comment by rcjsuen** [comment] 2018-02-09 12:54
Duplicate of #689.

**Closed** 2018-02-22 23:09 UTC
Labels: duplicate

**Comment by SamVerschueren** [comment] 2018-02-23 05:07
Wow, totally missed that one. Thanks!
