### ISSUE TITLE
Undo/redo trigger does not work

### ISSUE THREAD

**Issue by myfoxtail** [microsoft/monaco-editor#2319] opened 2021-01-27 05:16 UTC
I'm trying to make a simple trigger for undo/redo functionality. Looking at the stack itself it seems like there are values, but the trigger does not work.

**monaco-editor version:** 0.21.2
**Browser:*Chrome 88*
**OS:*Mac*
**Playground code that reproduces the issue:**

```js
this.editor.trigger('whatever...', 'undo');
```

**Comment by alexdima** [comment] 2021-01-27 12:19
Duplicate of https://github.com/microsoft/monaco-editor/issues/2195

**Closed by alexdima** 2021-01-27 12:19 UTC

**Comment by myfoxtail** [comment] 2021-02-05 05:05
@alexdima thank you for the reference. Unfortunately the code in the issue you've linked does not work as intended. Here is what happens:

Adding this code for undo:
`this.editor.addAction({
      id: 'undo',
      label: 'Undo',
      run: () => {
        this.editor?.focus()
        if (!document.execCommand('undo')) {
          this.editor.getModel()?.undo()
        }
      },
    });
`
I call undo like this:
`this.editor.trigger('whatever...', 'undo');
`

I enter anything into the editor. Try to click undo: the editor content does not update to the previous state. Keep clicking on undo until the end of the stack, or in other words the initial stage before the change, is reached, and that's only when I see the change in the editor itself. What could be the problem?

**Comment by alexdima** [comment] 2021-02-05 17:01
@myfoxtail Please open a new issue with a complete sample that can be executed at https://microsoft.github.io/monaco-editor/playground.html. Also, are you trying on the latest editor version?
