### ISSUE TITLE
registerCodeActionProvider

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2602] opened 2021-08-05 07:12 UTC
If I use an asynchronous wait function that takes a long time to return, I get an error when I fire codeAction frequently
![1628147540(1)](https://user-images.githubusercontent.com/34642268/128307439-e01e49a0-5129-4b19-bc2e-44d2b2d3e0ca.png)

**Comment by rcjsuen** [comment] 2021-08-13 14:40
Looks like a duplicate of #2612.

**Closed** 2021-08-13 14:47 UTC
