### ISSUE TITLE
[Bug] Mouse click incorrectly sets the caret position

### ISSUE THREAD

**Issue by janarvaez** [microsoft/monaco-editor#3217] opened 2022-07-27 11:53 UTC
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```js
const customElement = document.createElement('div');
customElement.style.height = '100%';
customElement.attachShadow({mode: 'open'});

const customContainer = document.createElement('div');
customContainer.style.height = '100%';
customElement.shadowRoot.append(customContainer);

document.getElementById('container').append(customElement);

const editorRef = monaco.editor.create(customContainer, {
	value: `let wrapper = document.createElement('span');
wrapper.setAttribute('class', 'wrapper');
let icon = document.createElement('span');
icon.setAttribute('class', 'icon');
icon.setAttribute('tabindex', 0);
let info = document.createElement('span');
info.setAttribute('class', 'info');`,
      language: 'javascript',
});


```

### Actual (Problematic) Behavior

I created a MonacoEditor which has issues with highlighting text and setting the caret in the desired position when clicking with the mouse, and I can't figure out what's going on.

I added a few console logs as an example, and for instance, I get:
```
// log1
mouseX: 376
mouseColumn: 16

// log2
mouseX: 223
mouseColumn: 23
```

What could be interfering with the correct position of the caret in the editor? How could it be that a click further to the right return a lower column number?
The deviation is not consistent or proportional either. If I click in the same place, I do get it in the same position. But clicking in one place can have +2 columns wrong, in another to the right have about +6 columns wrong, and further to the right the caret can be even positioned -7 columns in the other direction (like in the example above).

### Expected Behavior

Clicking in the editor correctly positions the caret

**UPDATE**: I found out the issue is when using the editor inside a shadowDOM

**Comment by hediet** [comment] 2022-07-27 12:53
Can you provide an example in the playground to reproduce your issue? Thanks!

**Comment by janarvaez** [comment] 2022-07-27 13:48
Hi @hediet ! Thanks for the quick reply. I managed to get something that has similar issues with minimum code. My case is not as drastic, so in the example the caret won't move from the beginning, in my actual code it does move but to a wrong position. You can notice that if you click and type, the internal position does get moved though. I am using StencilJS for my custom elements with shadow DOM, so it might work better in my code due to stencil adding polyfills and other stuff.
Hope this helps

**Comment by hediet** [comment] 2022-07-27 13:51
I'm sorry, but we need an example in our playground to properly investigate this bug and to rule out that, for example, StencilJS polyfills cause this issue.

**Comment by janarvaez** [comment] 2022-07-27 14:10
There are some references to problems with the caret in this other issue:
https://github.com/microsoft/monaco-editor/issues/619

**Comment by lucasMarioza** [comment] 2022-09-21 13:36
@janarvaez Did you find a fix or workaround? I'm facing the same issue and using monaco inside a shadowDOM is a requirement for me

**Comment by hediet** [comment] 2023-03-13 12:08
You have to copy the CSS:

https://microsoft.github.io/monaco-editor/playground.html?source=v0.31.0-dev.20211210#XQAAAALGAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw4v2XLo-p0hMWx6TqtaYiguu-Ze1HCMrFo1TCjVGPLT5Z218HFXAvjYXjnc4hbgy7_q9nUQtRSXnUgURv_VPhCo6sAVqG0SvKaimja1QTmOemgfjAuH_ZsUCJrQ9kkDea6E5DIvOgpUg8Ooz5Syokix-8PisT_x2GKQwtZuJNiwh956-PeqaTJ4k8hkyvfbg37hDRdTkRWeeKWq9q4P2C6uBqCCrfAy7P-n00brWG8lkiN4ccS5r8ULl1pUpRuJDP7zdVMAep1-DchoNbdET213RHBHVxWlx6CHzw8dh1lvqzo2kufoQB_uxBxksEVP0UwFz5iU9yuhoVLkKQsSNRournKCvrzTi5-6tfDYinGCQ8VTLeOCb-M6rygm1wbv8ERDUpXq-fh5Li29WFZhze9AxwemNMokQULMVZ5AE6SWgTlECMf2K5uZSM7B8Q4gPEzmdSyN496XEBYe6idvwdl_7z6SveXA7QVHE5fjzutgwSxFRp8jsp_--3nuA

**Comment by janarvaezkng** [comment] 2023-03-16 08:26
https://user-images.githubusercontent.com/127384873/225558155-74b4634c-1ecc-4416-b9c7-4225afabaf0e.mov

Please look at this reproduction video

**Comment by sorinui** [comment] 2023-03-16 09:23
I also stumbled into this. It worked fine in Microsoft Edge versions prior to `110.0.1587.69` (and older Chrome versions).
The culprit seems to be `window.getComputedStyle(el, null).getPropertyValue('font');` returning an empty string now. See 
https://github.com/microsoft/vscode/blob/4c53c189a195c78a305ccce19d47341b9bee9baa/src/vs/editor/browser/controller/mouseTarget.ts#LL1037C12-L1037C12
@hediet can we reopen this issue?

**Comment by hediet** [comment] 2023-03-16 11:27
I can reproduce the bug in edge, but not chrome.

@sorinui can you look into this?

**Comment by lucasMarioza** [comment] 2023-03-16 19:45
Disabling `font-feature-settings: "liga" 0, "calt" 0;` in the dev tools fixed the bug for me, but I'm not sure it will have anyother side effects
![image](https://user-images.githubusercontent.com/16712671/225735621-6dcf7c57-742c-49e7-ae2c-8b1b78d3455c.png)

**Comment by hediet** [comment] 2023-03-20 10:46
@lucasMarioza thanks for sharing this!

Enabling/disabling this rule actually changes if `window.getComputedStyle(el, null).getPropertyValue('font');` returns an empty string or not (as @sorinui pointed out)

**Comment by jogibear9988** [comment] 2023-03-22 12:20
Has someone already raised a chrome issue?
We have the same problem, but only on some computers

**Comment by jogibear9988** [comment] 2023-03-22 12:29
I created a chrome issue (cause after switch to 111 it also happens on my computer): https://bugs.chromium.org/p/chromium/issues/detail?id=1426792

**Comment by hediet** [comment] 2023-03-22 12:42
I suggest you create a minimal reproducible example for them (not using monaco editor), demonstrating the issue that `getPropertyValue('font')` returns an empty string.

**Comment by jogibear9988** [comment] 2023-03-22 12:51
> I suggest you create a minimal reproducible example for them (not using monaco editor), demonstrating the issue that `getPropertyValue('font')` returns an empty string.

is this surely the cause of the issue?

**Comment by jogibear9988** [comment] 2023-03-22 18:09
duplicate: https://github.com/microsoft/monaco-editor/issues/3858

**Comment by janarvaezkng** [comment] 2023-03-23 07:28
> duplicate: #3858

@jogibear9988  #3858 is a duplicate of this one

**Comment by hediet** [comment] 2023-03-24 19:36
Thanks a lot for investigating!

Suggestion from @drott:

> I suggest for the Monaco editor to change the implementation of their character width measurement to recreate the font in a more accurate way by using all longhand properties, or, as a temporary workaround, rebuild a `font` string by accessing the shorthands and compiling a longhand form from that.

**Comment by tursunova** [comment] 2023-03-27 12:33
We analysed how this issue behaves in Chrome, Firefox, and Safari, looks like for Firefox Monaco editor is not accessing the `font` property for cursor positioning, that's why it is working correctly in Firefox, [details here](https://bugs.chromium.org/p/chromium/issues/detail?id=1426792#c13).

**Comment by leadpipe** [comment] 2023-04-17 19:40
FYI, we at Google are still seeing the same Chrome behavior, though in a much narrower set of circumstances, with v0.37.0 (and now also on 0.37.1).  (The good news for us is that we've found a workaround for it.  See the end of the note for details. 
 But you'll probably still want to figure out what's going on.)

It's all working fine now on Macs.  But selection continues to be broken on Windows.  Here's a synopsis of what we're seeing:
- On Windows, using Chrome 111.0.5563.147 or 112.0.5615.50, at normal resolution, the font metrics used for selection are narrower than those used to display the text.  So near the ends of lines, particularly longer ones, the last few characters appear to be cut off from the selection.  In fact, everything is selected just fine, it's just that the selection doesn't line up with the display so it's no longer WYSIWYG, which makes it essentially unusable.
- If you change your resolution to 90% or 110% in these browsers, selection lines up with display like normal.
- We've had a report that Chrome 111.0.5563.64 has no problem at 100% resolution.
- Most interesting, if you _reload the page_ the selection is drawn correctly.

Here's an example at 100% resolution (in Chrome 112.0.5615.50 on Windows) showing the problem:
![image](https://user-images.githubusercontent.com/6924328/230998001-91efee9a-8573-472b-bf31-184f2f9afe2d.png)


The same screen at 90%:
![image](https://user-images.githubusercontent.com/6924328/230998117-6d8cf097-1a97-4381-bd2c-081f0d2d828c.png)


And at 110%:
![image](https://user-images.githubusercontent.com/6924328/230998195-f00fb029-1b15-4c50-993b-a85df27c20b0.png)

The workaround we have discovered is to add the `fontLigatures` property to your IStandaloneEditorConstructionOptions:

```
const EDITOR_CONFIG: monaco.editor.IStandaloneEditorConstructionOptions = {
  ...,
  fontLigatures: '',
};

```

With that option set, selection is drawn correctly even on Windows.

**Comment by jogibear9988** [comment] 2023-04-18 05:26
@hediet 
reopwn?

**Comment by drott** [comment] 2023-04-18 06:51
The change in https://github.com/microsoft/vscode/pull/178795/files is not setting `font-feature-settings` for the measurements, which may explain the difference in measurement vs. displayed text.

**Comment by TheDunco** [comment] 2023-06-02 18:23
I am experiencing this issue in my [PayloadCMS](https://github.com/payloadcms/payload) instance which uses this package for their [Code](https://payloadcms.com/docs/fields/code) field. I'm running Chrome on MacOS. Is this the same issue or slightly different?

https://github.com/microsoft/monaco-editor/assets/44826828/17ac0a63-cd51-48f5-8d36-c333173c3ff8

**Comment by cdllqos** [comment] 2023-06-21 07:31
Situation  as @TheDunco

**Comment by hediet** [comment] 2023-06-29 12:45
I don't see this issue on Version 114.0.5735.199 (Official Build) (64-bit) on Windows, thus I assume this got fixed in Chrome.

> The change in https://github.com/microsoft/vscode/pull/178795/files is not setting font-feature-settings for the measurements

This is true, but there does not seem to be a way to consider this setting when measuring the text with `CanvasText.measureText(text: string)`, as `Canvas` only allows to set font, not font-feature-settings.

**Closed by hediet** 2023-06-29 12:45 UTC
Labels: bug, editor-shadow-dom

**Comment by drott** [comment] 2023-06-29 13:45
Re Chrome changes: We have at least not changed the `font` property serialisation behaviour changed that we made in https://chromium-review.googlesource.com/c/chromium/src/+/4018412 and which played a key role in our analysis above, so I am not sure by what change this would have been affected on the Chromium side.

**Comment by hediet** [comment] 2023-06-29 14:28
@drott thanks for letting us know! Once someone can reproduce with the latest chrome/monaco editor or vscode and can share reproducible steps, we'll reopen.

Off topic, but thanks so much for bringing back the "restart frame" feature in v8/Chrome! I use it daily and it just saves so much time!
