### ISSUE TITLE
Support placeholder when content is empty

### ISSUE THREAD

**Issue by cwtuan** [microsoft/monaco-editor#1228] opened 2018-12-08 17:29 UTC
Since `placeholder` isn't supported currently, is there any workaround?

**Comment by cwtuan** [comment] 2019-03-29 02:49
any updated?

**Comment by BeginVic** [comment] 2019-04-11 01:50
+1

**Comment by Tinysymphony** [comment] 2019-11-15 03:43
I have the same question

**Comment by hiraditya** [comment] 2020-05-24 02:33
When are we getting this feature?

**Comment by LironHazan** [comment] 2020-06-08 08:42
I will also be happy to have it (if there's anything I can do to help LMK)

**Comment by sanket03** [comment] 2020-09-14 11:04
Any updates folks?

**Comment by LironHazan** [comment] 2020-09-18 13:06
This could be easily workaround by faking a placeholder, not saying that it's optimal but definitely a legit solution 

e.g. my implementation in an Angular  app:

```angular
<div *ngIf="!editorState.text" class="placeholder" (click)="focusOnEmptyText()">
  <div class="placeholder-text"> {{placeholder}} </div>
</div>  
```

```css

  @keyframes fadeIn {
    from { opacity: 0; }
    to   { opacity: 1; }
  }

  .placeholder {
    position: absolute;
    font-family: Lato;
    font-style: italic;
    color: var(--input-border-color);
    top: 8px;
    left: 34px;
    animation: fadeIn 500ms;
    animation-timing-function: ease-out;
  }
```

**Comment by vikyd** [comment] 2020-12-03 15:16
Here is my solution: **add another element to simulate placeholder**

https://codesandbox.io/s/monaco-editor-placeholder-vue-1lurc?file=/src/components/MonacoPlaceholder.vue

**Comment by oovm** [comment] 2021-05-12 13:27
![image](https://user-images.githubusercontent.com/17541209/117982675-d5362c00-b368-11eb-887c-6a017dc71d76.png)

It seems that vscode already supports this feature, any ideas?

**Comment by dlech** [comment] 2021-07-02 01:10
I found the source code for this in VS Code: https://github.com/microsoft/vscode/blob/167b197e767beb791e3d191c24efb97865a98b42/src/vs/workbench/browser/parts/editor/untitledHint.ts

It looks like it is overlaying an element as other have suggested here.

**Comment by YukioSenpai** [comment] 2022-03-08 20:57
Any update on this ?

**Comment by BeginVic** [comment] 2022-03-08 20:58
你好！我是翁碧琴，您的邮件我已收到，谢谢~

**Comment by hediet** [comment] 2022-03-16 10:57
Duplicate of #568.

**Closed by hediet** 2022-03-16 10:57 UTC
Labels: feature-request
