### ISSUE TITLE
Non-global `addExtraLib` for TypeScript?

### ISSUE THREAD

**Issue by rf-** [Microsoft/monaco-editor#374] opened 2017-02-22 21:41 UTC
I have a use case where it would be useful to show multiple Monaco editors on a page, each set up with its own contextually-appropriate `d.ts` file. Right now it doesn't seem like there's any way to do this, since the `addExtraLib` method is global. How hard do you think it would be to make it possible to configure extra libs on a per-model or per-editor basis? I might be able to work up a PR if you guys feel like it's feasible/desirable and have any suggestions about how to structure it.

**Comment by jrieken** [comment] 2017-06-19 09:05
dupe of #262

**Closed by jrieken** 2017-06-19 09:05 UTC
Labels: monaco-typescript

**Comment by ayys110** [comment] 2017-06-29 07:03
I have the same problem. How can I change the extra lib when a editor haved loaded?
