### ISSUE TITLE
Uncaught Error: Unexpected usage

### ISSUE THREAD

**Issue by soneway** [microsoft/monaco-editor#1384] opened 2019-03-21 11:32 UTC
Uncaught Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js?8c76:468)
    at eval (webWorker.js?a9b4:39)
    at eval (errors.js?0f90:57)

**Comment by Symbolk** [comment] 2019-07-02 13:25
My solution: Configure webpack-plugin in vue.config.js, instead of webpack.config.js:
`module.exports = {
  configureWebpack: {
   plugins: [
      new MonacoWebpackPlugin({
        // available options are documented at https://github.com/Microsoft/monaco-editor-webpack-plugin#options
        languages: ['javascript', 'css', 'html', 'typescript', 'json']
      })
    ]
  }
`

**Comment by phyng** [comment] 2019-08-14 06:51
Maybe you use the unmatched model id, in my case:

```javascript
window.MonacoEnvironment = {
  getWorkerUrl: function (moduleId, label) {
    if (label === 'json') {
      return BASE_WORKER_PATH + './json.worker.bundle.js'
    }
    if (label === 'css' || label === 'scss') { // FIX SCSS Uncaught Error: Unexpected usage
      return BASE_WORKER_PATH + './css.worker.bundle.js'
    }
    if (label === 'html') {
      return BASE_WORKER_PATH + './html.worker.bundle.js'
    }
    if (label === 'typescript' || label === 'javascript') {
      return BASE_WORKER_PATH + './ts.worker.bundle.js'
    }
    return BASE_WORKER_PATH + './editor.worker.bundle.js'
  }
}
```

**Comment by alexdima** [comment] 2019-12-12 08:23
Duplicate of #1385

**Closed by alexdima** 2019-12-12 08:23 UTC
