### ISSUE TITLE
Implementing "timecapsule" of edit history.

### ISSUE THREAD

**Issue by shoorlyne** [microsoft/monaco-editor#1024] opened 2018-08-23 16:11 UTC
monaco-editor version: 0.14.3
Browser: Chrome 67.0.3396.99
OS: macOS 10.12

I'd like to implement a timecapsule feature for the edit player described [here](https://github.com/Microsoft/monaco-editor/issues/1019) using Monaco's API. Basically, this feature allows the user to navigate to any step in an edit history recorded previously.

For example, say the user has made several edits like: edit 1, edit 2, ..., edit n, which are captured in a edit history. Later on, he might want to jump to edit 5, and the editor should display the content as created up to step 5.

I break this problem down into 2 parts: replay forward, where the target step is ahead of the current step, and backward, where the target step is behind the current step.

For replay forward, I'd just call `pushEditOperations` for edits between current step and the target step (included).

For replay backward, at first I though I could call something like popEditOperations on the model, but it turns out it's not in the documentation. Therefore, I assume it's not available at my disposal. Alternatively, i think I can reconstruct the model by starting from edit 1, and call `pushEditOperations` up to the target step (included). However, this approach might not be the most efficient, since each time it has to reconstruct the model from scratch.

Do you think the implementation makes sense?

Another concern, when reconstructing the model by calling `pushEditOperations`, would the editor display the whole reconstruction process? If so, this might cause some flicker effect in the editor, and I'd like to (somehow) detach the model from the editor first, reconstruct the model, then re-attach the model to the editor again to avoid the effect. Comments on this concern welcome!

Thanks!

**Comment by troy351** [comment] 2018-08-23 17:01
I'm curious about how does user know which certain step he wants to go?
I mean I may know what the target step looks like, but I don't know the exact step number.

**Comment by shoorlyne** [comment] 2018-08-23 17:05
The user can enter a number for the target step (edit) to go to.

**Comment by troy351** [comment] 2018-08-24 02:13
I assume there are 5 steps:

1. `a`
1. `ab`
1. `abc`
1. `abcd`
1. `abcde`

and I want to go to `abc`.
The problem is, I don't know `abc` is step 3, I just know I want to go to `abc`.

**Comment by alexisargyris** [comment] 2019-01-24 14:45
To go backwards in the edit list you could try to 'undo' one by one the last edits by calling `editor.trigger('sourceName', 'undo')`. It doesn't seem to cause any major flickering.

**Comment by saurabhaditya** [comment] 2021-05-12 02:41
What do you think of implementing a smaller feature of navigating to the previous edit location/line? Similar to what Cmd-[ does in IntelliJ IDEA and in Slack. Also, Cmd-] goes to the later edit location.

**Comment by hediet** [comment] 2023-02-13 10:53
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

**Closed by hediet** 2023-02-13 10:53 UTC
Labels: feature-request, out-of-scope
