### ISSUE TITLE
Monaco Editor in NW.js

### ISSUE THREAD

**Issue by toyssamurai** [microsoft/monaco-editor#333] opened 2017-01-23 01:10 UTC
Hi,

I am trying to get the monaco editor running in NW.js. I did a search on Google, and found nothing about that, so I decided to use the Electron example as my starting point (https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-electron/index.html). Unsurprisingly, the example does not work.

To make a long story short, after many trials, I ended up with the following codes (FYI, I placed the folder "monaco-editor" inside a folder called "js" under the NW.js root):

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Hello World!</title>
	</head>
	<body>
		<h1>Hello World!</h1>
		<div id="container" style="width:500px;height:300px;border:1px solid #ccc"></div>
	</body>

	<script>
		// Monaco uses a custom amd loader that over-rides node's require.
		// Keep a reference to node's require so we can restore it after executing the amd loader file.
		var nodeRequire = require;
	</script>

	<script src="js/monaco-editor/min/vs/loader.js"></script>

	<script>
		// Save Monaco's amd require and restore Node's require
		var amdRequire = require;
		require = nodeRequire;
		require.nodeRequire = require;
	</script>

	<script>
		amdRequire.config({
			baseUrl: 'js/monaco-editor/min'
		});

		// workaround monaco-css not understanding the environment
		self.module = undefined;

		// workaround monaco-typescript not understanding the environment
		self.process.browser = true;

		amdRequire(['vs/editor/editor.main'], function() {
			editor = monaco.editor.create(document.getElementById('container'), {
				value: [
					'function x() {',
					'\tconsole.log("Hello world!");',
					'}'
				].join('\n'),
				language: 'javascript'
			});
		});
	</script>
</html>
```

This is the closest I could get. First of all, I no longer get any errors from the codes above. Secondly, the editor actually, sort of, loaded. However, something appears to be missing as the layout of the editor is completely messed up

![monacoinnw](https://cloud.githubusercontent.com/assets/14955849/22187927/d1303154-e0dc-11e6-81bc-1a382d8e1dff.jpg)

As you can see, the editor did seem to be, at least, attempting to initialize. Unfortunately, at this point, I am totally lost, and don't know what else I could do to make it work. Any suggestions how I can fix that would be really appreciated.

BTW, below are the reasons for the changes I've made to the Electron examples:

1. Instead of saving **global.require**, I saved **require**. If I saved global.require, I would end up having this error: _amdRequire.config is not a function._

2. I removed the codes dealing with the baseUrl. If I left them there, I would actually get a "**no such file or directory**" error, and the editor wouldn't even load at all (unlike the messed up version as shown in the screenshot above).

Thanks for help.

**Comment by alexandrudima** [comment] 2017-01-23 08:52
You are very very close indeed. The editor looking like that is a hint towards that the `editor.main.css` hasn't been loaded. You can load it on your own via a link tag annotated with `data-name` if you can't get the css loader plugin to find it:

```html
<link rel="stylesheet" data-name="vs/editor/editor.main" href="../node_modules/monaco-editor/min/vs/editor/editor.main.css">
```

Would you be interested in submitting a PR to monaco-editor-samples for NW.js?

**Comment by toyssamurai** [comment] 2017-01-25 13:20
Wow! That works. I can't believe all I need is just the CSS.

> Would you be interested in submitting a PR to monaco-editor-samples for NW.js?

I would love to. I've never done it before, though. Is there a page where I can read all the requirements before I do that?

**Comment by mbana** [comment] 2017-01-26 18:36
mmm. how odd. i had a similar if not the exact same issue.
i didn't try @alexandrudima solution as i didn't think a missing css file would cause this issue.

now... what i think the problem is or at least fixed by problem was:

```html
	<body>
		<h1>Hello World!</h1>
		<div id="container" style="width:500px;height:300px;border:1px solid #ccc"></div>
	</body>
```

`container` does through this check https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/dom.ts#L49.
is `NW.js` doing something special? anywho setting a breakpoint there and checking the returned value might lead to something.

if you have a repo to clone, i could possibly verify that it is the same issue.

**Comment by rebornix** [comment] 2017-02-04 04:26
@mbana NW is actually almost the same as Electron. It renders HTML in webkit with access to Nodejs. You can give it a try from my fork https://github.com/rebornix/monaco-editor-samples/tree/master/sample-nwjs and run `npm install` then `/Applications/nwjs.app/Contents/MacOS/nwjs .`

@toyssamurai there isn't any page about contribution to this repo. You can add a new folder to the root of this repo, put the NW.js sample project into that and that's all, look forward to your PR! I only have two tiny suggestions
1. Add `monaco-editor` dependencies to the `package.json` file of the NW project and add the nested `node_modules` into `.gitignore`.
2. Add a readme for this NW project like reminding users to install npm packages before launching the app.

Let me know if you have any problem :)

**Comment by alexdima** [comment] 2019-12-10 15:51
We now have samples at https://github.com/microsoft/monaco-editor-samples/tree/master/nwjs-amd and https://github.com/microsoft/monaco-editor-samples/tree/master/nwjs-amd-v2

**Closed by alexdima** 2019-12-10 15:51 UTC
Labels: integration, question
