### ISSUE TITLE
unconfirmed text of Japanese IME collapse to one character

### ISSUE THREAD

**Issue by karino2** [Microsoft/monaco-editor#320] opened 2017-01-17 14:49 UTC
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: Windows 8

Reproduce step:
1. Go to playground https://microsoft.github.io/monaco-editor/playground.html
2. Type some Japanese text like あいう without pressing ENTER key.

Expectation:
Show あいう with underline (as usual for Japanese input).

Actual: 
Show last character only, in this case う.

Other Info:
VS Code handle correctly.

**Comment by alexandrudima** [comment] 2017-01-17 16:27
Looks like a change in Chrome v55. I have just confirmed this works as expected in Chrome v53

**Comment by alexandrudima** [comment] 2017-01-17 16:41
It looks indeed like a regression in Chrome v53. Chrome version 57.0.2984.0 canary emits compositionupdate events with the full text being composited, and not with only the last glyph (as Chrome v53 does)

**Comment by alexandrudima** [comment] 2017-01-17 17:00
Mostly for posterity, proof that `compositionupdate` is broken in Chrome v55:

### Firefox (OK)
![japanese-ff](https://cloud.githubusercontent.com/assets/5047891/22030662/98bc9a9e-dcde-11e6-8fbb-803148d9bc60.gif)

### Chrome 53.0.2785.0 (OK)
![japanese-53](https://cloud.githubusercontent.com/assets/5047891/22030684/aefd7062-dcde-11e6-9749-94e5290a6a88.gif)

### Chrome 55.0.2883.87 (NOK)
![japanese-55](https://cloud.githubusercontent.com/assets/5047891/22030702/c1359426-dcde-11e6-9465-abc93bcf7316.gif)

### Chrome Canary 57.0.2984.0 (OK)
![japanese-57](https://cloud.githubusercontent.com/assets/5047891/22030734/d95487ba-dcde-11e6-9dfc-f17004bc310c.gif)

**Comment by alexandrudima** [comment] 2017-01-17 17:02
Chromium issue confirming this was introduced in M55 and fixed in M57:

https://bugs.chromium.org/p/chromium/issues/detail?id=677050#c9

**Comment by karino2** [comment] 2017-01-17 17:02
I also try dev-cahnnel (57.0.2979.2) and confirm to work correct as you said.
For my side, it's OK to close this issue now.

Thank you for your quick investigation.

**Closed** 2017-01-17 17:11 UTC
Labels: bug
