### ISSUE TITLE
Paste menu item missing and cut/copy/paste not work

### ISSUE THREAD

**Issue by zimolab** [microsoft/monaco-editor#2604] opened 2021-08-05 18:51 UTC
**monaco-editor version:** 0.26.1
**Browser:**  JavaFx webview/Edge
**OS:** windows 10

There is a strange issue about cut/copy/paste command in monaco editor, ant i think it is related to the clipboard mechanism.
The issue is like this:

With the same code base, cut/copy/paste works fine in browser: the 3 actions are present in the context menu and perform action as normal. 

While in javafx webview: 
 a) the paste menu item is missing in the context menu.
 b) if you have something in your clipboard before you can still use ctrl-v to paste it into the editor, however if you use cut/copy inside the editor and then use ctrl-v you will get nothing, it just like cut/copy clear the origin content in the clipboard but failed to put new content into it.

code is simple.

JS
```
import * as monaco from "monaco-editor"
import {
    editor,
    IPosition, IRange,
    ISelection, Selection
} from "monaco-editor"

var monacoEditor = monaco.editor.create(document.body)
```

Kotlin(javaFx)
```
package com.zimolab.testifyfx.view

import com.zimolab.testifyfx.JsArray
import javafx.concurrent.Worker
import javafx.scene.layout.VBox
import javafx.scene.web.WebEngine
import javafx.scene.web.WebView
import netscape.javascript.JSObject
import tornadofx.*

class MainView : View("") {
    override val root: VBox by fxml("/view/Testify.fxml")
    val webView: WebView by fxid()
    val webEngine: WebEngine by lazy {
        webView.engine
    }

    init {
        webEngine.load(javaClass.getResource("/dist/index.html")!!.toExternalForm())
        webEngine.loadWorker.stateProperty().addListener { observable, oldValue, newValue ->
        }
    }
}
```

**Comment by zimolab** [comment] 2021-08-06 14:54
Edit: I think this issue is related to the javafx webview, because i tried to load the official playground page in webview i found the paste menu item was still missing and the copy/cut action did not work too. For there is no usable debugger tool for javafx webview so i cannot figure out what happening in the underlying js executing. Now i am trying to remove the internal copy/cut/paste actions and implement my own copy/cut/paste mechanism with the local storage api or with the power of java bridge. May be someone can tell me how to remove builtin actions or commands. Thanks in advance.

**Comment by hediet** [comment] 2022-12-13 14:18
Closing as this seems to be caused by javafx.

**Closed by hediet** 2022-12-13 14:18 UTC
