### ISSUE TITLE
Object doesn't support property or method 'remove' in 0.16.0 on IE

### ISSUE THREAD

**Issue by nico-bellante** [Microsoft/monaco-editor#1357] opened 2019-03-11 21:44 UTC
**monaco-editor version:** 0.16.0
**Browser:** IE
**OS:** Windows

**Steps or JS usage snippet reproducing the issue:**
1.) Go to [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html) in Internet Explorer
2.) Right click inside the editor to bring up the right click menu.
3.) Attempt to left click to dismiss menu.

At this point you will get the following error:
```
SCRIPT5022: Object doesn't support property or method 'remove'

TypeError: Object doesn't support property or method 'remove'
   at onHide (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:1425:855)
   at t.prototype.hide (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:267:101)
   at t.prototype.hideContextView (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:1399:375)
   at Anonymous function (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:1425:557)
   at e.prototype.fire (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:57:216)
   at Anonymous function (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:702:714)
   at e.prototype.fire (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:57:216)
   at Anonymous function (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:132:595)
errors.ts (22,6)
```

**Comment by Zlatkovsky** [comment] 2019-03-11 23:09
@alexandrudima , note, this is a blocker for us in moving to Monaco 0.16.X in Script Lab.
https://github.com/OfficeDev/script-lab/issues/667

**Comment by mattmasson** [comment] 2019-03-12 14:26
I can reproduce this as well (IE embedded control, Edge compatibility)

```
TypeError: Object doesn't support property or method 'remove'
   at onHide (eval code:90:21)
   at ContextView.prototype.hide (eval code:180:13)
   at ContextViewService.prototype.hideContextView (eval code:59:9)
   at Anonymous function (eval code:76:46)
   at Emitter.prototype.fire (eval code:509:25)
   at Anonymous function (eval code:417:17)
   at Emitter.prototype.fire (eval code:509:25)
   at Anonymous function (eval code:806:25)
   at Anonymous function (eval code:22:21)
```

**Comment by mattmasson** [comment] 2019-03-12 15:39
Seems like it might have been this [commit in vscode](https://github.com/Microsoft/vscode/commit/d96141bb7af896a4bf2a1daa4058188d25f0dc21#diff-12bc40c6ff65411b8204a30f64e1334e) ([PR 64099](https://github.com/Microsoft/vscode/pull/64099))

/cc @sbatten

**Comment by rebornix** [comment] 2019-03-12 18:43
@sbatten and me will work on a fix and publish a new version.

**Comment by rebornix** [comment] 2019-03-14 22:06
0.16.1 is published with the fix.

**Closed** 2019-03-14 22:07 UTC
Labels: bug, important

**Comment by Zlatkovsky** [comment] 2019-03-14 23:30
Thanks, @rebornix .
Note that you may  want to update https://microsoft.github.io/monaco-editor/playground.html to use the latest, right now it looks like it's still grabbing the old 0.16.0 files:

![image](https://user-images.githubusercontent.com/2230453/54398233-74224900-4676-11e9-9a60-f00a6236ec1f.png)

**Comment by rebornix** [comment] 2019-03-14 23:48
It seems the auto update fails to publish the website (probably because I update the branch inproperly). I'll update the website.

**Comment by rebornix** [comment] 2019-03-15 20:27
Website published. @Zlatkovsky thanks!

**Comment by Zlatkovsky** [comment] 2019-03-15 20:28
Great.  @rebornix , could you please take a look at the other IE11 issue as well, that's also possible to repro using the site?  Or redirect to a colleague?  See #1367.
