### ISSUE TITLE
Feature Request: Virtual Space support

### ISSUE THREAD

**Issue by wizzard0** [microsoft/monaco-editor#919] opened 2018-06-16 13:27 UTC
monaco-editor version: 0.13.1
Browser: All browsers
OS: All OS
Steps or JS usage snippet reproducing the issue: (review editor options and VS Code issues carefully, discover there's no virtual space)

Feature Description: https://blogs.msdn.microsoft.com/zainnab/2010/02/28/understanding-virtual-space/
Also known as "cursor past end of line", "cursor in empty space" or "cursor past end of file".

First, Monaco is absolutely great and miles ahead of competitors, especially in performance. But the lack of virtual space hurts each time I try to use it. A matter of taste and a habit, indeed, but keeps me from adopting VS Code as well as from using Monaco in personal projects/recommending it elsewhere. 

Would be great to know if it's even on the roadmap, and/or how hard does it look given the current Monaco internals (even without related multiple cursors/full rectangular selection support)

Thanks in advance!

**Comment by GeekyMonkey** [comment] 2020-12-09 15:38
This is the one thing holding me back from using Code.

**Comment by m6502** [comment] 2021-05-26 10:02
https://github.com/microsoft/vscode/issues/13960

**Comment by Phyyl** [comment] 2021-07-14 03:37
This is a must have for any code editor... I use this in VS IDE all the time when selecting vertically (with mouse and with shift+alt+arrows). Please add this. Like @GeekyMonkey, this is one the only things that's holding me back from using it daily.

**Comment by hediet** [comment] 2021-07-14 07:38
I think it is better to track features that are not monaco-specific in the VS Code repository, as all major Monaco features are driven by VS Code feature requests anyway.
As there is already an issue for it (https://github.com/microsoft/vscode/issues/13960), to avoid duplicated discussions, I'm going to close this issue.
Please subscribe to the linked issue to stay updated on this topic.

**Closed by hediet** 2021-07-14 07:38 UTC
Labels: feature-request

**Comment by wizzard0** [comment] 2021-07-14 07:45
> not monaco-specific 

wait, this feature is 100% not vscode-specific but monaco-specific. Monaco is used not just in vscode

**Comment by hediet** [comment] 2021-07-14 07:55
Monaco is built from parts of the sources of VS Code.
Once there is Virtual Space support in VS Code, it will also be supported by Monaco.
It is very unlikely though that there will be exclusive support for Virtual Space in Monaco without supporting it in VS Code.

**Comment by wizzard0** [comment] 2021-07-14 07:57
@alexdima Can you please comment whether you agree virtual space is a component feature or an app feature? Thanks.

**Comment by m6502** [comment] 2021-07-20 07:57
> As there is already an issue for it ([microsoft/vscode#13960](https://github.com/microsoft/vscode/issues/13960)), to avoid duplicated discussions, I'm going to close this issue.
> Please subscribe to the linked issue to stay updated on this topic.

Issue 919 is a duplicate of issue 13960?
