### ISSUE TITLE
How to use the ESM to support the Monaco-Editor menu in Chinese

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2633] opened 2021-08-25 03:07 UTC
I know min or dev can be set to Chinese using require but I would like to ask how do I set it to Chinese if I use import （esm）

**Comment by spahnke** [comment] 2021-08-25 06:30
Duplicate of https://github.com/microsoft/monaco-editor/issues/1514

**Closed** 2021-08-25 09:47 UTC
